### ISSUE TITLE
Alignment will probably require implementation-defined behavior

### ISSUE THREAD

**Issue by titzer** [WebAssembly/design#105]
It seems that some ARM implementations may ignore the low order bits of unaligned memory accesses and thus round down to the next aligned address. That would mean that every access that the engine cannot prove is properly aligned would need a dynamic check (since these processors won't cause a hardware fault). That may be too slow or too much code.

Would it be reasonable to spec aligned/unaligned accesses thusly?

- All accesses require alignment to be specified.
- Load/Store[aligned=true] have implementation-defined behavior when the offset is not actually aligned.
- Load/Store[aligned=unknown] never have implementation-defined behavior, but may be slow on some architectures when the offset is not actually aligned.

For both kinds of accesses we could specify a sanitizer mode that will trap on Load/Store[aligned=true] (actually not aligned) and profile or warn on Load/Store[aligned=unknown] (actually not aligned).

The above would allow the engine to omit checks for the [aligned=true] case, accepting whatever the hardware does, but still require it to emit checks for [aligned=unknown] on these processors.

**Comment by sunfishcode** [comment]
I've recently been told that there are some relevant Android devices that have alignment trapping which is imprecise, meaning it may not be feasible for an implementation to fix up misaligned accesses. I don't know the specifics yet, so I don't have a recommendation for what we should do yet, but I do want to outline a possible backup plan.

A backup plan is that we say that it's nondeterministic whether a misaligned accesses succeeds or traps (and the trap wouldn't be recoverable in this case). That still rules out silent behavior changes (and ARMv5), so we could broaden the set of supportable platforms while still avoiding the worst of the portability risks.

**Comment by lukewagner** [comment]
Another alternative is, if this is only a small % of users (and I assume old kernel versions that time will obsolete), keep the spec deterministic and any wasm impl on those devices can choose between being incorrect wrt the spec (faulting) or branching on alignment before each load/store (as part of the bounds check) at some runtime cost.  I think this is preferable since, whether or not the standard declares trapping as a valid nondeterministic execution, it will be a little-tested path since most devs won't have one of these devices.

**Comment by sunfishcode** [comment]
Trapping may be an untested path, but it's a very short one :-). And we already have nondeterministic trapping when a program runs out of callstack space ("at any time"), so it's not a great new imposition. I think it'd be nicer to acknowledge this in the spec than issuing exemptions that create a de-facto spec on top of the original one.

**Comment by lukewagner** [comment]
Well, the option I'd expect engines to instead take (e.g., that I would want FF to take) in this case would be to use dynamic branching to handle misaligned accesses; otherwise, spec-blessed or not, programs are going to fault when running on the platform (especially since we make misaligned accesses Just Work).

**Comment by titzer** [comment]
This issue needs some more investigation when we get closer to having a
full-performance native implementation, but there is also a semantic
question here.

At the risk of making the spec a little weaker, it'd be nice to quash a
potential proliferations of slightly spec-noncompliant implementations. In
particular, how far are we willing to let the polyfill get out of
compliance in order to allow it to make use of the slightly different
alignment semantics of asm.js?

**Comment by pizlonator** [comment]
Yes, 32-bit ARM can take a hit if we have misaligned access. They can trap or not based on some CPU flag, and I've found that this flag is often set to trap.

Incidentally, just this past week I had to put out fires because of a C program that behaved differently on different platforms because of alignment. It reminded me how important it is for an allegedly-portable platform to have uniform semantics on such things. 

As a user, I think that I'd prefer for my code to run slower on old ARMs than to exhibit different behavior. As an implementer, I wonder how many of the software is-aligned checks would remain if you speculate aligned and deoptimize on misaligned.

-Fil

**Comment by lukewagner** [comment]
@titzer I'm not sure in which direction you're talking about weakening the spec, but it sounds like allowing nondeterministic auto-alignment which seems like making the spec a *lot* weaker.  As I was arguing above: regardless of what we specify, If only a few platforms exercise a certain nondeterministic path, then they're just as likely to be broken and are better off taking a speed hit to conform to the norm.  In the initial transition phase (when a significant % of the browser market does not have native wasm), the asm.js polyfill will be a tier 1 testing platform so errors will be caught just like they are caught today with pure asm.js (to make it easy to catch bugs, the polyfill can have a throw-on-misaligned option analogous to Emscripten `SAFE_HEAP`).  As native wasm support becomes ubiquitous, we might see apps coming out that include misaligned accesses (because they only tested native support) but, at that point, we could change the polyfill default to issue byte loads (so it also Just Worked, albeit more slowly).  We could also mitigate this issue by having a "Strict mode" browser devtool option that we loudly and widely encouraged everyone to test with.

**Comment by titzer** [comment]
@luke

It only introduces nondeterminism if the program lies about its alignment
annotations. If a program is conservative and always specifies unaligned,
it will not experience nondeterminism.

We've had some input from some MIPS partners that they were worried their
platform would be severely punished, since the alignment issue is
complicated and hardware that handles unaligned access at full speed is
still in the pipeline.

I'm not exactly sure what value the alignment attribute has if
implementations will generate very similar code for both cases. E.g:


On platforms that have fast hardware-based unaligned support:

load[aligned] x y:
  mov %r0, [%r1 + %r2]

load[unaligned] x y:
  mov %r0, [%r1 + %r2]

On platforms with slow (trap-based) unaligned support:

load[aligned] x y:
  mov %r0, [%r1 + %r2]

load[unaligned] x y:
  if(not_aligned) goto out_of_line_code
  mov %r0, [%r1 + %r2]

On platforms with masking behavior:
load[aligned] x y:
  if(not_aligned) goto out_of_line_code
  mov %r0, [%r1 + %r2]

load[unaligned] x y:
  if(not_aligned) goto out_of_line_code
  mov %r0, [%r1 + %r2]

The only difference I see is on the trap-based platforms, you roll the dice
and let the program pay the big performance penalty. But if these platforms
are not tested on often, then there will probably be a creep of programs
that have unaligned accesses and never noticed because they always ran on
the other platforms. In order to avoid that we'd have to specify a debug
mode where unaligned accesses trap so that people could flush those bugs
out early. But that is essentially specifying nondeterminism, but only in
debug mode.

**Comment by lukewagner** [comment]
> We've had some input from some MIPS partners that they were worried their platform would be 
> severely punished, since the alignment issue is complicated and hardware that handles unaligned 
> access at full speed is still in the pipeline.

Are there any new constraints we need to be considering here wrt MIPS?  I think experience with asm.js shows that misaligned (as reported by LLVM) accesses are generally rare.  Also, I don't see how adding nondeterminism makes the theorized problem go away since if the desired codegen is branching, you can always use branching with the deterministic Just Works semantics.

> It only introduces nondeterminism if the program lies about its alignment annotations. If a program is 
> conservative and always specifies unaligned, it will not experience nondeterminism.

But if unaligned offers performance advantages (and it would on trap-based platforms), then compilers would be encouraged to always emit aligned and thus most programs would have the nondeterminism.

> But if these platforms are not tested on often, then there will probably be a creep of programs
> that have unaligned accesses and never noticed because they always ran on
> the other platforms.

This is going to happen regardless, unless we can get most people developing/testing in debug-mode.  Given that misaligned accesses are going to happen, having it run, but execute slower seems like the best option (compared to crashing).  Also, while an individual access may be 1000x slower, amortized over a whole program it's likely a a much smaller % and so there is a good chance the app will stay usable.  Lastly, in the worst case, if this was becoming a problem in practice, trap-based platforms could always mitigate by switching to always-branch (or byte loads).

> In order to avoid that we'd have to specify a debug mode where unaligned accesses trap so that
> people could flush those bugs out early. But that is essentially specifying nondeterminism, but only 
> in debug mode.

The debug mode I was imagining would be a pure devtools option, not a mode in the wasm spec, and would deterministically fault on all misaligned accesses (and so have a small perf hit on x86).  If it's a devtool, I don't think it counts as nondeterminism any more than a debugger changing values is nondeterministic.

**Comment by jfbastien** [comment]
The worry on these platform is that **regular** accesses either need to be split up into byte accesses and then merged, or signal handling must be used. This isn't a "pay for what you use" approach to performance: you may have no unaligned accesses and performance will suffer, or you'll need to use a signal handler which folks have said they don't want to mandate. See the [Linux MIPS](http://www.linux-mips.org/wiki/Alignment) docs for details.

**Comment by lukewagner** [comment]
@jfbastien Yes, but what is the nondeterminism buying us in those cases?  If you have to branch on misaligned access then you can just as well implement Just Works deterministically as something else nondeterministic.  The only case I can see nondeterminism buying something is for auto-aligning platforms which would not otherwise have to branch.  Is this the MIPS use case?

**Comment by lukewagner** [comment]
... and that is just from the performance perspective.  From the perspective of "I want apps that run on other platforms correctly to also run on my auto-aligning platform correctly", then you don't want to be the one oddball platform that auto-aligns; of *course* apps are going to randomly break for you.  That's why I was saying above (and iiuc @pizlonator was also saying) that, even if nondeterminism was a choice, I'd still want to implement Just Works semantics just to minimize bustage.

**Comment by pizlonator** [comment]
Do we have data on what the penalty for misaligned-accesses-do-weird-things platforms will be, if we require misaligned accesses to just work, but then also roll up our sleeves and actually optimize that case?  I’ve been pondering this a bit.  If you have profiling that tells you what the low bits of a pointer tend to look like, then you can emit optimized code that is biased for either aligned or misaligned, and you could even speculate that the pointer was already aligned which allows you to blow away repeated alignment checks on that pointer - and probably alignment checks on most pointers derived from that one, if the derivatives are just “ptr + C” where C is a multiple of the appropriate word size.

Since we probably do not have such data, it seems we have the following to choose from, and the following mitigations in a subsequent version if the performance isn’t good enough:
	1) MVP only has access modes that Just Work when misaligned, old ARM and MIPS be damned.  Future versions introduce new access modes, which allow for better performance on old ARM and MIPS.
	2) MVP only has access modes that Trap when misaligned, x86 and ARM64 be damned.  Future versions introduce new access modes, which allow for better performance on x86.
	3) MVP only has access modes that are undef when misaligned.  Future versions nail down the undef to mean either “Just Work” or “Trap”, depending on our empirical findings.

I prefer (1) because it’s the most forward-looking.  I like (2) more than (3) because undef has a high likelihood of causing confusion for developers.

-Filip

**Comment by sunfishcode** [comment]
C/C++ developers can also catch misaligned accesses by using UBSan (aka -fsanitize=undefined) ([clang](http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation), [GCC](http://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/)).

**Comment by sunfishcode** [comment]
I agree with what's said above; nondeterminism in anything other than trapping-or-not doesn't help much because it just converts applications that were slow on said architectures to applications that behave wrong on the same architectures.

I still believe "it's nondeterministic whether misaligned accesses trap" (misaligned means dynamic alignment is less than static alignment) is worth considering if we can't do "everything always just works". Implementations on MIPS/etc. might then choose to have two modes, "fast" (traps) and "slow" (branches). "fast" could be the default, and when a program traps (which should be rare), the implementation could (for example) automatically restart the program, blacklisting it to "slow" mode thereafter (for example). Blessing this in the spec means that spec conformance can remain something which is done by default. And This approach would mean that there's no mandate to catch and handle signals, and it would permit "pay for what you use", addressing two of @jfbastien's concerns above.

ARMv5 would just have to do "slow" mode, but there's a fair amount of agreement here that ARMv5 is old and not worth complicating the spec for.

**Comment by titzer** [comment]
The other important implementation that does masking (i.e. forcible
alignment) is the polyfill to asm.js. If we go with "always works", then
the polyfill is going to be incorrect for misaligned accesses. How strongly
do we value the correctness of the polyfill? Or conversely, how specially
do we treat the polyfill in comparison to any other implementation? When a
spec comes, will we need to add special exceptions for it, or will it
remain spec incompliant?

**Comment by sunfishcode** [comment]
There is [a plan for the polyfill](https://github.com/WebAssembly/design/blob/master/Polyfill.md#polyfill-deviations). It's a little awkward, but it's an attempt at a practical strategy to break with JS semantics in certain key areas.

If an implementor is thinking "the polyfill masks addresses, so why shouldn't I do it too?", we'll remind them that any time the polyfill's alignment masking actually affects anything, then the program doesn't work right under the polyfill. "Program doesn't work right" isn't something that we anticipate implementors should need to emulate [0].

[0] And we aren't worried about programs coming to depend on the polyfill semantics either, because we already know that popular native wasm implementations won't be masking.

**Comment by paul99** [comment]
@tizer asked me to comment here, I work at MIPS/Imgtec on V8.

As discussed above, existing MIPS cores trap on unaligned accesses. Any remotely modern kernel will fixup the un-aligned load/store (same result as  x86). It just works, but these accesses are slow.

Newer cores (in development) will support unaligned accesses in hardware.

Of course, code that claims [aligned=true] but lies could tank performance.

Detection and deoptimization to safe accesses would be trivial with a signal handler (though we have avoided those due to concerns with sandboxing, etc.) There are pure software methods discussed by others above.

So MIPS does not introduce indeterminism, and the performance impact of 'Just Work when misaligned' can be mitigated over time.

The debug-mode dev tool support would be excellent.

**Comment by lukewagner** [comment]
@paul99 Just to be clear, though: on all the MIPS archs you're considering, it is possible to trap on unaligned access in user-mode?  That would make the MIPS case equivalent to the slow-ARM case we've already been considering.

@sunfishcode's comment suggests a hybrid solution that doesn't require any semantically-visible modes: the engine optimistically compiles with trap-on-misaligned and, after a significant number of traps, recompiles into branching (dynamically, swapping out on-stack or, if nothing else, between turns of the event loop).

**Comment by jfbastien** [comment]
@lukewagner IIUC you don't need to trap in usermode, the kernel traps and fixes up the access for you and usermode goes on without knowing about this.

**Comment by lukewagner** [comment]
@jfbastien I realize that, but I was asking if it was *possible* since that enables several of the things we've been talking about.

**Comment by sunfishcode** [comment]
On Linux MIPS, according to the docs linked to above, [a process can easily chose which it wants](http://www.linux-mips.org/wiki/Alignment#Controlling_the_kernel_unalignment_handling_in_your_own_code).

**Comment by paul99** [comment]
@lukewagner Yes, its possible to disable the kernel fixups, and then install signal handler to catch the alignment errors in user-mode. (As @sunfishcode just said :)

**Comment by lukewagner** [comment]
Ok, thanks.  So given all the above, I'm still not seeing how nondeterministic fault-on-misaligned access would help out MIPS here.  What is the desired codegen?

**Comment by paul99** [comment]
I may be missing your point, but I don't see any nondeterminism here. Code known to be unaligned could use byte accesses and construct the larger words. Code presumed to be aligned but with rare unaligned accesses would just work. Code with frequent unaligned accesses would also work, but would have terrible performance. I would like to detect that case and fall back to byte accesses. 

I don't see this as essential for MVP, but desirable in the longer term, as we see how rare or common these unaligned accesses are. I think this mostly agrees with Dan's https://github.com/WebAssembly/design/issues/105#issuecomment-125414141

**Comment by lukewagner** [comment]
@paul99 The big question being discussed in this issue is whether we should weaken the specified semantics of loads/stores from always Just Working to possibly faulting (i.e., the wasm app crashes).  It sounds like that's not what you're asking for, though, which is good.

**Comment by lukewagner** [comment]
Actually, it's possible I misread you.  When you say "I would like to detect that case and fall back to byte accesses.", I assumed you meant "dynamically and transparently".  That is, you'd somehow (user-mode signal handler?  perf counter?) detect a lot of this misaligned access going on and then generate a new version of code that uses byte accesses and swap in this new code.  Is that what you meant?

**Comment by paul99** [comment]
> I assumed you meant "dynamically and transparently". That is, you'd somehow (user-mode signal handler? perf counter?) detect a lot of this misaligned access going on and then generate a new version of code that uses byte accesses and swap in this new code. Is that what you meant?

Yes, this is exactly what I meant.

From https://github.com/WebAssembly/design/issues/105#issuecomment-108019173 there is statement "Obligatory aligned/unaligned distinction, with unaligned operations Always Working but possibly being slow". 

The aligned/unaligned distinction seems very valuable for MIPS, where knowing ahead that accesses will be unaligned will let us generate reasonable code for that case, and only the 'promised aligned but lied' case would give us the perf hit (which we could dynamically detect and generate replacement code).

**Comment by lukewagner** [comment]
@paul99 Great, then it also sounds like you're happy with the [current state of the design](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#alignment).

Are there any more outstanding reasons to consider weaking the semantics of misaligned loads from Just Working or can we close this issue?

**Comment by paul99** [comment]
@lukewagner Now I see where we were misunderstanding each other.

In the spec I see no mention of [All accesses require alignment to be specified.](https://github.com/WebAssembly/design/issues/105#issue-84107089) The discussions here seemed to all require a promise of the alignment intent, and then various methods for handling actual alignment differing from the promised alignment. Having such an attribute would be super helpful in generating the right code to start with for data that is a-priori known to be unaligned, and I had presumed that would exist. 

Then the exceptions to that can be dealt with dynamically/transparently. All cases would just work, but the places that would tank performance would be far fewer. 

But if there is no distinction on alignment, I would think it would be uniformly ignored, and no one would even notice the small performance hit on Intel, for example.

**Comment by lukewagner** [comment]
@paul99 The first sentence of the [alignment section](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#alignment) says "Each linear memory access operation also has an immediate positive integer power of 2 alignment attribute."  Is this not what you mean?

**Comment by paul99** [comment]
@lukewagner My apologies, I previously misread the first paragraph. I now see that the alignment attribute is precisely what I was looking for. The whole section sounds good to me as written. Sorry for the churn!

**Comment by lukewagner** [comment]
No problem, it's good to talk through these issues to make sure we understand.  Think we can close this issue @titzer?

**Comment by rodolph** [comment]
Hi,
  
@titzer asked me to comment for the ARM architecture, I work for ARM on V8. The current proposal works on all modern ARM cores: they either support unaligned accesses or mechanisms to enable emulation (with the OS support).

The beginning of this thread touches on the behaviour of older ARM cores. Those cores (ARMv5 and earlier) have a peculiar behaviour which would introduce non determinism with this proposal. For example for a word load, if the address is not aligned the loaded values is rotated 8 times by the value of bits[1:0] of the address. And those cores can either be little or big endian.

All those cores have been superseded a while ago so it may be acceptable to ignore those.

Regards,
Rodolph.

**Comment by lukewagner** [comment]
Thanks for that information!  So this also suggests we don't need any changes from what's in the spec.  @titzer any other issues to consider before closing?

**Comment by titzer** [comment]
No, it sounds good. I'm OK with keeping the high road and going for that
misaligned accesses just work out, so we can close this issue.

I'll probably do some experiments when we've got some example workloads,
and will only bring this up again if it turns out to be a showstopper.
