### ISSUE TITLE
Getters / setters configurable / enumerable

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#1069]
JS.md's getters and setters currently don't specify whether they're configurable or enumerable. Presumable we inherit the default... but it sounds like there's more than one default!

cf https://github.com/WebAssembly/design/pull/1062

So what should they be?

**Comment by rossberg-chromium** [comment]
Since everything is described in terms of Ecma-262 atm, I would naturally assume that its defaults are meant to apply. However, I wasn't even aware that WebIDL picked different defaults. Why is that?

**Comment by domenic** [comment]
It's not just getters and setters; also methods have unspecified property descriptors right now.

> However, I wasn't even aware that WebIDL picked different defaults. Why is that?

I don't know :(. Probably a decision made, before Web IDL even existed, by different browser teams, which was then codified eventually.

Probably we'll want to go with Web IDL's defaults here, since we're likely to formalize the API spec as Web IDL anyway in order to ensure it's bindable to wasm code?

**Comment by lukewagner** [comment]
Just to check, is the only difference here `enumerable` (`false` for JS builtins, `true` for DOM things)?

**Comment by domenic** [comment]
Yep

**Comment by lukewagner** [comment]
We actually have a [test](https://github.com/WebAssembly/spec/blob/master/test/js-api/jsapi.js#L448) in the spec test suite that does test every property descriptor of every property.  (It tests that `enumerable` is `false`.)  I should probably go update that with the `exports` change...

**Comment by sunfishcode** [comment]
This seems to have settled, and the tests were finished in https://github.com/WebAssembly/spec/pull/484. Today, these tests now live in https://github.com/WebAssembly/spec/blob/main/test/js-api/assertions.js.
