### ISSUE TITLE
Why not create a Chinese translation?

### ISSUE THREAD

**Issue by jiftle** [WebAssembly/design#1103]
create chinese translation

**Comment by rongjiecomputer** [comment]
I don't think WebAssembly group has enough bandwidth to provide different language versions of design document in this repo.

If you do like to contribute Chinese translation yourself, my suggestion will be to fork this repo, add Chinese translation there and then ask WebAssembly group to add a link to your repo.

**Comment by Becavalier** [comment]
@jiftle You can try this one: http://webassembly.org.cn/

**Comment by fanmingfei** [comment]
I speak Chinese directly  可以加入我们，参与官网翻译呀，webassembly.org.cn 右上角 参与翻译




发自网易邮箱大师
On 08/09/2017 08:58, YHSPY wrote:

@jiftle You can try this one: http://webassembly.org.cn/

**Comment by Becavalier** [comment]
Also there are bunch of learning resources and communities that we already have in chinese and also english:

WebAssembly official website of chinese version: http://webassembly.org.cn/
WebAssembly open source community: https://www.wasmrocks.com


Hi JF,
Do you think we should aggregate all those resources (other related communities, official wasm website which was translated into other languages, etc) and list them in a single website page in webassembly.org at current time?

@jfbastien 

Jason Yu.

**Comment by jfbastien** [comment]
Yes, that sounds like a good idea. I'm not sure how the W3C usually does this type of cross-language accessibility, let me check what they recommend.

**Comment by jfbastien** [comment]
@Becavalier it looks like the W3C has some guidance around translations: https://www.w3.org/Consortium/Translation/
What do you think?

**Comment by Becavalier** [comment]
@jfbastien 
I have looked through the w3c official translation guidance, and I think it's complicated and inefficient, if one wanna join the translation, he must send email and go through all those processes first. Also, this official translation guidance is much more proper for the translation of specs and documentations. I think it's better to start translation from our official website http://webassembly.org, because it's much more acceptable to engineers rather than specs which is full of terms. 

Some thoughts note here:

1.We can create a new repo named "internationalization" (or any other word like this), and we list the links of all those internationalization version website on README.md, and what we should take responsibility for maintaining is just this piece of sheet.

2.Also, we should add a link on our website in "community" section, the words of this link is something like this:"Other languages of this website (unofficial translation)", and point this link to the repo which we created at previous step.

3.Once some open source groups complete the translation, they can contact core member to add the link of the translation website to our repo.

PS: It's necessary for us to let more and more people know webAssembly, even use it. This will also help us improve it and know what do people really need if they use webAssembly in their normal work. Also, I'll be glad to help on this : )

Any idea on this?

**Comment by jfbastien** [comment]
I think separate repos with internationalized versions of the design repo sounds good. It will need to be harmonized with the webassembly.org deployment, which @s3ththompson used to do. He's going back to grad school though, so @flagxor said he'd find someone to take ownership of the site. WDYT Brad?
