### ISSUE TITLE
Issue in implementation of atomic LoadLinked/StoreConditional for MIPS architecutre 

### ISSUE THREAD

**Issue by ibogosavljevic** [WebAssembly/design#1121]
Hi!

I am working on implementing Atomic WASM operations on MIPS platforms as part of adding WASM support to V8 javaScript engine. MIPS supports atomic operations using instructions LoadLinked/StoreConditional. The problem that I am facing is related to natural alignment requirements for those operation. MIPS has two instructions LL/SC for 32-bit numbers and LLD/SCD for 64-bit numbers. This means that there is no way to perform atomic operations on 8-bit and 16-bit numbers that are not 4byte aligned .

Please advise!

**Comment by lars-t-hansen** [comment]
Right.  We've discussed this (the case of MIPS specifically) and as far as we can see from CPU manuals and so on, it will be correct to use LL/SC on the word containing the smaller unit that you want to update atomically, because any updates from other threads to other bytes within that word (even non-atomic updates) that are performed after the LL will cause the SC to fail, and the LL/SC loop to re-iterate.  That is, suppose you're atomically updating the second byte in a word, something like this should be OK:

```
again:
v = load_linked *addr
v = v & 0xFF00 
v = v | (w << 8)  // change the byte to the value w
if (!store_conditional *addr, v) goto again
```

If you have information suggesting this is not well-defined on the architecture please let us know.

**Comment by lars-t-hansen** [comment]
That code actually did land:
https://dxr.mozilla.org/mozilla-central/source/js/src/jit/mips-shared/MacroAssembler-mips-shared.cpp#1221

**Comment by ibogosavljevic** [comment]
Thank you, this information helped me solve the issue. Please close this issue as resolved.
