### ISSUE TITLE
Assembly text format.

### ISSUE THREAD

**Issue by hsk** [WebAssembly/design#1164]
I think S expression is Lisp.
However, WebAssembly is assembly language.
Please, standard assembly language with text format.

**Comment by hsk** [comment]
example:

https://github.com/hsk/vscode-debugger-simple-asm/blob/master/dist/ocaml/parser.mly

This is very simple assembly language format.
I think assembly language should be defined with very simple BNF.

**Comment by hsk** [comment]
Although it can be understood that handling is easy if written in S formula, S expression is difficult to understand.
Are you not learning anything from XHTML?

**Comment by xtuc** [comment]
What is wrong with WebAssembly Text Format being a new syntax? You said that it's difficult to understand, do you have some examples?

To me it's good to have a dedicated syntax because WebAssembly has nothing to do with neither Lisp or the Assembly text format.

Could you tell us more about XHTML?

**Comment by hsk** [comment]
XHTML is very Simple format. But, HTML5 is not XHTML, now.
Because XHTML is not readable and usable for human.
I think S expression is not readable and usable for human too.
Since the web assembly is in a standard format, the text format must adopt the usual assembly language format.

**Comment by xtuc** [comment]
> XHTML is not readable and usable for human.

I don't agree, humans can read it and used to even write it.

> S expression is not readable and usable for human too.

I don't agree, same comment than for XHTML.

WebAssembly is **not** a standard format, it has been designed with specific goals, that's why it has a custom syntax, which is better IMHO.

> the text format must adopt the usual assembly language format

I would be opposed to that. Note that WebAssembly is an open group, they don't **have** to do certain things (like using an existing standard because you say that it has a similar syntax).

**Comment by hsk** [comment]
I see.
Thank you.

**Comment by hsk** [comment]
S expression is beautiful and usable.
Good luck.

**Comment by hsk** [comment]
https://staff.aist.go.jp/y-ichisugi/doc/newjdoc/outline.html
I like this solution.

**Comment by hsk** [comment]
but,...

**Comment by ROBERT-MCDOWELL** [comment]
xtuc:
> WebAssembly is not a standard format, it has been designed with specific goals, that's why it has a custom syntax, which is better IMHO
well, wasm will tend to be a standard itself within a couple of years isn't it?

**Comment by xtuc** [comment]
@ROBERT-MCDOWELL sorry I didn't mean to write that, of course WebAssembly is a standard format. I meant that it don't use an existing standard syntax.

**Comment by hsk** [comment]
Is LLVM format S expression?
Is X86 assembler format S expression?
Are Arm,68000,PowerPC...
I looking first time WebAssembly is beauty.
But, My motivation is down.
I think, I don't like S expression syntax assembly language.

**Comment by hsk** [comment]
There was no need to write parentheses so far.
But we needed parentheses.
I think this is not very happy.

**Comment by hsk** [comment]
fuck

**Comment by hsk** [comment]
Until now I did not dislike about WebAssembly.
But I hate WebAssembly now.

**Comment by hsk** [comment]
From the perspective of lisper, webassembly is epoch-making.
Great. I think so, I think that it is also simple and fast.

**Comment by hsk** [comment]
The quick movement of webassembly was also great.

**Comment by hsk** [comment]
But,I am not Lisper.
I can see the brackets.
I hate parentheses and I do not like that.

**Comment by hsk** [comment]
I think that WebAssembly is egoistic language of lisper.

**Comment by hsk** [comment]
Is WebAssembly an intermediate code an S formula?
The Internet has finally caught up with Lain.
Well, maybe HTML is also good for S formula.

**Comment by hsk** [comment]
I think that it is very good that I do not need to use C or C ++.
But if I write TypeScript I would like you to choose between writing in native or writing in JS ...

**Comment by hsk** [comment]
https://keens.github.io/blog/2017/12/07/webassemblynogc/

**Comment by hsk** [comment]
https://qiita.com/chikoski/items/d98ed0a98acfa896869f

**Comment by hsk** [comment]
WebAssembly is Hot now!

**Comment by hsk** [comment]
However, he is shibuya lisp boy.

**Comment by Pauan** [comment]
@hsk It's not usually intended for people to actually read or write the S-expression format directly.

Instead, you would write your code in a higher level language and it would then be compiled to WebAssembly.

And source maps means that you can even debug in the high-level language, so you never need to see the WebAssembly S-expressions.

So 99+% of the time, it doesn't matter what the text format is, because you never see it.

**Comment by hsk** [comment]
I like text format output compiler.
I writing compiler, 99+% of time, I read and write wast.

**Comment by hsk** [comment]
He tried to compare the performances corresponding to the wasm that I made in Emscripten in the past
https://qiita.com/toyoshim/items/e714cb4d00eace2f4d97

**Comment by ROBERT-MCDOWELL** [comment]
critics are always good to make a project to evolve. However we must take in consideration the years of code layers that built what is internet today and avoid to reinvent the wheel every time there is an evolution....

**Comment by jfbastien** [comment]
I understand that you're frustrated by s-expressions. I'm not a fan either, and find solace in accepting that the text format doesn't really matter to WebAssembly as a whole. Indeed, the binary format is what matters. We just had to have some text format for low-level display and basic testing, and the only one that was seriously proposed and moved forward was this one. It made *some* people happy to have s-expresions, so that's nice for them. To me it's similar to using XML: it's ugly and harder to read, but really doesn't matter.

What's great is that you can create your own WebAssembly text format. [We did for our own testing](https://trac.webkit.org/browser/webkit/trunk/JSTests/wasm/README.md) and it gives us more flexibility than combining textual s-expressions would. An LLVM IR like format wouldn't be hard to build at all.

That being said, I thoroughly enjoyed the play-by-play realization that you've recorded live here. 👍

**Comment by hsk** [comment]
Thank you, for understand my issues.
s-expression is good. developping is speedy.
I know a calling direct LLVM library is fast, and WebAssembly too.
Calling direct library is fast than AST base compiler.
But, library binding is difference between other language.
Since I am hobby programmer, I hope simple AST.
We use C++,JavaScript,Rust,OCaml,Haskell,SML,Coq,Scala,Scheme,Common lisp,etc... any languages.
I do not want you to accompany it soon, but I'd like you to consider it.
