### ISSUE TITLE
When will wasm64 standard design begin?

### ISSUE THREAD

**Issue by thatname** [WebAssembly/design#1314]
Hello there.
For some types of applications, 64-bit address space is very important. 
I have seen past proposals mentioning wasm64. what happened next?

**Comment by tlively** [comment]
Basically everyone involved in the standards process expects wasm64 to be officially proposed and specified at some point, but no one has had the time or motivation to do the work of specifying it so far, since there are so many spec proposals already in flight. There would be nothing stopping a sufficiently motivated person from bringing a proposal for wasm64 to the CG and beginning the specification process for it.

**Comment by binji** [comment]
Question answered, so closing. Please reopen if otherwise.
