### ISSUE TITLE
No way to ensure consistent performance.

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/design#1327]
I understand that each WebAssembly host is meant to run a specific application, but it is possible to develop a generic, well-documented host that could run any application designed for it, which could be useful in an educational (hobbyist/demoscene) context.

However, the host would have different performance characteristics and variable amounts of memory available (for code, globals and locals, and for providing linear memories) on different physical machines.

When using a virtual machine based around a CPU emulator, it is possible to control the clock speed and available memory very precisely, and user code then runs consistently on any physical machine that's basically good enough. Is something like this beyond scope for WebAssembly?

**Comment by binji** [comment]
One possibility would be to use an interpreter and peg the number of executed instructions to a fixed time. It's not a perfect solution, since you can call out to host functions which wouldn't have to obey these restrictions, and since some operations have the potential to be considerably more expensive than others (e.g. `memory.copy`, `memory.grow`, etc.). [wabt's interpreter](https://github.com/WebAssembly/wabt/tree/master/src/interp) has some of the building blocks already to do this.

This is also akin to what blockchain users of WebAssembly want -- AIUI they need to measure the cost of execution and suspend when a certain amount of "gas" is used. So it's likely that you could combine this with a fixed clock to get what you want too.

**Comment by carlsmith** [comment]
Thanks for taking the time, @binji. There's no urgency on my end, so if the blockchain community are already pushing for something similar, I'm happy to add my two-cents to that conversation.
