### ISSUE TITLE
Defining a genuine WAT canonical format

### ISSUE THREAD

**Issue by helins** [WebAssembly/design#1400]
*** What ***

The WAT format is intended to be a human-readable translation of the WASM binary format based around s-expressions. However, it is ambiguous in the sense that several representations are allowed for one WASM construct. We argue this ambiguity, albeit being described in the specs, harms both human-readability and building tools. This tiny proposals aims to define a clear and unequivocal format to become the canonical WAT format.

Problem example 1.  `block`
```
block
  ...
end

;; equivalent to

(block ...)
```

Problem example 2. `memarg` (optional immediates)
```
i32.store offset=4

;; equivalent to

(i32.store offset=4)
```

*** Why ****

From a psychological point of view, needing to keep in mind that several representations are equivalent adds an unnecessary mental load. From a tooling point of view, it adds complexity as the tool needs to deal in several representations at the same time. As all those representations are defined in the specs, it is too late to back up. However, it is not too late for defining a genuine canonical WAT representation that strikes for a balance between authentic human-readability, ease of parsing, and ressemblance to the binary format.

*** Ideas ***

1. Instructions should always be flatten

Folded s-expression can add clarity regarding what an instruction consumes from the stack. In an ideal world, folding everything would provide more clarity to both humans and machines. However, code cannot always be folded so that an instruction always indicates what it consumes from the stack. On the other hand, flat code is never ambiguous and is closer to the binary format.

Problem example 3. "unfoldable" instruction because of a `block`
```
(i32.const 0)
(i32.const 1)
(block)
i32.store
```

2. Symbol which belongs together are bracketed together

In "Problem example 2", we see that `offset=4` can stand on its own. However, without its related `i32.store`, it would not be legal. It does not have any meaning on its own. Following this position, they should be bracketed since they form a somewhat atomic bond syntax-wise.

```
(i32.const 0)
(i32.const 42)
(i32.store offset=4)

;; instead of

i32.const 0
i32.const 42
i32.store offset=4
``` 

3. Brackets instead of `END`

Brackets already shows delimitation. Since WAT is primarily based on s-expressions, it makes sense to use brackets exclusively. It is both easier to parse for a tool and visually-striking for a human.

4. Co-locating exports with their targets

All exports should be located in the resource they do export. This is the opposite of the binary format but we argue it is easier for humans and what matters most for a tool is to locate exports in one place.

```
(func $f (export "my-func") ...)

;; instead of

(func $f ...)
(export "my-func" (func $f))
```

*** End note and background ***

These ideas stem from:

a) The opinion that the WAT format, even writing directly in WAT, should have a bigger place in the WASM ecosystem.

b) Writing WASM/WAT tools in Clojure, a functional Lisp where the WAT format can be directly represented and manipulated "as is". As in any Lisp, lists, symbols and everything needed in WAT directly maps to core data strucures of the language. Acknowledging this fact opens a possibility for powerful tools. For instance, the current tooling provided by WABT at the command line can be replicated in an interactive environment (a Lisp REPL, such as Clojure's), allowing the user to gain deep insights about the code in a unique fashion. It would really make things easier to agree on a canonical WAT format.

**Comment by tlively** [comment]
Thanks for this write-up! A couple questions:

 1. I expect that most tools will continue to want to parse any valid text format program, so this proposal would at most inform how they print programs. If that's the case, I don't see how tool implementations would be simplified. Do you expect tools to drop support for parsing non-canonical programs eventually?

 2. WABT already has a wat-desugar tool for canonicalizing the text format into its own idea of what is canonical. For improving readability, there is also WABT's wasm-decompile, which uses a different format entirely. How would having a specified canonical format be a significant improvement over this status quo?

**Comment by helins-io** [comment]
1. No as that would be unrealistic and eschewing the specs. A specified canonical format would become the default output format and any tool, especially future ones, might decide to operate only on that canonical format in order to maintain a simpler implementation. Or not. But it should be expected that any WAT tool would support at least that canonical format.

2.`wasm-decompile`  decompiles to a C pseudo language which is purely a facilty for humans. `wasm2wat`, from what I see, just tries to flatten things as much as possible and its "canonical" format is not formally described. Maybe let me explain my current usecase, shining light on why WAT might be more important than meet the eye.

The advantage of using a Lisp to read, manipulate, and generate WAT is that there is no need for an intermediary representation unlike in C++ or Rust based tools or libraries. This is because WAT maps to the core data structures of any good Lisp (here, Clojure). This has an interesting property: parsing WAT is essentially free and any tool written in such a Lisp is always up-to-date, by definition, unless newer specs takes suddenly a completely different turn. That is why I envision that Clojure might  become important for WebAssembly: it allows for easily writing tools for analyzing WASM code, instrumenting, stubbing, minifying it, and so one. In a non-Lisp language (eg. Binaryen), such features demand expertise, maintaining a IR, and working in a compile-exec cycle. In Clojure, one simply has to understand the WAT format and can right away operate on it interactively if one can expect consistency in how data (ie. WAT code) is layed out. It is hard to operate on binary data but it is trivial to operate on s-expressions and there is no better tool for handling s-expressions than a Lisp.

I have written a WASM to WAT decompiler in Clojure (not yet open-sourced) and these are the kind of conclusions I am reaching.

This is just one example, but a real and dare I say important one, of why WAT should have a canonical format which is unambiguous. We can live without it for sure, but it will make things simpler. As more languages compiles to WASM, new ones are created,  I predict this will make more and more sense.

**Comment by sbc100** [comment]
Assuming there will continue to be non-canonical files that exist in the wild, any tool that it limited to reading only the canonical form will almost certainly require some kind of `wasm-canonicalize` pre-processor (which I imagine would be easy to write in wabt of binaryen). no?.  Given that (i.e. that we will forever need to maintain and use this pre-processor), what do we gain from blessing the official canonical form?  

Or do you envisage all the wat files in the wild slowly converging to the canonical form over time eventually making such as pre-processor unnecessary.   I find this unlikely given the wide variety of WAT styles the different folks seem to prefer.   For example, as someone who works on llvm I find the completely flat and bracket-free form the most familiar because it looks more like llvm's `.s` format.

**Comment by helins** [comment]
Well, I guess the broader question is what is the prime purpose of having a text-format that is somewhat ambiguous? If its sole purpose was strictly human-readability then what we have is a "jack of all trades but master of none", haven't we?

**Comment by dulanov** [comment]
The problem can be expanded even further - in addition to the wat format, there is also the wast script format and its extended witx variant.

@helins, it is natural for you to try to adapt wat to use it directly from clojure, but wat was not designed for writing wasm-modules and is unlikely to be used for that, except for primitive examples. It's main goal if I understood it correctly - to disassemble existing wasm-modules, or to summarize, although it looks like a lisp, it is not one on a semantic level and was chosen with the idea of simplicity.

**Comment by helins** [comment]
@dulanov Fair enough, it is just I was seeing there greater potential than initially imagined but obviously it does not attract masses so let us close this issue.
