### ISSUE TITLE
Positive/negative encoding of type (constructor)s that have arguments

### ISSUE THREAD

**Issue by titzer** [WebAssembly/design#1411]
All type constructors that are currently in Wasm are negative numbers, encoded as LEBs. There are upcoming proposals, specifically the [function references](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md) and [gc](https://github.com/WebAssembly/function-references/blob/master/proposals/gc) proposals that have complex type constructors. Specifically, they introduce types that are not just a simple number, but a type constructor code, followed by an index into the types section (either a function, struct, or array declaration).

I am working on a fast in-place wasm interpreter, and one stumbling block is the speed of decoding local type declarations. It would help to speed up this decoding step, which is on the critical path for a function's execution, to separate type constructors that have an argument from those that don't.

I propose that type constructors that have no arguments continue to use negative numbers and new type constructors that are not just a single number, e.g. have an argument, are positive. This would make this distinction a single comparison. Otherwise, it will become a nasty list of cases or a table lookup.

**Comment by rossberg** [comment]
We chose negative numbers for type constructors so that positive ones can directly represent type indices without extra prefixing. I'm afraid this is too late to change, since this overlay is already used in the encoding of [block types](https://webassembly.github.io/spec/core/binary/instructions.html#binary-blocktype). The function reference and GC proposals also use it for their [representation of heap types](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md#heap-types-1). (IIRC, the original idea even was to allow a type index as a value type directly to denote a typed reference, but some compat issue prevented that.)

**Comment by titzer** [comment]
But heaptypes are not value types, and cannot appear as local declarations. Block types are also not value types and cannot appear as local declarations, either.

**Comment by rossberg** [comment]
But the binary encoding of blocktypes basically is `valtype | typeidx`, so we cannot put any positive constructors into the value type domain without clashing.

**Comment by titzer** [comment]
Ah yes, you are right. It is indeed too late.
