### ISSUE TITLE
Other languages besides C++

### ISSUE THREAD

**Issue by xclayl** [WebAssembly/design#215]
I'd love to use something like this, but since it's targeting C++ devs, I've got no chance of introducing this in our company/dev team.  You would get a lot more adoption if you targeted languages we web developers already use: C#, Java, python, etc

Good luck with your project. I sincerely hope to use something like this in the future.

**Comment by jfbastien** [comment]
This is definitely a goal, but we've moved it past the MVP because doing it right is pretty tricky. Please take a look at [this FAQ question](https://github.com/WebAssembly/design/blob/master/FAQ.md#is-webassembly-only-for-cc-programmers) which should address your concerns.

Closing for now, feel free to reopen if the FAQ isn't addressing everything you'd like.

**Comment by abustin** [comment]
The use of LLVM as a compiler infrastructure will allow flexibility for people to independently add language support. For example, I believe there is already a LLVM front-end for Java bytecode (.class files). 

https://en.wikipedia.org/wiki/LLVM#Front_ends:_programming_language_support

**Comment by mendeza** [comment]
As an LLVM/clang first-class citizen, is Objective-C implicitly included in the oft-cited group `C/C++`?

**Comment by kripken** [comment]
If someone ports the Objective-C runtime library, it would work.
