### ISSUE TITLE
Questions about WebAssembly

### ISSUE THREAD

**Issue by qwertie** [WebAssembly/design#257]
I'd like to get a better technical understanding of some issues that I haven't figured out from reading the design documents, and I hope you don't mind lots of questions being dumped on you.

- asm.js represents a program's entire heap as a single massive array. Does WebAssembly MVP use the same model? Are all pointers relative to the beginning of the heap? If so, isn't there a substantial performance penalty for constantly adding the array's base address? And how is it feasible to run large programs in a 32-bit browser--isn't it necessary to reserve, up front, the maximum amount of virtual memory that the program is allowed to use? If not, why not? Is the giant array occasionally relocated?
- Why can't we store "real" function pointers on the heap? Aren't they required for efficient virtual calls (dynamic binding)? If (malicious) alteration is a problem, could vtables be grouped together and hardware-write-protected?
- I have the impression that the PNaCl approach is to put code in an isolated low-permission process and "let it crash if it wants". Is this an accurate characterization, and if so, is it an option for WebAssembly?
- Does WebAssembly's MVP have technical advantages over PNaCl?
- ~~Given the popularity of LLVM, why was LLVM's bitcode not selected as the starting point for WebAssembly?~~ ([FAQ](https://github.com/WebAssembly/design/blob/master/FAQ.md#why-not-just-use-llvm-bitcode-as-a-binary-format))
- Is anyone thinking of a long-term-future architecture, in which WebAssembly programs can have GC and non-GC objects (in particular, with GC objects being "first class citizens"? What does this architecture look like?
- It seems to me that D is the acid test: D allows pointers to be defined (inside GC or non-GC heap blocks) that may or may not point to GC objects, and these pointers do not necessarily point to the beginning of an object. Has anyone thought about how to make this possible in WebAssembly's future?

**Comment by kg** [comment]
I'm not an absolute expert, but I'll attempt to answer your questions.

> asm.js represents a program's entire heap as a single massive array. Does WebAssembly MVP use the same model? 

Yes[*].

> Are all pointers relative to the beginning of the heap?

Yes, though GC integration will likely introduce a second class of address which is an address into the GC heap or a handle to a rooted GC value.

> If so, isn't there a substantial performance penalty for constantly adding the array's base address?

In theory, but it's my understanding that modern JS runtimes (along with Native Client) are able to exploit the segmentation feature built into x86 and x86-64 to eliminate most (if not all) of those adds while cheaply enforcing the address space boundary.

> And how is it feasible to run large programs in a 32-bit browser--isn't it necessary to reserve, up front, the maximum amount of virtual memory that the program is allowed to use? If not, why not? Is the giant array occasionally relocated?

Heap is currently reserved to a specific size in asm.js. There is a proposal to allow resizing the heap that is based on ArrayBuffer.transfer. It implies some recompilation of code but the fixups there are relatively simple.

> Why can't we store "real" function pointers on the heap? Aren't they required for efficient virtual calls (dynamic binding)? 

The asm.js (and thus wasm) heap is user-controlled so being able to manipulate function pointers would increase the risk of vulnerabilities. I believe @lukewagner has a theory for how to reduce or eliminate the overhead that results from this.

> If (malicious) alteration is a problem, could vtables be grouped together and hardware-write-protected?

Yes.

> I have the impression that the PNaCl approach is to put code in an isolated low-permission process and "let it crash if it wants". Is this an accurate characterization, and if so, is it an option for WebAssembly?

Whether or not NaCL/PNaCL do this aside, you could do it, but it increases the attack surface because any code loaded into the process is a possible target for attack. WebAssembly executables in the browser will almost certainly have to execute in the same process and thread as the JS runtime for interop purposes.

> Does WebAssembly's MVP have technical advantages over PNaCl?

I can assure you that once it's finalized, it will, if only in terms of wire size and decoding speed. We also have an opportunity here to correct errors in NaCL/PNaCL's design. Likewise, we have an opportunity to correct errors/deficiencies in asm.js's design.

> Given the popularity of LLVM, why was LLVM's bitcode not selected as the starting point for WebAssembly? (FAQ)

The FAQ covers this as you noted, but to summarize, it was tried for PNaCL and found to be undesirable.

> Is anyone thinking of a long-term-future architecture, in which WebAssembly programs can have GC and non-GC objects (in particular, with GC objects being "first class citizens"? What does this architecture look like?

Yes. I believe there is an issue about this, if not a page on the wiki. We've had in-person discussions about what it will look like and we are confident it can be done effectively. I plan to spearhead this effort if nobody else takes on that responsibility, and I'll make sure to collect feedback from people who intend to use it.

> It seems to me that D is the acid test: D allows pointers to be defined (inside GC or non-GC heap blocks) that may or may not point to GC objects, and these pointers do not necessarily point to the beginning of an object. Has anyone thought about how to make this possible in WebAssembly's future?

Yes. The two classes of pointers will be distinct and there will be separate mechanisms to manipulate them.

**Comment by qwertie** [comment]
Regarding D, let me reiterate that you can define pointers that can point both to GC and non-GC objects, i.e. D seems incompatible with a regime in which a pointer _must_ point only to GC, or to non-GC, memory. This, I think, is the main reason D cannot be compiled to .NET/CLR.

Aside: even in a programming language that works fine under a "segregated" pointer regime, in low-level code such as specialized data structures and interpreters, it is really handy to be able to have a union of a pointer with an integer - setting the low bit to '1' to represent an integer. If the GC were to support such unions (i.e. if such pointers could point to the GC heap), then of course you could also have unions of the two types of pointers.

**Comment by kg** [comment]
A precise rooting model would allow you to store a GC handle and a heap pointer in the same location, using your tag bit.

**Comment by sunfishcode** [comment]
It sounds like the questions here were answered.
