### ISSUE TITLE
"Signed-less"

### ISSUE THREAD

**Issue by indutny** [WebAssembly/design#268]
What does "signed-less" addition and subtraction supposed to mean? Is it just "signed"?

**Comment by kg** [comment]
I think what's meant is that the operation is the same for both signed and unsigned values? 'Bitwise' or 'sign-agnostic' might be better here.

**Comment by indutny** [comment]
Hm... ok, so basically it means that:

```
int32.add(-1, -1) => -2
uint16.add(0xffff, 0xfffff) => 0xfffe
```

Is this correct?

**Comment by kripken** [comment]
It means that the bits could be interpreted as signed or unsigned, but the interpretation does not matter - given certain input bits, the output is the same. This is true of addition, due to how 2's complement works + overflow semantics (signed vs. unsigned interpretation differs only by an additive factor of `2^32` on 32-bit, which goes away due to overflow), but is not true of say division, where a sign-free `/` is not possible.

**Comment by indutny** [comment]
Oh gosh, you're right :) Still I think that the wording is a bit confusing.

**Comment by kripken** [comment]
Yeah, I agree with @kg that "sign-agnostic" might be more clear. But it is lengthier, so I don't know...

**Comment by titzer** [comment]
"sign-agnostic" is also fine by me.

**Comment by jfbastien** [comment]
Sent #272 to address this.
