### ISSUE TITLE
'Symbols' in AST

### ISSUE THREAD

**Issue by kg** [WebAssembly/design#269]
in a discussion with @jfbastien it came up that we probably want to have the concept of 'symbols' in the AST - names/identifiers that are unique within a module. This applies to things like function names, global names, names of locals, and loop labels (for ```x: while (1) { break x; }```, etc).

Symbols are globally-unique identifiers that the encoder numbers internally. A symbol could be externally visible, in which case there would be a table somewhere in the encoding that assigns a textual name to the symbol (this would be the case for exported functions, for example), but most of them would not have names once encoded. So in this case round-tripped source -> binary -> source would discard the textual version of a symbol but the symbol would maintain a unique identity.

Symbols would be semantically distinct from integers, indices, string literals, and so on. Maybe we would have sub-categories of symbols - i.e. a separate symbol space for loop labels, a separate symbol space for function names?

In this model, get-local and set-local operations would semantically accept symbols representing a local instead of just taking an integral index into the function's locals.

The overall motivation for this is to ensure that things are sensible and clear when round-tripping our textual representation and binary representation. So, complete syntax strawman to demonstrate the concept:

source text:
```text
global int32 @Foo

func float32 @Bar ( int32 @a, int32 @b ) {
  local float32 @result
  setlocal @result ( conv:float32 (
    add:int32 (getarg @a) (getarg @b)
  ))
  ret @result
}
```

-> arbitrary binary format -> disassembled text:

```text
global int32 @global0

func float32 @Bar ( int32 @arg0, int32 @arg1 ) {
  local float32 @local0
  setlocal @local0 ( conv:float32 (
    add:int32 (getarg @arg0) (getarg @arg1)
  ))
  ret @local0
}
```

This interacts well with some other ideas - for example, debugging information naturally includes tables mapping symbol #s to names.

**Comment by kg** [comment]
Erk. When I say 'globally unique identifiers' I actually mean 'scope-unique' identifiers. Local names would be scoped.

**Comment by lukewagner** [comment]
We've also been discussing defining a symbol section (as a lightweight alternative to full-blown debugger info) which would have the similar goal of assigning names to anything in wasm that was named by an index (viz., functions, locals).  The idea is that the section would be optional and strippable (just like native) and, when present, you'd see those symbols in your text format when you View Source'd; otherwise you'd just see autogenerated (and thus meaningless) identifiers.  By keeping symbols in a separate section (esp one at the end, for streaming reasons) we'd avoid wasting any time decoding symbol bytes unless we wanted to.  Is this similar to what you're thinking?

**Comment by kg** [comment]
Bingo. We'd want to make sure that non-strippable symbols (export names) are separate somehow.

**Comment by qwertie** [comment]
Good idea! This plan treats non-obfuscated, decompilable code as a first-class citizen (which is important to me), hopefully without sacrificing anything when the code is "minified" (stripped).

Sometimes a program would like to use the same string as both a variable/function name and also as a runtime string (or run-time [symbol](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol)) - another reason to have non-strippable symbols.

Would it be smart to predefine in the spec, say, the first 26 strings as letters of the alphabet? That way a minified version would have some "names" to refer to, whose symbol numbers are one byte as LEB128 (if we're using that), without a need to store a string table.

**Comment by lukewagner** [comment]
@kg Perhaps the best place is to start fleshing out Tooling.md and add a section talking about a Symbols section?

**Comment by m4b** [comment]
@qwertie 

> Good idea! This plan treats non-obfuscated, decompilable code as a first-class citizen (which is important to me), hopefully without sacrificing anything when the code is "minified" (stripped).

I'm glad someone else brought this up, and that @kg includes round trip considerations from the get-go; for some reason there's been a long, deep history of source code biased thinking in compilation strategies and representations.  Consequently, I'd argue that this results in a bountiful source of security vulnerabilities, and unfortunately, wheel reinvention, since if binary -> source had been considered a first class operation in the first place, much of the tools for debugging wouldn't need to be reinvented, recoded, etc., which are typically insufficient at the end of the day due to information loss (which again, is a result of source-biased thinking).

> We'd want to make sure that non-strippable symbols (export names) are separate somehow.

@kg the mach-o format accomplishes a non-strippable export symbol section by defining export data in a special section, with its own semantics (it uses a trie for lookups/efficient encoding), which is indexed/accessible via non-strippable meta data called a "load command".  Similarly for imports.  An optional, strippable section (it's actually the only thing that can be stripped when you run `strip <some_binary>` on OSX), contains the traditional nlist symbols, which is everything, and therefore is a superset of the import and export symbols.  The benefit of this approach is that exports, imports, and locals can be clearly delineated, with no ambiguity, which is _really_ nice for debugging and binary analysis.  The downside is that there is a lot of redundant data (in the nlist), but this obviously need not be so.

I believe microsoft's PE format does something similar w.r.t. exports, although you probably know more about this than me?

**Comment by jfbastien** [comment]
Maybe @MikeHolman knows more about this, or can pull in the right person.

**Comment by MikeHolman** [comment]
>I believe microsoft's PE format does something similar w.r.t. exports, although you probably know more about this than me?

Yes, we have a separate .edata section which basically has 3 tables, one for function addresses, one for export names (null terminated ASCII), and one which maps those together. However I believe this is only used for linking, and distinct private symbol names are used for internal references.

**Comment by jfbastien** [comment]
@lukewagner will write a PR to add strippable "debug info" sections for names / symbols.

**Comment by lukewagner** [comment]
Done in #580.
