### ISSUE TITLE
Non-storable bool type

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#281]
AstSemantics.md currently uses integers to hold comparison results. I'd much rather have a non-storable boolean type (call it `i1`) which is returned by comparisons. It's convertible to/from other integer types, but cannot be loaded or stored.

It can be used for `select`, and once we have SIMD you can construct non-storable `i1` vectors.

This is nice because it keeps the type information in the IR, making things easier to track and in the case of SIMD easier to optimize because different ISAs represent SIMD comparisons differently.

**Comment by sunfishcode** [comment]
If we add a scalar bool type, I suggest `bool` instead of `i1` or `int1' because I don't believe we'd plan to give it basic integer operations like `add`, `sub`, etc.

I like this because it's human-friendly, it enables some fun (though not game-changing) optimizations, and it eliminates a pesky asymmetry where we just use `int32` to hold booleans, however I don't feel I have any arguments which conclusively outweigh the downsides of adding another type. In particular, it's feasible to have a SIMD bool type without having a scalar bool type.

**Comment by jfbastien** [comment]
`bool` sgtm.

I would allow bitwise operations on `bool`.

Agreed the optimizations aren't game-changing, but they're useful enough and make the code generator ever-so-slightly easier that it's worth it. I do like the symmetry for SIMD bool types :-)

**Comment by titzer** [comment]
I don't see a real value-add here. It means more local types, which means
more signatures, requires explicit conversions between ints and bools, and
requires more operators on booleans. Overall, this just means more
complexity with marginal static checking possibilities. Actually, I see
bool as more of a hassle for wasm producers and consumers than anything
else. I'm not sure what optimizations this enables. E.g. TurboFan already
does plenty of optimizations, e.g. reasoning about boolean negation,
without the extra help of a boolean type.

**Comment by sunfishcode** [comment]
I agree that symmetry with SIMD is also in favor of a scalar bool type. WebAssembly has a pretty good chance of achieving symmetry between all operators which will have both scalar and SIMD forms, but a lack of a bool type would compromise this aesthetic property.

The main optimizations enabled by a scalar bool type would be around (non-inlined) call boundaries. Consider a language where throwing is not rare, so zero-cost EH is expensive. One approach to EH is to give functions a second return value, a flag indicating an exception was thrown. Having a bool type in the platform could facilitate a moderately clever implementation returning the flag in the condition code register (e.g. FLAGS on x86), which would mean that callsites could just do a conditional branch directly rather than a compare and branch (though the value of this optimization depends on details like macro-fusion in the CPU). Which is probably not game-changing, but interesting.

I don't think the cost to WebAssembly consumers would be very high. It would be trivial to expand bool expressions into int32 expressions straight out of the decoder if one wished.

**Comment by titzer** [comment]
After some discussion since the discussion of this issue, the use cases don't compelling enough to justify the introduction of another type and a series of associated operations and conversions. Optimization opportunities didn't seem to materialize. E.g. whether `bool.not` could be implemented more efficiently by an engine, or whether flipping the direction of a branch with a `bool.not` is something that engines could take advantage of. Since we have the full complement of integer comparison operators, flipping the direction of a branch is pretty easy, and in the case of floating point comparisons, a simple `== 0` or `xor` can be done by the application, as it will know whether the i32 is really a bool or a full-range i32. Some engines already do do some optimizations on `== 0` feeding into a branch, so it's definitely not a blocker to top-line performance.

Move to close.

**Comment by sunfishcode** [comment]
As someone who favored the bool type, I agree that the optimization case isn't compelling.
