### ISSUE TITLE
Text format names (indexing and sigils)

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#340]
There was some discussion [here](https://github.com/WebAssembly/design/issues/310#issuecomment-136417393) about only allowing names instead of either indices or names in the text format. I'm in favor: it makes the text format easier to understand, particularly references to labels, and isolates indexing to the binary encoding.

I'm also proposing that WAST should use sigils to distinguish different namespaces. A derivation of the LLVM convention is fine: ```@global```, ```%local```, ```#label```. Maybe ```$function```, ```^import```, and ```!function_table``` (IMO those could all go in the global namespace, but that's a separate issue).

**Comment by lukewagner** [comment]
Initially I had the same inclination, but a good counterpoint was that allowing arbitrary indices is useful for writing bad test cases since they allow you to generate the bad ASTs (and then assert that they are caught as invalid).

More generally, this is a detail of the SExpr language parsed by ml-proto which is not the wasm text format (TextFormat.md) which would be part of the spec (and likely be completely different and only provide names, as you've said).  The SExpr language is an internal testing tool, so it's really not even in the scope of the design repo.

**Comment by AndrewScheidecker** [comment]
Yes, this is meant to be about the official text format. But it's news to me that the S-expression syntax defined by the spec interpreter will not eventually be the official text format. TextFormat.md doesn't say otherwise, so I assumed that was the plan. Do you mean that there hasn't been a decision to adopt the spec interpreter syntax, or that there was an explicit decision not to?

**Comment by lukewagner** [comment]
TextFormat.md was written before there was an SExpr syntax; there was a concrete decision (#287) for SExpr *not* to be the text format.  We want an actual somewhat pleasant (though still assembly-level) text format and that means bikeshedding.  SExpr is a way to skip all that and let us focus just on the AST/semantics for now, leaving text/binary choices to after so we divide and conquer our problem space.

**Comment by titzer** [comment]
Closing for now, since there is an agreement that the s-expression format is temporary.
