### ISSUE TITLE
A way to decode past unsupported opcodes in feature tested branches

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#345]
Making an issue for this based on discussion here: https://github.com/WebAssembly/design/pull/339#issuecomment-139584753

The future features list [suggests](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#better-feature-testing-support) that there should be a way to encode operations on a feature tested path so that a runtime without that feature can skip over those operations without knowing how to decode them.

One form it could take is ```(if_feature "featurename" a b)```. In the binary encoding, the size of the serialization of ```a``` would be emitted before the serialization of ```a```, so if a runtime doesn't support "featurename", it can skip past that subexpression without knowing how to decode it. That only works with a pre-order serialization, though.

**Comment by kg** [comment]
That's an interesting approach. My binary format proposal is simpler and just has a schema that describes the size/shape of all AST nodes so unimplemented ones can be skipped.

**Comment by AndrewScheidecker** [comment]
That could work, but you also need a way to convince the validator those operations are unreachable. I didn't think of that when I made the issue...

**Comment by lukewagner** [comment]
Considering this problem and the potential solutions led to [this future feature](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#better-feature-testing-support).

I'm hesitant to require a module validator to be able to generically parse nodes.  A few reasons:
* For performance reasons, normal module decoding will contain explicit code to decode every op it understands (that's what v8-native-proto does, I think it's what the JSC wasm support is doing and it's what SM will do) and thus the generic decoding path would *only* be taken for unknown ops.  Thus, all the work to spec and implement parsing and interpreting schemas (bugs, vulnerabilities, complexity) will only exist for this one use case and we must weigh the pros/cons accordingly.
* While expression nodes have an obvious interpretation for unknown nodes (fault if you execute this), new features will often add more than just expression nodes (e.g., local types), so this conditional support would be inherently limited.

In contrast, handling feature testing (and choosing what to do when a feature is absent) can be done in full generality in user space in layer 1 decoding (which we're already "betting" on to offload other things from the spec).  I'd suggest, according to the minimality goal of the MVP and the distinct non-triviality of this feature, we keep this as a future feature.  Expanding on the current future feature text with how this could work (schemas, etc) would be welcome, though.

**Comment by jfbastien** [comment]
Are there existing systems which have accomplished this?

Agreed that this should be a future feature.

**Comment by JSStats** [comment]
There might be other compelling use cases.

1. There seems to be discussion of a decoder layer, that might be customizable, and it might also help this layer to have a format that binary operations follow. For example, if someone wanted to rewrite just some operations in the code (like the instrumenting memory loads and stores etc), then this could just copy through most operations and rewrite just those that it affects, and if there could be some format to the binary encoding then this might continue to work in the future.

2. Another use case might be compression algorithms which might be able to exploit knowledge of the binary format.

If these tools break with any change or addition to the binary format then wasm is not very robust.

While such decoder/recoder layers might be explored post-MVP, perhaps this issue deserves some more design attention now.

Have the issues of supporting 'streaming' decoding/recoding also been raised, and random access into the binary?

**Comment by jfbastien** [comment]
@JSStats yes, see #99 and a few other places.

Let's keep this discussion focused on unsupported opcodes.

**Comment by JSStats** [comment]
@jfbastien The point was that this might deserve more attention pre-MVP. The solution to being able to skip unsupported (unknown) opcodes might also be the solution to being able to copy-through unknown opcodes and to being able to walk unsupported opcodes in a compression algorithm etc. Thank you for the link to other cases. It would seem unfortunate if we get to MVP and only then realize that with some minor changes to the binary encoding that it could have met these uses.

It might not be necessary to define all the fields in each opcode and perhaps it would be enough if the size of the opcodes were well defined and the AST links within each opcode. Perhaps some of the more complex opcodes are less frequent and it would not hurt much if they included more information on their layout. For example each opcode could include the following: opcode index, number of AST links, size of remaining binary data. This would allow the AST to be walked without knowing the opcodes. This could be further optimized to encode high frequency opcode layouts more efficiently. There are s-exp encodings that might also give some inspiration.

**Comment by lukewagner** [comment]
I don't think we should overconstrain ourselves here: adding more per-node data will make decoding slower and likely make the binary bigger; for reference, in polyfill-prototype-1 (and I think v8-native-prototype), we're in the ballpark of 1 byte per op + immediates.

I do want to support use cases like generic traversal, but this is not something browsers need to do as part of wasm execution so I think it should be done as a separate section/file analogous to debug symbols.  For [backwards compatible evolution](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#backwards-compatibility), we want a module to start with a set of tables that list all the names of ops it uses (specifying the opcode for each).  The generic traversal metadata could then simply map opcode names to that op's AST node's description.  In fact, since the AST metadata is not unique to the module, no metadata section is necessary in the module itself; a tool could just fetch metadata on demand from a web service.  But we shouldn't design this in the abstract before we have real tool users that specifically need *generic* traversal.

Related, but separate from the use case of generic traversal, the MVP binary format *does* need to support backwards-compatible evolution, but I think we have a good [rough idea](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#backwards-compatibility) for that which we'll flesh out when we [get to that step in the plan](https://github.com/WebAssembly/design/issues/287#issuecomment-127441974).

**Comment by lukewagner** [comment]
This use case is now reflected in [FutureFeatures.md](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#better-feature-testing-support).
