### ISSUE TITLE
Parameterize conversion operations

### ISSUE THREAD

**Issue by kg** [WebAssembly/design#349]
Below is a verbose explanation of what things are now and why I think they should change. Scroll to the bottom for the list of proposed changes.

--

At present, in the spec repo binary, unary and memory operations are parameterized, with the opcode names being parsed into values in the AST:

```
  | (ixx as t)".load_"(sign as s)"/"(mixx as m)"/"(align as a)
    { LOAD (memop t s m a) }
```

```
  | (ixx as t)".add" { BINARY (intop t Int32Op.Add Int64Op.Add) }
```

And the AST contains generic operations with a type attached:

```
type binop = (Int32Op.binop, Int64Op.binop, Float32Op.binop, Float64Op.binop) op
```

```
  | Binary of binop * expr * expr
```

The actual implementation is a little awkward and convoluted courtesy of ocaml functors (as far as I can tell), but essentially we have abstract operations like 'eq' or 'and' that accept a type parameter that specifies the types of the left/right operands. 
Memory loads/stores similarly contain values that describe the source type, output type, and alignment of the operation.
I think this is good. 

Validation is a mixture of explicit type checks and enumeration values:
```
and check_memop {ty; mem; align} at =
  require (Lib.Int.is_power_of_two align) at "non-power-of-two alignment";
  let open Memory in
  match mem, ty with
  | (SInt8Mem | SInt16Mem | SInt32Mem), Int32Type
  | (UInt8Mem | UInt16Mem | UInt32Mem), Int32Type
  | (SInt8Mem | SInt16Mem | SInt32Mem | SInt64Mem), Int64Type
  | (UInt8Mem | UInt16Mem | UInt32Mem | UInt64Mem), Int64Type
  | Float32Mem, Float32Type
  | Float64Mem, Float64Type -> ()
  | _ -> error at "type-inconsistent memory operator"
```

Conversions, on the other hand, are a mess. Much of the 'validation' is encoded directly into the lexer in the prototype:
```
  | "i64.extend_s/i32" { CONVERT (Values.Int64 Int64Op.ExtendSInt32) }
  | "i64.extend_u/i32" { CONVERT (Values.Int64 Int64Op.ExtendUInt32) }
  | "i64.wrap/i64" { CONVERT (Values.Int32 Int32Op.WrapInt64) }
  | (ixx as t)".trunc_s/f32"
    { CONVERT (intop t Int32Op.TruncSFloat32 Int64Op.TruncSFloat32) }
  | (ixx as t)".trunc_u/f32"
    { CONVERT (intop t Int32Op.TruncUFloat32 Int64Op.TruncUFloat32) }
  | (ixx as t)".trunc_s/f64"
    { CONVERT (intop t Int32Op.TruncSFloat64 Int64Op.TruncSFloat64) }
  | (ixx as t)".trunc_u/f64"
    { CONVERT (intop t Int32Op.TruncUFloat64 Int64Op.TruncUFloat64) }
  | (fxx as t)".convert_s/i32"
    { CONVERT (floatop t Float32Op.ConvertSInt32 Float64Op.ConvertSInt32) }
  | (fxx as t)".convert_u/i32"
    { CONVERT (floatop t Float32Op.ConvertUInt32 Float64Op.ConvertUInt32) }
  | (fxx as t)".convert_s/i64"
    { CONVERT (floatop t Float32Op.ConvertSInt64 Float64Op.ConvertSInt64) }
  | (fxx as t)".convert_u/i64"
    { CONVERT (floatop t Float32Op.ConvertUInt64 Float64Op.ConvertUInt64) }
  | "f64.promote/f32" { CONVERT (Values.Float64 Float64Op.PromoteFloat32) }
  | "f32.demote/f64" { CONVERT (Values.Float32 Float32Op.DemoteFloat64) }
  | "f32.reinterpret/i32" { CONVERT (Values.Float32 Float32Op.ReinterpretInt) }
  | "f64.reinterpret/i64" { CONVERT (Values.Float64 Float64Op.ReinterpretInt) }
  | "i32.reinterpret/f32" { CONVERT (Values.Int32 Int32Op.ReinterpretFloat) }
  | "i64.reinterpret/f64" { CONVERT (Values.Int64 Int64Op.ReinterpretFloat) }
```
and operations that should be generally parameterized are not. I think conversion operations should be parameterized like binary operators, loads, and stores. This would mean that the parsing becomes generic and type correctness is enforced entirely in the checker and through enumerations like it is for those other nodes.

I'd also prefer that we do *all* enforcement in the checker and not do it implicitly through enumerations, but that is a much smaller improvement.

--

So, what's the rationale?
* Reasoning about which type combinations are valid for a specific operation is difficult, because you need to look through the lexer, the enumerations (in the ast definition), and the checker.
* Most code generators are parameterized to begin with, so you end up with tables mapping ```truncate f64 i32 val``` to ```i32.trunc_s/f64 val```. So far, multiple typos have crept into the prototype (for example, ```i64.wrap/i64``` above). Similar errors have made it into my code generator and we'll screw this up at least once in LLVM (probably multiple times).
* The duplication imposed by this approach is something every wasm codegenerator and consumer will have to pay. Any time we introduce new types (for example, SIMD vectors) every one of those tables and switches and parser rules needs to be expanded to add all the new type combinations. The checker still has to be updated despite this.

One major objection raised in the past is that runtimes like v8 or spidermonkey (and interpreters) probably don't want parameterized operands, they want a big enum of all the operations they support.
* True, but a special case. No other stage in the pipeline benefits from this, and it introduces extensive duplication.
* If we binary encode based on earlier consensus, a module's opcode table will already contain things like ```i32.add``` with unique indexes, so the binary encoding process already will convert parameterized opcodes to names and indexes.
* Each VM's opcode list is unlikely to map directly to the set of wasm opcodes - some process is converting wasm operations to v8/spidermonkey/etc internal IR, and in many cases it's not going to be a 1:1 mapping.

--

My proposed changes, in descending order of importance-to-me:
* All conversion operations (```totype.operation/fromtype```) retain their current names but are parsed generally like memory, unary, and binary operations.
  * i.e. ```(ixx as t)".trunc_s/"(fxx as t2)```. 
  * This implies that the valid type combinations are rules enforced by the checker.
* Further parsing generalization: remove the specific ```_s``` and ```_u``` variants, to match ```load```.
  * i.e. ```".trunc_"(sign as s)```

These two changes will make it significantly easier to scan the list of operations and understand the valid combinations. This will simplify code generators and reduce risk from duplication.

More things I think we should do:
* Eliminate the duplicated opcode lists for specific number sizes.
  * i.e. ```| (ixx as t)".add" { BINARY (intop t Int32Op.Add Int64Op.Add) }``` becomes ```| (ixx as t)".add" { BINARY (intop t IntOp.Add) }```
  * This implies taking the implicit type information (whether it's an ```Int32Op.Add``` or ```Int64Op.Add``` tells you the type) and making it an explicit value contained in the operation.
  * This also implies that ```Float64Op.ConvertUInt64``` would become ```FloatOp.ConvertUInt``` or even ```FloatOp.ConvertInt```, with values identifying specific types.
* Pull all the implicit arguments out of the opcode name except for the result type.
  * i.e. ```f64.store/f64/1``` becomes something like ```f64.store f64 1```.
  * We already have type arguments for other opcodes, like ```(result f32)``` and ```(param $n i64)```. This introduces more consistency.
  * Sensible parse errors and validation errors are easier to produce because you are sanity-checking argument 0 instead of trying to infer what was intended by parsing a single complex string.

Changes to ```AstSemantics.md``` itself will be less extensive, as some duplication is already expressed there.

**Comment by rossberg-chromium** [comment]
I agree that the conversion operators are cumbersome. As far as I can see,
there are two reasonable points in the design space:

1. Have one conversion opcode indexed by both types (and a separate one for
reinterpret). This is what the prototype did initially.

2. Make each conversion a separate opcode. This is what the AstSemantics
describes, and what I made the prototype to match.

I'd still prefer the former for its simplicity and ease of use, but
ultimately I think it doesn't matter all that much.

You seem to be suggesting something in the middle. I don't see how that is
better than either of the above choices, and it seems to combine the
disadvantages of both: it's both structurally complex _and_ irregular.
Worse, it would artificially add malformed programs to the AST, when the
entire goal of an AST (as opposed to concrete syntax) is to be as abstract
as possible, i.e. to make as few malformed programs representable as
possible. Any representable program must be handled by all
operations/definitions over the AST, so you want to avoid populating it
with "junk" elements.

Some additional comments inline.


On 14 September 2015 at 23:15, Katelyn Gadd <notifications@github.com>
wrote:

> Below is a verbose explanation of what things are now and why I think they
> should change. Scroll to the bottom for the list of proposed changes.
>
> At present, in the spec repo binary, unary and memory operations are
> parameterized, with the opcode names being parsed into values in the AST:
>
>   | (ixx as t)".load_"(sign as s)"/"(mixx as m)"/"(align as a)
>     { LOAD (memop t s m a) }
>
>   | (ixx as t)".add" { BINARY (intop t Int32Op.Add Int64Op.Add) }
>
> And the AST contains generic operations with a type attached:
>
> type binop = (Int32Op.binop, Int64Op.binop, Float32Op.binop, Float64Op.binop) op
>
>   | Binary of binop * expr * expr
>
> The actual implementation is a little awkward and convoluted courtesy of
> ocaml functors (as far as I can tell), but essentially we have abstract
> operations like 'eq' or 'and' that accept a type parameter that specifies
> the types of the left/right operands.
>

Functors are mostly immaterial here. The datatypes simply reflect the
classification of the opcodes. For example, the binary operator `i32.add`
is represented as

  Binary (Int32 (Int32Op.Add))

where the Int32Op module defines all int32 operators. Similarly for other
operators and types. You may wonder about the duplicate "Int32" there, but
really, the outer Int32 constructor represents the object language
namespacing and typing, while the Int32Op module is there for the purpose
of implementation-level namespacing. Different levels altogether.

The functors are only used to share the implementation of both int and both
float operators, because they happen to be analogous, but that wouldn't be
necessary.

Memory loads/stores similarly contain values that describe the source type,
> output type, and alignment of the operation.
> I think this is good.
>
> Validation is a mixture of explicit type checks and enumeration values:
>
> and check_memop {ty; mem; align} at =
>   require (Lib.Int.is_power_of_two align) at "non-power-of-two alignment";
>   let open Memory in
>   match mem, ty with
>   | (SInt8Mem | SInt16Mem | SInt32Mem), Int32Type
>   | (UInt8Mem | UInt16Mem | UInt32Mem), Int32Type
>   | (SInt8Mem | SInt16Mem | SInt32Mem | SInt64Mem), Int64Type
>   | (UInt8Mem | UInt16Mem | UInt32Mem | UInt64Mem), Int64Type
>   | Float32Mem, Float32Type
>   | Float64Mem, Float64Type -> ()
>   | _ -> error at "type-inconsistent memory operator"
>
>
Note that this complexity has gone away with the simplification I proposed
and that Luke implemented. It is much closer to the way we deal with
conversions now.

Conversions, on the other hand, are a mess. Much of the 'validation' is
> encoded directly into the lexer in the prototype:
>
>   | "i64.extend_s/i32" { CONVERT (Values.Int64 Int64Op.ExtendSInt32) }
>   | "i64.extend_u/i32" { CONVERT (Values.Int64 Int64Op.ExtendUInt32) }
>   | "i64.wrap/i64" { CONVERT (Values.Int32 Int32Op.WrapInt64) }
>   | (ixx as t)".trunc_s/f32"
>     { CONVERT (intop t Int32Op.TruncSFloat32 Int64Op.TruncSFloat32) }
>   | (ixx as t)".trunc_u/f32"
>     { CONVERT (intop t Int32Op.TruncUFloat32 Int64Op.TruncUFloat32) }
>   | (ixx as t)".trunc_s/f64"
>     { CONVERT (intop t Int32Op.TruncSFloat64 Int64Op.TruncSFloat64) }
>   | (ixx as t)".trunc_u/f64"
>     { CONVERT (intop t Int32Op.TruncUFloat64 Int64Op.TruncUFloat64) }
>   | (fxx as t)".convert_s/i32"
>     { CONVERT (floatop t Float32Op.ConvertSInt32 Float64Op.ConvertSInt32) }
>   | (fxx as t)".convert_u/i32"
>     { CONVERT (floatop t Float32Op.ConvertUInt32 Float64Op.ConvertUInt32) }
>   | (fxx as t)".convert_s/i64"
>     { CONVERT (floatop t Float32Op.ConvertSInt64 Float64Op.ConvertSInt64) }
>   | (fxx as t)".convert_u/i64"
>     { CONVERT (floatop t Float32Op.ConvertUInt64 Float64Op.ConvertUInt64) }
>   | "f64.promote/f32" { CONVERT (Values.Float64 Float64Op.PromoteFloat32) }
>   | "f32.demote/f64" { CONVERT (Values.Float32 Float32Op.DemoteFloat64) }
>   | "f32.reinterpret/i32" { CONVERT (Values.Float32 Float32Op.ReinterpretInt) }
>   | "f64.reinterpret/i64" { CONVERT (Values.Float64 Float64Op.ReinterpretInt) }
>   | "i32.reinterpret/f32" { CONVERT (Values.Int32 Int32Op.ReinterpretFloat) }
>   | "i64.reinterpret/f64" { CONVERT (Values.Int64 Int64Op.ReinterpretFloat) }
>
> and operations that should be generally parameterized are not. I think
> conversion operations should be parameterized like binary operators, loads,
> and stores. This would mean that the parsing becomes generic and type
> correctness is enforced entirely in the checker and through enumerations
> like it is for those other nodes.
>

As an aside, "parameterisation" is the wrong term here. In mathematic
terms, the types of operators are _indices_, not parameters. The difference
being that they select a definition, there isn't one definition that is
generic in them.

That also explains why you don't want to represent other combinations in
the AST: only certain indices are defined for certain operators. The AST
should only allow to represent defined operations.

I'd also prefer that we do *all* enforcement in the checker and not do it
> implicitly through enumerations, but that is a much smaller improvement.
>
> So, what's the rationale?
>
>    - Reasoning about which type combinations are valid for a specific
>    operation is difficult, because you need to look through the lexer, the
>    enumerations (in the ast definition), and the checker.
>
>
Ideally, you should only need to look at the AST. I think we are fairly
close to that. I'm not quite happy about the sign bit on loads, which I
think is the main remaining violator of this principle.


>    - Most code generators are parameterized to begin with, so you end up
>    with tables mapping truncate f64 i32 val to i32.trunc_s/f64 val. So
>    far, multiple typos have crept into the prototype (for example,
>    i64.wrap/i64 above). Similar errors have made it into my code
>    generator and we'll screw this up at least once in LLVM (probably multiple
>    times).
>
>
Don't know about "multiple typos", and whether that's a big deal, but I
agree with this points. As mentioned before, I think the irregular naming
of conversions causes more harm than good.


>    - The duplication imposed by this approach is something every wasm
>    codegenerator and consumer will have to pay. Any time we introduce new
>    types (for example, SIMD vectors) every one of those tables and switches
>    and parser rules needs to be expanded to add all the new type combinations.
>    The checker still has to be updated despite this.
>
>
Not sure I completely follow.


>
>
> One major objection raised in the past is that runtimes like v8 or
> spidermonkey (and interpreters) probably don't want parameterized operands,
> they want a big enum of all the operations they support.
>
>    - True, but a special case. No other stage in the pipeline benefits
>    from this, and it introduces extensive duplication.
>    - If we binary encode based on earlier consensus, a module's opcode
>    table will already contain things like i32.add with unique indexes, so
>    the binary encoding process already will convert parameterized opcodes to
>    names and indexes.
>    - Each VM's opcode list is unlikely to map directly to the set of wasm
>    opcodes - some process is converting wasm operations to v8/spidermonkey/etc
>    internal IR, and in many cases it's not going to be a 1:1 mapping.
>
> My proposed changes, in descending order of importance-to-me:
>
>    - All conversion operations (totype.operation/fromtype) retain their
>    current names but are parsed generally like memory, unary, and binary
>    operations.
>       - i.e. (ixx as t)".trunc_s/"(fxx as t2).
>       - This implies that the valid type combinations are rules enforced
>       by the checker.
>    - Further parsing generalization: remove the specific _s and _u
>    variants, to match load.
>       - i.e. ".trunc_"(sign as s)
>
> These two changes will make it significantly easier to scan the list of
> operations and understand the valid combinations. This will simplify code
> generators and reduce risk from duplication.
>
> More things I think we should do:
>
>    - Eliminate the duplicated opcode lists for specific number sizes.
>       - i.e. | (ixx as t)".add" { BINARY (intop t Int32Op.Add
>       Int64Op.Add) } becomes | (ixx as t)".add" { BINARY (intop t
>       IntOp.Add) }
>
>
Are you proposing to change the AST or only tweak the parser? Note that
assumes that both integer types will always support the exact same set of
opcodes.


>
>    -
>       - This implies taking the implicit type information (whether it's
>       an Int32Op.Add or Int64Op.Add tells you the type) and making it an
>       explicit value contained in the operation.
>
>
Maybe I misunderstand the suggestion, but I don't think that type-checks.


>
>    -
>       - This also implies that Float64Op.ConvertUInt64 would become
>       FloatOp.ConvertUInt or even FloatOp.ConvertInt, with values
>       identifying specific types.
>    - Pull all the implicit arguments out of the opcode name except for
>    the result type.
>       - i.e. f64.store/f64/1 becomes something like f64.store f64 1.
>
>
I wouldn't necessarily mind that, if it's what we decide for AstSemantics.
The obvious objection is that it makes the distinction between operators
and operands far more fuzzy and the opcode structure more complex. Not sure
it is an improvement in that manner.


>    -
>       - We already have type arguments for other opcodes, like (result
>       f32) and (param $n i64). This introduces more consistency.
>
>
These are not opcodes but declarations.


>    -
>       - Sensible parse errors and validation errors are easier to produce
>       because you are sanity-checking argument 0 instead of trying to infer what
>       was intended by parsing a single complex string.
>
>
That is an implementation concern that should be separated from
considerations about the language specification. Messing with the latter is
the wrong approach to improve the former. Fortunately, it would be pretty
easy to extend the prototype's parser/lexer to give the error messages you
want without changing the language.

**Comment by rossberg-chromium** [comment]
On 16 September 2015 at 10:38, Andreas Rossberg <rossberg@google.com> wrote:

> So, what's the rationale?
>>
>>    - Reasoning about which type combinations are valid for a specific
>>    operation is difficult, because you need to look through the lexer, the
>>    enumerations (in the ast definition), and the checker.
>>
>>
> Ideally, you should only need to look at the AST. I think we are fairly
> close to that. I'm not quite happy about the sign bit on loads, which I
> think is the main remaining violator of this principle.
>

Let me clarify that: you should only need to look at the definition of the
(operator) AST to find out what's a valid operator. The checker is
responsible for defining how multiple operators can be plugged together.

**Comment by lukewagner** [comment]
@rossberg-chromium That makes sense.  That suggests going back to having `Load` share a `memop` with `Store` (no extension field and `mem : mem_type` is changed back to `ty : value_type`) and a new `LoadExtend` which takes an `align` and some new variant (replacing `Memory.extension`) composed of only `SInt8 | UInt8 | SInt16 | UInt16`.  `mem_type` could be removed too.  Is that what you were thinking?

**Comment by rossberg-chromium** [comment]
I haven't actually been thinking of anything particular yet, just made the
observation :). But separating a LoadExtend sounds like a possible
solution. I would probably still keep signedness as a separate attribute to
that opcode, instead of folding it back to the new type.

**Comment by lukewagner** [comment]
@rossberg-chromium Since `LoadExtend` would only make sense for `i8`/`i16` memory types (with the recent changes), it seems like we'd want a new type for the type parameter anyway, so it seems like we'd want either two two-element types or one four-elemement type.

**Comment by lukewagner** [comment]
These questions got resolved in subsequent PRs.
