### ISSUE TITLE
Left/right shift shift amount

### ISSUE THREAD

**Issue by kg** [WebAssembly/design#350]
Right now the int64 left/right shift operations take int64 for both operands in the ml prototype, and that seems to be what's implied in the spec.

Is that actually what we want? I think the rhs should be int32, at most. On x86 I believe the shift amount is stored in 8 bits of the count register, so we're definitely not getting anything out of the right-hand operand being 64-bit.

It would make sense (I think?) for the right hand operand of shift operations to always be int32. Ideally it would be an int8, but we don't have that type :-)

**Comment by sunfishcode** [comment]
Ideally ideally, it would be int5 for 32-bit and int6 for 64-bit, but we don't have those types either :-) so no matter what we do here, we'll have more bits than we really need; it's just a matter of degree.

Making the types of lhs and rhs be the same makes them consistent with the other binary operators, and anticipates a symmetry with the SIMD operators which do specifically want the operand types to match.

**Comment by JSStats** [comment]
I notice that the shift operations are specified to return 0 if the shift is at least the bit width, and might this cause performance problems on x86/x64 when the shift is not a constant? It seems to work fine for the x86 SIMD operations, but not for operations on the general registers? Would this lead to code being written to mask the high bits of the shift anyway for balanced performance, and if so then might this warrant separate opcodes?

**Comment by sunfishcode** [comment]
x86 SIMD does one thing, x86 scalar does another, ARM scalar does another, and ARM SIMD does yet another. Our choices are: pick something, or give the operators nondeterministic semantics. We have chosen to just pick something in the case of shift operators, under the theory that this is the best choice for WebAssembly, balancing the needs of the long term against the (relatively modest in this case) performance concerns in the short term. Also, masking isn't going to deliver "balanced performance"; it's going to deliver performance biased towards masking architectures, and we don't want to encourage developers to overtune for specific architectures, in general.

Opcodes that I do see being potentially useful to add here would be rotate operators, since that's one of the most prominent uses for dynamic-shiftcount shifts, and the alternative references the operand multiple times, breaking single-use expression trees.

**Comment by taisel** [comment]
Could we not allow both kinds of shifts? One that's "safe" and one that's non-deterministic, but explicitly selected with an alternative operator or library call in a future IDE? Kind of like having different integer  operators in Apple swift for checked versus unchecked int overflows.

**Comment by sunfishcode** [comment]
Every bit of nondeterminism in WebAssembly increases the likely percentage of programs in its ecosystem that will run on some implementations and not others. This is a greater concern in WebAssembly than in languages like Swift due to the nature of how WebAssembly will be deployed to end users, and the anticipated diversity of implementations.

That said, WebAssembly does have some nondeterminism, when it's of enough advantage. Since the majority of shift operations in practice have immediate shift counts (which have no overhead), and since the overhead of providing deterministic semantics in the dynamic-count case is fairly low, this issue isn't expected to be a major concern for most programs. Especially in the MVP timeframe, there is value in keeping the overall system simple. However, we do expect WebAssembly to evolve beyond its initial feature set, and if this shift issue is a significant concern in practice, it'd be quite plausible to add new language features to address it.

**Comment by titzer** [comment]
I think shifts are specified (i.e. with a shift count >= width returning
zero or the sign, in the case of signed right shift) is the best semantics.
It requires one branch on x86 but not on arm, IIRC. If developers/compilers
want the masked behavior to save this branch on x86, then they can just
insert an explicit mask and (at least on TF) the mask and the shift will be
matched together during instruction selection and generate a single x86
instruction.

**Comment by sunfishcode** [comment]
Yes; some compilers do this, and others don't. However, ideally, developers shouldn't often feel motivated to tune application code for specific hardware architectures at such a low level. If this becomes a concern, we should consider ways to address it in WebAssembly directly.

**Comment by taisel** [comment]
Yeah, my train of thought at least was to allow the non-deterministic path an explicitly marked way, that isn't accessed as easily. I was thinking of making developers at least use some call with the word unsafe in the keyword for accessing such a thing. Promote only the deterministic operation, and keep the non-deterministic one hidden, but usable. I totally get why web assembly would lack the non-deterministic one... A lot of programmers tend to do weird naughty things.

**Comment by lukewagner** [comment]
Agreed that it's best to be fully deterministic here.  I would expect Intel to eventually add the right op (if they haven't already; does `SHRLX` in [BMI2](https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets#BMI2_.28Bit_Manipulation_Instruction_Set_2.29) do the right thing?).

**Comment by sunfishcode** [comment]
No, `SHRL` and `SHRX` are the same as x86's other shifts; the only difference is that they don't set FLAGS.

**Comment by mbodart** [comment]
It seems there are two issues under discussion:  the bit size of the shift count; and the semantics for large shift count values.

As for the bit size, 32 seems preferable.  It effectively matches the definition in C/C++, assuming sizeof(int) is 4 bytes, and thus any issues related to the incongruity with the 64-bit operand size should be comparable to what C/C++ applications have always faced.

Presuming shift counts primarily exist as at most 32-bit computations (an educated guess, but likely true for C/C++), a 64-bit count would require an extend operation prior to use.  This is mainly a code size issue, as the extend would most likely be removed by the webasm consumer when unnecessary.

But more significantly, any range check necessary to emulate the 0/sign bit result for large shift counts would likely be expensive on 32-bit architectures.  (Of course if the shift count is known to be in the range of a 32-bit value, such as if it was produced by an extend operation, this devolves into the emulation cost for a 32-bit shift.)

Admittedly the lack of symmetry with SIMD operators could be an issue.  I'm not so concerned with simd shifts by a single shift count, as they can have the same 32-bit count and corresponding issues as scalar shifts.  But shifts by a vector of shift counts might prefer size uniformity.

As to the semantics of large shift counts, the existing definition can be made to have reasonable performance in some circumstances.  For example if the webasm is generated from a language like C/C++ which is free to toss out the high bits, the shift can be preceded with an "and count, $0x1f" operation.  On targets which truncate the shift count, the webasm consumer could recognize the "and" is unnecessary and remove it.  On other targets, the only additional cost is the "and".

If we wanted to support two flavors of shifts (and I'm not necessarily advocating for or against this), I just want to point out that we can do so without any undefined behavior.  One flavor would be defined to truncate the shift count to exactly the number of relevant bits per C/C++ (31 for a 4-byte int, for example), and the other flavor would be defined with the current 0/sign-bit semantics.  The webasm producer would choose the best flavor based on their semantic needs.

**Comment by sunfishcode** [comment]
Yes, multiple sets of differently deterministic shift operators is another alternative. I think this is an area though where it's best to start out by picking one set, to keep things simple to start with, since the performance differences between the various options here are usually not that great in practice.

**Comment by sunfishcode** [comment]
After discussion, x86, x64, and arm64 all have masking shifts (in scalar), and several source languages such as JS and Java require masking shifts, so it makes sense to change wasm's shifts to require masking semantics (similar to how we have to define integer division in a semantically undesirable way because of existing hardware and language semantics; see #250).

**Comment by sunfishcode** [comment]
This is now implemented in #456.
