### ISSUE TITLE
Memory addressing with negative immediate?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#353]
Can memory [addressing](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#addressing) be negative? Or equivalently: subtractive instead of additive?

Is seems specified as strictly unsigned addition.

I have a hunch that it may be useful to support both, but I think we should base our decision our actual data (read: I don't want an answer now).

**Comment by kg** [comment]
I'm confused, we have base+offset addressing? It's not in the ml prototype or any of the tests, as far as I can tell. (I do want it, though!)

I think negative addressing is potentially useful, but I can't think of a precedent for doing it. IIRC it's not valid in C, C++, or C#.

**Comment by lukewagner** [comment]
It's not in ml-proto yet, but it is described in the first sentence of the Addressing section JF linked to.

I agree we need to be very careful to make sure that negative immediate offsets don't mess up any of the bounds-check optimizations we want to do.  For example, the point of including a constant offset with special overflow rules is so that if you have a sequence of loads from different constant offsets where you simply bounds check the base pointer once and fault if out of bounds without worrying about whether any of the constant offset additions might have wrapped back in bounds.  With negative offsets, we'll partially lose this property: if the base is out of bounds, a negative offset might take the effective address back in bounds.

**Comment by taisel** [comment]
If that was true, couldn't unsigned and signed offset be split into two different opcodes?

**Comment by lukewagner** [comment]
The goal of `offset` is to allow some extra degree of optimization by providing infinite precision semantics.  This helps whether using bounds checking or page protection.  With a negative offset and the bounds checking scheme, a negative offset requires *extra* checking to catch the underflow (bounds checking against `memory_size` plus offset isn't sufficient), making it *slower* than just a manual `i32.sub`.  So I'd move to keep offset unsigned.

**Comment by titzer** [comment]
I'll give this a - -1.
I mean, +1 :-)

**Comment by lukewagner** [comment]
Closing pending compelling motivation.

**Comment by jfbastien** [comment]
Could you create a PR that clarifies the design with this decision?

**Comment by lukewagner** [comment]
Oops, I thought AstSemantics.md already specified an unsigned offset, but indeed only the *effective address* is specified to be unsigned.  Good catch.

**Comment by jfbastien** [comment]
Yeah sorry, I think my original issue wording was misleading :-)

**Comment by JSStats** [comment]
The base address is also interpreted as unsigned, and this should be noted too if not already.
