### ISSUE TITLE
Should inlining be syntactic substitution?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#381]
In a few places, it's been asserted that inlining can be syntactic substitution. However, this is not presently true:
 - wasm local variables are all function-scoped, so inlining a callee into a caller would require appending the callee's local variables onto the caller's and remapping the references to those variables
 - return statements in the callee would have to be written to be break statements
 - function bodies are currently wrapped in an implicit block (in the spec repo, at least) which would need to be made explicit for inlining.
 - others?

Of these, the first is the most significant, but all of these are fixable without too much trouble. Is syntactic substitution a property worth pursuing?

**Comment by JSStats** [comment]
+1 to adding AST/block scoped variables. Even non-trivial macros are problematic without them.

**Comment by jfbastien** [comment]
Are you suggesting this be tackled strictly at the textual wasm level, or at the binary level? Those are fairly different. FWIW I think both can be done (e.g. `break 10` from a block nested 10 deep into a function == `return`).

**Comment by sunfishcode** [comment]
At the AST level primarily, which will affect both text and binary. It looks like the implicit block of a function body is considered syntax sugar in the spec repo, so that may not be an issue. But, the return and local variable issues are present at the AST level.

**Comment by JSStats** [comment]
@jfbastien A break with a nesting level does not work well for macros which might increase the nesting level. The return might be considered a break to the function name.

**Comment by titzer** [comment]
I would advocate against adding scoping of variables to the AST. It breaks
some one-pass invariants, like knowing all the local variables and their
types at the beginning of a function.

**Comment by JSStats** [comment]
@titzer Could you give an example? It does not break an interpreter. The variables are always defined when reached. Does any one-pass compiler really demand knowing all the variables at the start of the function, for example to allocate a static frame on entry? Inlining will surely be just as much of a challenge - the inlinees variables will not be known in one pass on entry to the inliner function.

**Comment by titzer** [comment]
It complicates every decoding algorithm, because now the data structures
needed to track state for locals are all dynamically sized. E.g. now the
SSA environments are dynamically sized.

On Wed, Sep 30, 2015 at 10:25 AM, JSStats <notifications@github.com> wrote:

> @titzer <https://github.com/titzer> Could you give an example? It does
> not break an interpreter.
>
Any interpreter that allocates the frame for a function up-front won't work.

**Comment by JSStats** [comment]
@titzer Dynamically sized data structure are not a challenge that should constrain work here - they are just basic programming tools.

An interpreter can use a stack, push on entry and pop on exit of the context - it does not have to allocate a static frame up-front. This issue raises a similar challenge. Are you suggesting that this issue not be consider because an interpreter can not allocate a static frame for the callee up front?

What happened to the 'one-pass' blocker? Show me a one-pass SSA compiler - doesn't exits because the life of the variables is not know without making a full pass. If block-local variables were available then some simple compilers could do well without SSA because they would already know a lot about the scope of variables and the producer could do some of the work here.

**Comment by titzer** [comment]
On Wed, Sep 30, 2015 at 11:30 AM, JSStats <notifications@github.com> wrote:

> @titzer <https://github.com/titzer> Dynamically sized data structure are
> not a challenge that should constrain work here - they are just basic
> programming tools.
>
It makes an actual difference to how much state decoders need to carry
around and how that state is implemented. With dynamically sized data
structures, the storage for state for local variables no longer follows a
stack discipline, so, yes, it uses more memory.

> An interpreter can use a stack, push on entry and pop on exit of the
> context - it does not have to allocate a static frame up-front. This issue
> raises a similar challenge. Are you suggesting that this issue not be
> consider because an interpreter can not allocate a static frame for the
> callee up front?
>
I don't think WebAssembly is the right level to have variable scoping.
Having scoped variables in WebAssembly just moves work that could be done
at production time to consumption time with distinct disadvantages for
consumers, dictating implementation choices like an interpreter that can't
allocate a whole frame up front.

It would be possible to allocate scoped variables at the beginning of the
function in the sexpr->binary wasm translator. The tradeoff there is that
sexprs drift farther from the eventual binary format we will standardize.

> What happened to the 'one-pass' blocker? Show me a one-pass SSA compiler -
> doesn't exits because the life of the variables is not know without making
> a full pass. If block-local variables were available then some simple
> compilers could do well without SSA because they would already know a lot
> about the scope of variables and
>
the producer could do some of the work here.
>
We've seen from asm.js that in big functions, graph construction time and
memory is considerable and want to make sure decoders are super-efficient.
v8-native constructs a fully correct SSA-renamed sea-of-nodes graph from
WebAssembly in a single pass. The same properties that graph construction
benefits from (all locals are known up front and control is structured)
benefit interpreters, baseline JITs, verifiers, etc. I think we want to
avoid reasoning that compilers that have N passes deserve N+1, and also
that N > K.

**Comment by JSStats** [comment]
@titzer That is interesting but not a proof that SSA renaming can not be done in a single pass with block scope variables, or that it will be slower. I don't see any reasons it would require an extra pass, but can not demonstrate it now. It might require some reworking of your current algorithm, but I don't think such issues should constrain the design given that algorithms can be reworked.

The choice to start the life of all variables at the start of the function and end them at the end *requires* an SSA pass in order to reason about variable types. This choice demands an extra pass. It pushes work from the producer to the consumer - the need for SSA to untangle the life of variables from overlapping references. If the producer declares a limited scope for a variable then it has already done some of the work that an SSA passes does. If the variable has only one definition and multiple uses then it's already in SSA form. Perhaps an alternative SSA algorithm could exploit this for even better performance. Perhaps you could give it some more thought.

**Comment by rossberg-chromium** [comment]
On 30 September 2015 at 01:07, Dan Gohman <notifications@github.com> wrote:

> In a few places, it's been asserted that inlining can be syntactic
> substitution. However, this is not presently true:
>
>    - wasm local variables are all function-scoped, so inlining a callee
>    into a caller would require appending the callee's local variables onto the
>    caller's and remapping the references to those variables
>    - return statements in the callee would have to be written to be break
>    statements
>    - function bodies are currently wrapped in an implicit block (in the
>    spec repo, at least) which would need to be made explicit for inlining.
>    - others?
>
> Of these, the first is the most significant, but all of these are fixable
> without too much trouble. Is syntactic substitution a property worth
> pursuing?
>

FWIW, function blocks are syntactic sugar in the spec, so not an issue on
that level. Return statements could actually be desugared into a break to
that block (which would probably make sense for spec economics, regardless
of this issue).

So variables are the only "real" hurdle. Personally I'd like the
compositionality, but then again, I don't think it's a big deal to compose
variable environments on the side when substituting.

**Comment by jfbastien** [comment]
I agree with @titzer on wanting to keep single-pass.

I think things like `break <function-level-nesting>` instead of `return` could be interesting to explore, it seems to be easy to track. That would mean that `break` can return a value.

**Comment by binji** [comment]
break in the spec repo already can return a value.

**Comment by sunfishcode** [comment]
So the present status here is that variables are going to remain function-scoped.

**Comment by jfbastien** [comment]
Do we want to change to `break` instead of `return` as you suggested? (in a separate issue)

**Comment by sunfishcode** [comment]
I don't presently have an opinion on that. My main purpose for this issue was to determine whether was a desire to make the language fully compositional. It appears there is not. Inlining is still fairly simple though, since variable rewriting, renaming return to break, and inserting a block around the body, are fairly simple.

**Comment by JSStats** [comment]
The decision might be significant for the web as is effectively means that functions can't be streamed through transform stages, not even modest macro expansion that needs to add a variable. It means there will surely be a library that transforms the wasm into another easier form to work with and back again for each function, and another intermediate form to deal with is not a great outcome.

Not sure how significant this is. Transforms will probably be done on the client side so it's probably just a memory usage issue for large functions, and perhaps an issue for parallel parsing as it delays the start of parsing by the wasm parser.

The rationale appears to be that G are already invested in a parser which does not look like good to reason to me. I hope people can give this some more thought, but if it stands then you might want to document the rationale (and don't forget to note that it's because G's invested in a parser). I think G's parser is a throw-away as it does not handle general CFG's and competition will surely demand support for this going forward. But it does not appear to be a show stopper, and history can judge :)

**Comment by titzer** [comment]
On Fri, Oct 9, 2015 at 3:36 PM, JSStats <notifications@github.com> wrote:

> The decision might be significant for the web as is effectively means that
> functions can't be streamed through transform stages, not even modest macro
> expansion that needs to add a variable. It means there will surely be a
> library that transforms the wasm into another easier form to work with and
> back again for each function, and another intermediate form to deal with is
> not a great outcome.
>
> Not sure how significant this is. Transforms will probably be done on the
> client side so it's probably just a memory usage issue for large functions,
> and perhaps an issue for parallel parsing as it delays the start of parsing
> by the wasm parser.
>
> The rationale appears to be that G are already invested in a parser which
> does not look like good to reason to me. I hope people can give this some
> more thought, but if it stands then you might want to document the
> rationale (and don't forget to note that it's because G's invested in a
> parser). I think G's parser is a throw-away as it does not handle general
> CFG's and competition will surely demand support for this going forward.
> But it does not appear to be a show stopper, and history can judge :)
>
That's not the real reason. I'd be happy to change the v8 parser for real
benefits, but I don't see a lot in this instance. As I mentioned, lifting
all variables to the top of the function is easy static work, so we might
as well keep it static work for the producer. Besides, once a language has
scoping, then a series of questions follow, like whether to allow/require
readonly and/or read-write bindings, whether bindings are left to right,
have initializers, have default values, have type inference, etc. In other
words, a bunch of small opportunities for gotchas, tricky bits, and
incompatibilities between engines.

**Comment by JSStats** [comment]
It can see that it helps simplify an interpreter and probably improves interpreter performance to have the local variables packed at the top. With a transform stage in the pipeline, this will be doing this packing, so it's not really static work. Would an interpreter also run the transforming code, which would add a lot of work, or will it be necessary to spec the macro layer and how it deals with introducing more local variables.

I also see a suggestion the backend can use the producers choices to bias it's packing choices. The backend is not constrained to pack by type though, so might do a better job ignoring the producers choices.

For a starting point for discussion. Local bindings would be the same as the current function local variables, that is they would all need an initializer (zero), would all be read-write, and all have a type. How would this work?

This will need to be considered anyway if wasm is to support macros, although it might be possible to keep this out of the spec. by making the transform stage wasm code too so the community would experiment with alternative intermediate language extensions separately to the core wasm spec.

I don't think it's a show stopper, but think there are issues to consider here. At least: what does this mean for a macro layer?

**Comment by lukewagner** [comment]
I've been considering this feature in the context of the (user-space) macro layer and so far I don't see any use cases: the input format is under the macro layer's arbitrary control so it should be possible to put the right info in the right place so it is available at the right time during streaming translation.  For example, if the macro layer wants a concept of scoped bindings (I can definitely see this being useful for macros), it can easily precompute how many locals are needed AOT and put this number at the beginning of the function so that it can be written in the generated wasm before seeing the body.  Then, to translate a scoped binding access, the macro algorithm would just maintain a scope depth counter which indicated the next free local to use knowing there are enough locals.

**Comment by jfbastien** [comment]
When we discuss "macro", are we talking about lower-than-s-expr macros for compression purpose, or are we talking about hygienic macros that make it nice to hand-write `.wast` text files?

**Comment by JSStats** [comment]
@lukewagner In general it would not be possible to anticipate all the macro used (and their depth if used recursively) without seeing the whole function. Worst case seems to be that the user-space macro layer would need to work function-by-function, and maybe people don't thinks this is a big problem, or could be addressed in future if it becomes an issue.

@jfbastien Good point, if they are only used for compression then I guess the function variables are known in advance and the challenge might be for the compression encoding to map everything to the right function variable which seems trivial - and to map scope depth references if wasm uses them. But I also had substitutions in mind that were not anticipated upstream, such a injecting instrumentation for debugging. Might people want to distribute wasm style code with 'hygienic macros' intact, that are expanded at the client - worst case seems to be that it needs to be done function-by-function.

Still it might be prudent to plan to allow scoped variables by keeping the rest of the design consistent with this (independent of nesting depth), and it might even help compression if it does not need to rewrite sub-trees that reference a target scope by depth.

**Comment by JSStats** [comment]
On the scope targets: then again it could be more efficient to encode scope targets by depth rather than giving each a unique number - numbers can be reused in separated AST branches so repeat.

**Comment by lukewagner** [comment]
@jfbastien I was referring to "macro" as described in layer 1's [Specific compression](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md).
