### ISSUE TITLE
Writing audio driver callbacks in WebAssembly?

### ISSUE THREAD

**Issue by kaoskorobase** [WebAssembly/design#382]
I'd like to discuss the following use case (hoping this is the right place): We have a sound synthesis engine that is written in C++ using PNaCl/Pepper and that is controlled from Javascript inside a web application. One of the strong points of PNaCl/Pepper in comparison to other technologies from our perspective is that the audio generation callback, written in C, is called (in)directly by the underlying platform audio driver, without going through Javascript and any GC related overheads and latencies.

Is this use case going to be addressed by WebAssembly? Or will we have to generate audio buffers in C and pass them on to Javascript and the WebAudio API for example?

I think that for professional, low-latency audio applications the possibility of interfacing directly with the platform audio driver will be an important requirement.

**Comment by chicoxyzzy** [comment]
good case. I was thinking the same thing

**Comment by kg** [comment]
Do you have control over the location of the audio buffers in your address space, or does the driver allocate them for you?

**Comment by kaoskorobase** [comment]
Usually the platform's hardware abstraction layer provides audio buffers to a callback that you fill in order to generate one callback period worth of audio. For timing purposes, there is often additional information passed to the callback, such as a timestamp that specifies the time a buffer will actually hit the DAC (for an in-depth treatment see for example [this paper](http://www.rossbencina.com/static/writings/portaudio_sync_acmc2003.pdf)). The latter feature is unfortunately missing from the Pepper API but present in CoreAudio on OSX for example.

**Comment by lukewagner** [comment]
WebAssembly specifically tries to keep itself orthogonal from the set of Web platform APIs that are exposed.  WebAssembly does, however, have the [explicit goal](https://github.com/WebAssembly/design/blob/master/GC.md#webidl-integration) of being able to interact with Web APIs directly without going through JS.  One specific subgoal is that it should be possible to pass a subrange of linear memory to Web APIs which are specified to take a typed array view without actually constructing a JS GC TypedArray view (the browser ultimate just wants a `(ptr, length)` pair, so that's what the WebAssembly caller could provide.  However, it is up to the individual Web APIs to provide efficient interfaces that avoid mandatory garbage generation (e.g., allowing users to provide their own buffers instead of creating new ones internally).  Fortunately, many Web APIs already do this.  I expect any current suboptimal Web APIs can be evolved over time to provide newer, more efficient alternatives.

**Comment by kaoskorobase** [comment]
OK, thanks for the clarification!
