### ISSUE TITLE
Include byteswap and rotates in the MVP

### ISSUE THREAD

**Issue by mbodart** [WebAssembly/design#422]
Of the integer operations listed in FutureFeatures.md, it seems bswap and the rotates belong in the MVP.  I imagine they have as much utility and direct hardware support as popcnt, clz and ctz.

They seem trivial to support, and increase the richness of the MVP, so I don't see why we would defer them.

I created PR https://github.com/WebAssembly/spec/pull/149 for support in the spec interpreter.

Of course, AstSemantics and other tools would need updating as well.

What say all?

**Comment by JSStats** [comment]
+1 to bringing low hanging fruit into the MVP.

**Comment by jcbeyler** [comment]
+1 too :)

**Comment by jfbastien** [comment]
Hmm, reading @sunfishcode's comments on #121 I'm a bit confused... It sounds like he added bswap based on a comment, but the description says otherwise because it's hard to polyfill. I don't quite recall.

**Comment by sunfishcode** [comment]
The observation is: we don't need to worry about the polyfill being slow for operators like these, because it'll be no worse than what apps that need this functionality would do instead.

These operators were removed from the MVP due to a general desire to keep the MVP focused. bswap in particular is tricky because 32-bit and 64-bit bwap begs a 16-bit bswap too. It'd probably have to have the extra behavior of zeroing the high 16 bits, and it'd be asymmetric between i32 and i64. And, since some architectures fold bswaps into loads and stores (e.g. x86's movbe instruction, and other architectures have similar things), would it be better to have an optional endian attribute on regular loads and stores, instead of a standalone integer operator?

Rotates on the other hand are simple and have prominent use cases. :-)

**Comment by titzer** [comment]
Since this operation is pretty common and there are architectures with this
explicit instruction, this seems OK to me, but I'm not sure if it's
pressing enough to add to MVP. We'll probably implement this "just for fun"
but not sure all engines need to in MVP.

**Comment by mbodart** [comment]
As with any large project I can understand the desire to avoid feature creep in the MVP,
towards keeping schedules manageable and allowing sufficient time for good design.

But bswap and rotate seem straight forward to define and implement, certainly no more difficult,
nor less pressing I would imagine, than popcnt/clz/ctz.  Low hanging fruit, as @JSStats put it.
So I don't see what holding them back buys anyone.

The 16-bit argument seems generically applicable to all integer operations.
Adding 32/64-bit flavors now does not inhibit adding 16-bit flavors later.

Bswap is often used in conjunction with memory accesses, so I can understand
some hesitance to add a non-memory form.  But the non-memory form can be easily
folded with an i32.load on architectures that support bswap from memory.

**Comment by taisel** [comment]
+1 Byteswap stuff being folded into loads and stores as endianness argument.

**Comment by mbodart** [comment]
It appears bswap was not as "slam dunk" as I envisioned.

I still think some form of bswap is appropriate for the MVP, as the alternative emulation sequence with shifts and masks is quite verbose (i.e., non-compact).  But for purposes of moving this issue forward, I'm fine with deferring consideration of bswap, and focusing on the rotates for now.

Any objections to adding the rotates?

As I'll need to update the spec PR (and AstSemantics.md), I'll go ahead and switch to the "t" names, rotl and rotr, that are used in the Futures section.

**Comment by taisel** [comment]
+1 the suite of rotate operations. The bswap stuff can be pattern matched from the shift operations as well. I thought I even saw that already in turbofan.

**Comment by mbodart** [comment]
I'm closing this issue as the rotates have been added.

Byteswaps can be addressed separately, if desired.
