### ISSUE TITLE
Add block scoped variables with one initializing writer and multiple readers.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#429]
The matter of block scoped variables has been discussed, but was rejected or at least deferred.

One of the reasons expressed was that an interpreter would want to allocate a single frame on entry, however with the expression based encoding in wasm it would seem that even an interpreter might need to allocate extra local storage for expression intermediate values. Supporting block local variables with one initializing writer and multiple readers seems only a small step from what the interpreter would need to support anyway?

Another reason expressed was that the v8-native parser can efficiently convert wasm into SSA form and that supporting block local variables would frustrate the algorithm, and might require extra passes, and more dynamic data structures. But surely this parser already needs to support block local definitions for expression values, and might it be only a small step to also support block local variables with one initializing writer and multiple readers?

Might this support reduce the number of general variables need per function and might this actually assist a compiler? I see reports of poor compiler performance with a lot of general variables in asm.js code, and might compilers be able to handle the proposed block scoped variables more efficiently. Might compilers be able to take advantage of the declared local scope of a definition to be more efficient compiling.

The code could fail to validate if these variables were written apart from their initialization, or the syntax and binary format might simply not support writing to them.

Even with the single-writer restriction these could be very useful for upper layer code transforms. For example, it is often the case that an unsupported operation can be implemented using a number of existing operations, but without block local variables it becomes necessary to write the arguments referenced multiple times, or arguments reference out of order, to function scoped variables to be read by the filling operations. Block local variables could copy the argument values and preserve their evaluation order and allow multiple readers in the filling code, and it would not require new function scoped variables so it opens a path to making these transforms while streaming the code rather than transforming one function at a time.

**Comment by jcbeyler** [comment]
Seems like this is a tangent of https://github.com/WebAssembly/design/issues/381. I think this is a lesser evil and could be good. It would solve inlining small methods btw :)

**Comment by lukewagner** [comment]
I agree that implementing write-once block-scoped bindings would be roughly equivalent to expressions since they avoid the need for phis and a slot in the SSA environment maintained by Ion MBasicBlocks.

I don't really see this helping reduce the number of variables since a good compiler will try to reuse vars anyways (effectively performing regalloc on the locals).  And if a dumber compiler is able to reason about block scoping, it should be able to simulate block scoping in terms of locals.

I do see block-scoped bindings being useful for macros however, for the reasons you mentioned.  However, as already [explained](https://github.com/WebAssembly/design/issues/381#issuecomment-147012922), I don't see them being *necessary*; the macro generator should be able to easily simulate block-scoped bindings in terms of locals used in a stack-y manner.

Thus, I'm still waiting to see a case where block-scoped bindings are necessary or fundamentally enable some use case.  That best argument I've been able to come up with is that a dumb compiler might be able to generate a little better naive regalloc since the block-scoped bindings have some liveness info baked in (like expr trees).  But I'm not sure that's compelling enough.

**Comment by JSStats** [comment]
Give up on this for now as there is little support, and it looks practical to offer some support using meta information that allows let variables of sorts that are backed by the function local variables but that still communicate to the reader the lexical extent of the binding.
