### ISSUE TITLE
Why is select a "type-parameterized" operation?

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#474]
Since it's just a strict form of `if_else`, it seems like it should be parametric like `if_else`: e.g. instead of writing `i32.select` you just write `select` and the `i32` is inferred from the context.

**Comment by rossberg-chromium** [comment]
This was discussed before, but I don't remember whether there was a resolution.

Putting my semantics hat on, `select` could either be defined as _"type-indexed"_ (with an explicit type in the name) or _"type-parametric"_ (with no type in the name). I'm not sure what "type-parameterized" was supposed to mean, it could be either.

**Comment by AndrewScheidecker** [comment]
What's the plan for `select` and SIMD vectors? If `select` on vector types takes a vector condition, then it wouldn't be strictly parametric.

One option is to say `select` is parametric and just chooses between two values based on a scalar condition, and then add a `vector_select` that takes a vector condition and does a per-lane select between two vector values.

Another is to say that `select` takes a vector condition if its other operands are vectors. I think in that case it does kind of make sense for it to be a *"type-indexed"* operation.

**Comment by sunfishcode** [comment]
We'll definitely want a select which takes a vector condition and does a per-lane select.

I don't yet have a sense of whether select with a scalar condition and vector operands will be worthwhile.

**Comment by rossberg-chromium** [comment]
@AndrewScheidecker, makes sense. So we should keep it as is?

**Comment by sunfishcode** [comment]
Could a "type-parametric" select for SIMD operations could be interpreted in a way that takes a vector condition? That's consistent with the general model of projecting scalar operations into SIMD, by performing one independent instance of the scalar operation in each SIMD lane.

**Comment by AndrewScheidecker** [comment]
> Could a "type-parametric" select for SIMD operations could be interpreted in a way that takes a vector condition?

That seems like overload polymorphism rather than parametric to me.

> That's consistent with the general model of projecting scalar operations into SIMD, by performing one independent instance of the scalar operation in each SIMD lane.

But I assume those operations will all include the type in the opcode: e.g. `f32.add`, `i32.add`, `f32x4.add`

My own intuition is that it's best to make `select` parametric and have a separate non-parametric `vector_select` or `mix` or whatever.

**Comment by titzer** [comment]
Given that we'll have to sort out SIMD as a bulk proposal at a later time, move to close this issue?

**Comment by JSStats** [comment]
Is there a conflict between the v8 `select` and the current spec, which seems to have `i32.select` etc? If so then might this be a suitable issue to discuss it and resolve it?

**Comment by titzer** [comment]
AstSemantics.md just has `select` and mentions "two additional operands,
which must have the same type as each other."

**Comment by JSStats** [comment]
Ok, thanks. But then is the spec out of sync with the design docs? The spec tests use i32.select, f32.select, f64.select.

**Comment by rossberg-chromium** [comment]
My understanding is that `select` for SIMD types will behave pointwise, in which case it is an operationally different operator. For that reason, `select` is not a parametric operator, and should have the type explicit in its name, in the same way `add` has.

**Comment by titzer** [comment]
On Thu, Jan 21, 2016 at 3:08 PM, rossberg-chromium <notifications@github.com
> wrote:

> My understanding is that select for SIMD types will behave pointwise, in
> which case it is an operationally different operator. For that reason,
> select is not a parametric operator, and should have the type explicit in
> its name, in the same way add has.
>
In that case I think it should be given a different name and we should
preserve the type-parameterized nature of select. Thus, for any type T,
select<T>(a: T, b: T, cond: i32) is valid.

**Comment by lukewagner** [comment]
+1

**Comment by rossberg-chromium** [comment]
I'm fine with that, just want to make sure that we're not deciding this to be a parametric operator today, and then sneak in overloading when we extend to SIMD later. (Also, that means that we'll have both `select` and `f32x4.select` with SIMD, which might potentially confuse some people.)

**Comment by titzer** [comment]
On Thu, Jan 21, 2016 at 3:43 PM, rossberg-chromium <notifications@github.com
> wrote:

> I'm fine with that, just want to make sure that we're not deciding this to
> be a parametric operator today, and then sneak in overloading when we
> extend to SIMD later. (Also, that means that we'll have both select and
> f32x4.select with SIMD, which might potentially confuse some people.)
>
Agree; we definitely will want a better name for the vector select.

**Comment by JSStats** [comment]
I don't see any rationale behind these decisions. Could I ask if people have reasons for these choices?

Why not allow `add` to be 'a parametric operator` also, and many of the other operators?

**Comment by rossberg-chromium** [comment]
@JSStats, the definition of parametric is that the observable behaviour is type-agnostic. An equivalent definition is that an operation never needs to inspect the actual value. That is not the case for addition, which very much looks at the values, and has specialised behaviour for each type. So each addition is a different operator. If you were to collect them under a single name, then that would be a form of overloading.

**Comment by JSStats** [comment]
@rossberg-chromium Thank you. I think I understand the definition now, but still not the rationale? This definition assumes that the copy-through operation is type independent but at the machine code level this is not the case when using unboxed values so from a machine code point of view it is still an 'overloaded' copy operation. Is there any substantive technical difference between allowing some overloading (without conversions) versus using separate opcodes?

If there is an advantage one way or the other then perhaps it applies to the copy-through cases too.

For example a limited compression predictor might do better if the parent opcode is always typed - it might not be of high enough degree to look back further. Such an issue would apply equally to `select` or `add`. This is just a contrived example and I don't think wasm should be designed to the limitations of a predictor.

**Comment by rossberg-chromium** [comment]
@JSStats, note the use of the word "observable". That is key. We are defining a language by defining its observable semantics. On that level, no special handling for copy operations is prescribed. There is no observable difference between what happens for different types or different values. Under the hood, an implementation of course can do whatever, but that's an implementation choice and implementation detail, and not an observable part of the language semantics. So it "does not matter".

**Comment by sunfishcode** [comment]
I think the key is that @rossberg-chromium is using a certain model of computing that has some level of builtin type-genericism. On this model, one doesn't need to handle i32 differently from f32, because the model takes care of it implicitly.

However, there exist other models of computing where this is not the case -- actual CPU hardware being among them. Most physical CPU architectures have different instructions for i32 select vs f32 select. On this model, if we make select "parametric", JITs will end up doing something which is the same as what they'd have to do for "overloading".

So technically, it's not select being "parametric" versus "overloading" that's arbitarary -- that falls out naturally from whatever model we chose. It's the choice of model that is arbitrary. A practical approach would be to choose a model which reflects how we expect implementations to work in practice.

**Comment by lukewagner** [comment]
The practical reason I'm definitely in favor of the type-parametric operators like `get_local` is that as we add N more builtin types and then an open-ended set of user-defined [GC reference types](https://github.com/WebAssembly/design/blob/master/GC.md#native-gc), we'll want, e.g., the same `get_local` for all of them.  Not so for `add`, which is the usual one people ask about.  The parametric operators are exactly the set that make sense for all these future types.  I think `select` makes sense to be parametric since it's just an `if` where arguments are evaluated eagerly.

**Comment by rossberg-chromium** [comment]
@lukewagner, yes, excellent point. Parametricity means that it works for all types, present and future, without requiring any new definition.

**Comment by rossberg-chromium** [comment]
@sunfishcode, that's an interesting argument. But it is wrong. :) Here is why.

You are right that there are many possible models for a given operational semantics. The CPU model you suggest would be a valid model for Wasm, in the sense that it is _sound_. That is, it would not allow us to derive incorrect predictions, e.g. that two programs are equivalent that actually aren't according to the defined semantics.

However, this model, like most others, is not _complete_. That is, it distinguishes programs that are not actually distinguishable by the defined language semantics itself. It contains "too much detail" relative to the defined semantics, detail that cannot actually be "observed".

The way observability is usually defined is by whether you can give a program that can tell the difference, i.e. can make an actual decision based on such an observation, such that it produces obviously different outcomes (e.g., terminating vs diverging). If you can't, it is not observable and thus semantically irrelevant. The level of detail and abstraction that is relevant is not random, it is determined by the specified semantics.

For example, in Wasm the two functions
```
(func $f (nop))
(func $g (local $x i32) (set_local $x (i32.const 666)))
```
are observationally equivalent. You will not be able to write program that can tell the two apart. In a sufficiently low-level CPU model, however, you could probably tell that $g clobbers some register. Fortunately, Wasm does not allow you to write a program that can observe that. That is important, e.g. because it is only observational equivalence that justifies compilers to apply optimisations. A compiler can replace $g with $f locally, without having to worry about callers.

When you talk about semantic properties, you are only interested in models that match what the semantics defines as closely as possible. In that sense, while there are arbitrary many possible models, the choice among them is not at all arbitrary: you want a complete model. Finding a canonical model that is sound & complete is not always easy, but in the case of Wasm it is.

Anyway, I apologise for the lecture. With respect to parametricity specifically, the more direct manifestation of all that is was what Luke said. :)

**Comment by JSStats** [comment]
@rossberg-chromium Thank you again. I think you raise a good point. I see 'redundant information' as an issue in a number of areas. It reduces the information density in the presented source code to have all the types.

However it seems possible to define a reversible transform between the two options, so there is no loss of information, and both seem 'complete'. Perhaps you ignored that the types would be validated. It adds no information to annotate the nodes with their type if the type is otherwise constrained, and conversely there is no loss omitting the type.

The same seems to apply for `add`. For example: '(i32.add (32.add (i32.const 0) (i32.const 1)) ...)` is equivalent to `(i32.add (add 0 1) ...)` for top down type constraints and to `(add (add (i32.const 0) (i32.const 1)) ...)` for bottom up type constraints.

Here's a challenge for top down type constraints: `(block (select .. (i32.const 0) (i32.const 1)) (i32.const 0))`.

I suspect that all the redundant information, with separate opcodes, is not going to help the compression but will explore this to try to understand it better. For presentation I am considering a reversible transform to increase the information density, that is transforming to `i32.add` to `add` etc using the type constraints. A attempts at an implementation might expose failures in my understanding.

**Comment by titzer** [comment]
On Fri, Jan 22, 2016 at 3:52 PM, Luke Wagner <notifications@github.com>
wrote:

> The practical reason I'm definitely in favor of the type-parametric
> operators like get_local is that as we add N more builtin types and then
> an open-ended set of user-defined GC reference types
> <https://github.com/WebAssembly/design/blob/master/GC.md#native-gc>,
> we'll want, e.g., the same get_local for all of them. Not so for add,
> which is the usual one people ask about. The parametric operators are
> exactly the set that make sense for all these future types. I think select
> makes sense to be parametric since it's just an if where arguments are
> evaluated eagerly.
>

Agree with Luke here. We'll have an unbounded set of user-defined types in
the not-too-distant future, so we need to plan for that with parametricity.

**Comment by rossberg-chromium** [comment]
@JSStats, sorry, I was going on a tangent. My reply was addressing sunfishcode's point about models more generally. Intent was to explain that "observations" and "parametricity" have well-defined meanings, and there isn't much definitional leeway. (FWIW, a "reversible transform" -- I suppose you mean a bijection -- does _not_ exist between the models of different abstraction level that I was alluding to. Because one has genuinely more information. Well-typedness doesn't affect that, as it doesn't cut "redundant" information from _valid_ states, it only removes _invalid_  "junk" states from the model.)

Without going on a tangent again, your point is a different one. You are right that type information can statically disambiguate different operations. But as I said before, that effectively is overloading resolution; it means that the execution semantics of the operator then has to "switch" on this type information (or alternatively, there is a rewriting step somewhere). The nature of parametric operations is that their semantics never have to type-switch, because their definition is universal. I think it is a wise design decision for Wasm to avoid the complications of overloading.

**Comment by JSStats** [comment]
@rossberg-chromium The transform would be between two canonical models, so the canonicalization would remove the redundant type information on nodes. You are correct, if you start adding redundant type information to a canonical model then you are adding information namely the location of the redundant information. Still thinking this through, so do not have enough command of the topic to add much more.

Another query on this is how the empty-type (result of `unreachable`) propagates (bottom up) through `select`. Is it the same as for `if_else` where one of the paths can be the empty-type but if the other is not then that propagates to the result type? Or would the result be the empty-type if either is the empty-type?

From a top-down perspective, will both of the paths need to match the expected type, or if one is the empty type would the other be ignored. They are both pre-computed, so the `select` operation would also always be unreachable if either is unreachable, and it is 'parameterized' so has no type itself to resolve the matter. What do you think?

**Comment by rossberg-chromium** [comment]
@JSStats, the redundant information in those models wasn't type information, though.

FWIW, `unreachable` does not have the empty type, it has any type. In bottom-up type checking the standard approach is to use a type variable for that and resolve it via unification/join. V8 does a simple form of that, I think.

One thing to note here is that top-down vs bottom-up are algorithmic considerations. They do not matter for the actual definition of the type system, which is entirely declarative. That is, the type system doesn't prescribe a particular algorithm, and can be equally implemented both ways (or in others). Even though ML-proto actually implements it a as a top-down algorithm, the intention is that it reads very much like the declarative typing rules you'd write on paper.

If_else and select both have analogous typing rules, the evaluation order does not matter for typing.

**Comment by lukewagner** [comment]
@rossberg-chromium I do have a practical concern that there are conflicts between a top-down type system and simple/efficient type-checking of a postorder binary encoding.  Is there an equivalent bottom-up algorithm with cheap unification?

**Comment by JSStats** [comment]
@rossberg-chromium Unreachable returns the empty-type, the set of no types, it validates against any expected type. Any-type is something else, the set of all types and I don't think it exists in wasm - it's not possible to return an i32 and an i64 etc from any wasm operators, and it would not validate against a more specific expected type.

@lukewagner Not sure about unification, but I have a sketch of a bottom up algorithm passing up the empty-type through only the 'parameterized' operators which otherwise have no type, but not passing it further. Need something more concrete to consider your proposal.

**Comment by rossberg-chromium** [comment]
@lukewagner, V8-proto type-checks bottom-up, so that's probably a yes.

@JSStats, are you perhaps misreading the code in ml-proto? The checker does not _check_ anything for `unreachable`, which implies that the operator can yield any type the context wants.

**Comment by lukewagner** [comment]
@rossberg-chromium Ah, I wasn't sure whether v8 implemented the exact spec.

**Comment by sunfishcode** [comment]
@JSStats @rossberg-chromium In practical terms, it doesn't make sense for `select` to have any-type, the empty type, or whatever wasm ends up having. Since it's strict, its only purpose is to deliver a meaningful return value.

I propose we address @lukewagner's concern above about user-defined types as follows:
 - `i32.select`: select between two i32 values
 - `i64.select`: select between two i64 values
 - `f32.select`: select between two f32 values
 - `f64.select`: select between two f64 values
 - `gc.select`: select between two values of the same user-defined GC type (parametric)
 etc.

This defines select exactly for the types for which it makes sense, it lets JITs avoid overloading behavior in practice (even if there's a language-theoretical sense in which we don't *call* it overloading), and it supports user-defined types in a practical way.

**Comment by lukewagner** [comment]
@sunfishcode Other than aesthetics, what is the advantage of having 5 `select`s instead of 1 assuming wasm already has other parametric operators (like `get_local`)?

**Comment by sunfishcode** [comment]
@lukewagner In practice, wasm engines will need multiple `select`s in their implementation on all the popular platforms, because of the need to use different instructions. With separate opcodes in wasm, they won't need to do a secondary switch on the type. Admittedly, it's relatively minor, but so is reducing the number of nominal opcodes slightly.

It might make sense to make `get_local` and `set_local` non-parametric in the same way too, for the same reason.

**Comment by rossberg-chromium** [comment]
@sunfishcode, by that argument, you'd want to do it for all generic constructs, because they all will use different instructions at different types. Are you sure about this?

**Comment by JSStats** [comment]
@sunfishcode Great point. There will not be endless types, just some specific types related to the machine code, and a 'gc' type which is just a pointer to a boxed object. Where else might this be done: `if_else` `get_local` `set_local`.

That seems to just leave `block` and `br` and `return`, and  the block in `loop` and `tableswitch`. Would/could we have an `i32.block`, and `void.block` etc?

My concerns are how this impacts the compressor, and if some of the redundant type declarations can be nicely canonicalized away for presentation.

**Comment by rossberg-chromium** [comment]
...and `call` and `call_indirect` and...

What makes you guys think that the set of types will remain finite? That's a very adventurous assumption. For example, we have discussed adding typed function pointers; with those, the set would already be infinite. Similarly with other structural or user-defined types we may want to add in the future.

**Comment by JSStats** [comment]
The result type for the function calls seems well declared on it's own, it is not 'parameterized' by the context.

I have asked a few times for the 'typed function pointers' to be defined but it has not so it does not seem fair to raise it - if the group members can not evaluate your conclusions for themselves then I don't think you should be raising them as reasons for choices. Perhaps now would be a good time, and how they relate to `select` `if_else` `get_local` `set_local` `block`?

The 'structural types' cases need some thought, as does multi-value case. Perhaps they just don't apply to `select` or `if_else`, and need to be handled by their components.

**Comment by lukewagner** [comment]
... and union types (e.g., one that can hold any JS value) etc etc.  I still don't see the value of un-parameterizing these parametric ops nor the cost.

**Comment by JSStats** [comment]
It sounds like you want to extend wasm to have type integrity over storage outside the linear memory. This would certainly enable more optimizations but it's such a different vm that you could just concede to add new `select` `if_else` `get_local` and `set_local` operators if it every happens.

The value and costs either way do not seem clear. I am working on this in two areas: the effect on compression, and the effect on the usability as a source code.

**Comment by titzer** [comment]
The best future proofing we can do is to keep `select` and other operators
type parametric and avoid overloading.

**Comment by sunfishcode** [comment]
There are reasonable answers to the objections raised here, however I've made my proposal and it didn't catch on, so I'll stop pushing it.

**Comment by JSStats** [comment]
We still have a conflict here between the v8 encoding and ml-proto. This issue is a change request for the ml-proto and spec which would appear to make it consistent with the v8 encoding.

@sunfishcode so you conceded to change the spec and ml-proto to match the v8 implementation?

@titzer The only reasons I can find in your comments is that 'We'll have an unbounded set of user-defined types in the not-too-distant future, so we need to plan for that with parametricity.'. Yet this seems to have been answered by @sunfishcode - that there would be a few variations for machine specific types and just one more for all the higher level abstract types.

**Comment by titzer** [comment]
On Thu, Jan 28, 2016 at 7:59 AM, JSStats <notifications@github.com> wrote:

> We still have a conflict here between the v8 encoding and ml-proto. This
> issue is a change request for the ml-proto and spec which would appear to
> make it consistent with the v8 encoding.
>
> @sunfishcode <https://github.com/sunfishcode> so you conceded to change
> the spec and ml-proto to match the v8 implementation?
>
> @titzer <https://github.com/titzer> The only reasons I can find in your
> comments is that 'We'll have an unbounded set of user-defined types in the
> not-too-distant future, so we need to plan for that with parametricity.'.
> Yet this seems to have been answered by @sunfishcode
> <https://github.com/sunfishcode> - that there would be a few variations
> for machine specific types and just one more for all the higher level
> abstract types.
>
I see that point, but I think we should avoid having two levels of types,
one for the "high level" type that maps onto a "machine type".

**Comment by JSStats** [comment]
It's an interesting challenge to maintain the type integrity at the lower level. Typically a higher level language lowers types to operations on machine storage classes etc, but it controls the generated code.

For example, if there is an object with a slot declared to be an integer in the range of say [0,10] then what happens when it is loaded? Does it go to an abstract type of integer in the range [0,10] rather than an i32, or i64, or even f32 or f64, and does the runtime then lower this internally to a machine specific type? Or is there an i32.get_slot operation that loads the slot returning an i32 storage class result and failing to validate if the slot type is not compatible? If it is the later then looking at the machine code generated would appear to show just a few patterns, one for each machine storage class, and just one more for all the other abstract object pointers, so rather than see it as 'two levels of types' it can also be seen a just a few storage classes.

The validator will need to annotate the types in the 'boxed' values with their abstract class, and the types in the storage classes with whatever numerical types are defined such as a range.

Notably the (bottom up) derived result type of a select operation would be a union of the two choices. This would be very workable as they are in the same storage class. Having a distinct select operation for this storage class, and defining the choice and result as having the same storage class (not the same abstract type) would seem to be very clear from a spec perspective.

How will `select` be defined when there are these abstract types? It can't still be defined as requiring both choices to have the same type because it will want to be able to select between different abstract type objects. If the storage classes are disjoint from the abstract type then a subtype relation might allow this to be specified.
