### ISSUE TITLE
Call Site Semantics

### ISSUE THREAD

**Issue by fmccabe** [WebAssembly/design#486]
Currently the call site does state what the convention for the call is.

One of the features of LLVM that is very useful for extensibility is that the call site explicitly declares the calling sequence of the call. I suggest that we do the same: annotate the call with a symbol that identifies the semantics of the call. For the MVP this can be something like "C"; but in the future, especially when supporting interactions with other languages, the call site can have other symbols.

**Comment by JSStats** [comment]
A separate call operation could be added in future. Would that resolve the issue?

I don't see any need to flag the call conventions in the current call operation.

**Comment by jfbastien** [comment]
Calling conventions will be clarified in the context of [dynamic linking](https://github.com/WebAssembly/design/blob/master/DynamicLinking.md) which isn't in MVP. Until then it's up to the .`wasm` generator to be internally-consistent, the only "out" calls are to the embedder and these have their own calling convention that the embedder and the wasm VM have to honor.

It would be useful to clarify this in the dynamic linking document above. Would you mind creating a concise PR for this?

**Comment by sunfishcode** [comment]
Is this concerning LLVM calling conventions like GHC, HiPE, WebKit_JS, or similar calling conventions in LLVM, which are used for supporting compilers and JITs?

One of the main purposes of these conventions is pinning certain values to certain physical registers for use by a compiler and runtime. However, WebAssembly doesn't have physical registers; it has infinite virtual registers, so it's not clear how such a feature should translate, unless we also add a concept of "pinning" certain virtual registers to registers in the underlying machine code.

Another purpose is interoperating with hand-written assembly that uses a custom calling convention. In WebAssembly, the default calling convention is very simple since the infinite register set means it doesn't need to save/restore registers, pass (small) arguments or return values in memory, or deal with other tricky issues at the wasm level. Consequently, the need for custom calling conventions for this purpose seems reduced.

Another purpose for some is ensuring that tail call optimization is always possible. This is needed on some platforms because some native calling conventions can't always guarantee it. However, if WebAssembly adds general-purpose tail call support, I assume we'd do so in a way that doesn't have such restrictions, so it wouldn't require a special calling convention.

Another purpose for some is in forcing arguments to memory instead of being passed in registers. However, this would be something that would need to be lowered before wasm is produced, so that the loads and stores are explicit in wasm.

Are there other kinds of special semantics you're envisioning?

**Comment by fmccabe** [comment]
>Is this concerning LLVM calling conventions like GHC, HiPE, WebKit_JS, or similar calling conventions in LLVM, which are used for supporting compilers and JITs?

Yes, except that I am mostly interested in deeper differences in calling sequences and return conventions. So, the typical calling sequence for a lazy language like Haskell will require different assumptions around the evaluation stack. It will be different again for compiling SQL and related languages.

By explicitly marking the call site; it opens the option for interoperability between languages.

**Comment by sunfishcode** [comment]
Lazy evaluation can be something that compilers can implement before producing wasm. For example, GHC lowers Haskell's lazy semantics into an IR called Cmm (related to C--), which is a fairly low-level imperative language. This is what its backends work from, includuing its LLVM backend, which reportedly [works quite well](http://blog.llvm.org/2010/05/glasgow-haskell-compiler-and-llvm.html).

**Comment by JSStats** [comment]
Looking at the link to the GHC LLVM backend, I noted 'the calling convention passes arguments in the hardware registers that GHC expects to find the STG machine registers in'. I presume the 'STG machine registers' would be function scoped variables in wasm. Have not looked, but it suggests the caller it is often making calls using the same sequence of these variables and the callee is copying them to the same sequence of variables. Lets say the native code passed some arguments in registers then the goal seems to be to try and allocate a sequence of the function local variables to this same sequence to reduce copying at calls? If so then the question is does wasm need a hint here, or would wasm consumers implementing good function global register allocation optimize this well anyway?

**Comment by JSStats** [comment]
On a side note the GHC LLVM backend link notes a 'TABLES_NEXT_TO_CODE' (TNTC) optimization, allowing a code pointer dereference to be avoided. In wasm the function pointer would be an index, and perhaps this use case adds support to these being dense indexes to support such function index tables. If the target functions had heterogeneous signatures then this might be simpler with indexes into a heterogeneous table.

**Comment by titzer** [comment]
Agree with @sunfishcode in that WebAssembly's model of unbounded virtual registers makes calling conventions disappear below this level of abstraction. Should we close this issue?

**Comment by JSStats** [comment]
It is an interesting use case, and perhaps worth of noting somewhere. The implication being that runtimes would want to optimize register allocation to avoid copying in such patterns.

**Comment by sunfishcode** [comment]
The topics raised by the original poster have been addressed. If people wish to discuss these issues further, or other issues, please file new issues.
