### ISSUE TITLE
Load from known constant address

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/design#503]
A load from a known constant address currently requires an extra `const` node, like this:

```
(f32.load offset=0x01234567 (i32.const 0))
```

Since this is a common case (eg. statically-allocated variables in C/C++) and since it's also a notable case where bounds checking should be trivially eliminable, we should consider making load/store's operand optional, eliminating the need for the `(i32.const 0)` node in this common situation.

(Or, if optional operands are inconvenient to encode in the binary format, perhaps this could use alternate load/store opcodes which don't have an operand.)

**Comment by jfbastien** [comment]
Is the concern that it makes codegen harder, that the binary size is bigger, or something else?

**Comment by sunfishcode** [comment]
It theoretically could make a common optimization slightly more expensive in a simple JIT. It could also theoretically impact code size in programs that use lots of static variables, which could turn out to be a common pattern because it'll be really efficient.

I'm raising the idea because I'm looking at code generated by LLVM, and this is an easy to spot thing. For example, every stack pointer prologue is going to load and store from `__stack_pointer`, where instead of `(i32.load offset=__stack_pointer)`, we'll currently need to do `(i32.load offset=__stack_pointer (i32.const 0))`.

**Comment by lukewagner** [comment]
At the AST level (i.e., AstSemantics.md/ast.ml), we have so many load/store operators, I'm reticent to double the size to add const versions.  At the binary encoding level, if we include the proposed extension I've mentioned a few times which lets an opcode fix some or all of the immediates of an operator), load-from-const could be as little as 2 bytes (1 for the load, 1 for the const).  And, of course, a layer 1 macro could represent the load+const as 1 byte.  So that leaves the simple-compiler advantages which don't quite seem worth it; simple compilers will need to focus on optimizing loads/stores anyways.

**Comment by jfbastien** [comment]
@sunfishcode would you be OK leaving this open, and revisiting pre-MVP when we can gather data?

**Comment by kg** [comment]
In practice the cost of an optional arg to the load and the cost of a ```nop``` or hypothetical ```const.zero``` opcode as an argument are going to be roughly equivalent. Adding to the opcode space is, as luke points out, probably not a great idea. We can always test it, but it seems like even more complication on top of the most complicated opcodes we have :-)

**Comment by jcbeyler** [comment]
Agreed that most likely the data will show that you have the same encoding size in the end. If data shows the opposite, I would be surprised.

**Comment by JSStats** [comment]
Is using the `offset` the same as using a `(i32.const 0x01234567)? If so then it will likely be better to choose just one canonical way to express this and for the encoder to have just one symbol for this high frequency case.

**Comment by titzer** [comment]
In the current encoding there are several bits left over, so I would agree with @lukewagner that this can just be handled at the binary encoding level, e.g. using a bit to indicate the presence of a dynamically computed index. Let's experiment with that when we have large scale programs. Ok to close with that resolution?

**Comment by JSStats** [comment]
Yes, lets revisit it with a much more general opcode table description etc, so handle it at the encoding level.

**Comment by kripken** [comment]
> Let's experiment with that when we have large scale programs.

We should be able to do that now, `emcc+asm2wasm+wasm-as` is a path that should work for any C++ codebase to translate it to the binary format (I was just doing some measurements on zlib, for example). Let me know if there is a useful experiment that could be done for this particular issue.

**Comment by JSStats** [comment]
@kripken The suggestion is to support a memory operator with an immediate constant offset and an encoding option. So add an opcode table that abstracts the argument types and allows general definition of variants with immediate constants and labels references. I've tried it already. Such an abstraction might also go a long way to cleaning up the binaryen code, making it table driven rather than so explicitly encoded in switches and methods etc.

**Comment by sunfishcode** [comment]
Ok. We can close this for now, though I'll likely revisit it in my prototyping.
