### ISSUE TITLE
signature restriction for imports

### ISSUE THREAD

**Issue by MikeHolman** [WebAssembly/design#515]
With no way to map `i64` into JavaScript, I think we should restrict `call_import` to disallow signatures containing `i64` types, at least for the web platform.

Also, when calling an import with integer type, we should define how it is interpreted. In asm.js we force FFI calls to be signed, I think interpreting as signed should be fine for wasm as well?

**Comment by titzer** [comment]
That sounds OK to me. V8 truncates int64 to 32-bits, but forbidding them is
even better.

**Comment by kg** [comment]
> With no way to map i64 into JavaScript, I think we should restrict call_import to disallow signatures containing i64 types, at least for the web platform.

ECMAScript will have i64/u64 eventually though. Would we want this restriction to hold forever? Or just restrict it so that it's invalid when loading the module in a runtime without i64/u64?

**Comment by sunfishcode** [comment]
Me too. JavaScript is very likely to gain real support for 64-bit integers in the future; when it does, we can allow wasm imports to use them, and then we'll be in a better place than we'd be if we implement some temporary workaround now that we'd be stuck supporting.

**Comment by kripken** [comment]
I agree on both: sounds good to disallow i64 imports for now, and also to make i32s interpreted as signed.

**Comment by jfbastien** [comment]
Can we disallow i64 until ECMAScript supports it, but agree that toolchains should just expose two i32s for now for user's convenience? That's easy for parameters, but return values are tricky.

**Comment by sunfishcode** [comment]
Exposing something for convenience now would be setting ourselves up with an annoying compatibility constraint in the future. Unless there's a clear need otherwise, it seems better to keep things simple.

**Comment by kg** [comment]
Upon more thought about this, I suspect if we disallow i64 for now, we will end up with some syscalls that pass pairs of i32s across the wire anyway. Maybe it's better to wait until it happens, but we should consider how we are going to address that when it does... I feel like that will become a de-facto ABI for wasm<->JS either way.

Once we *do* have i64 in JS, how much performance would we be leaving on the table if syscalls continued to split those i64s into pairs of i32's? Could we safely feature-detect at runtime and drop the splitting? Is it even worth being concerned about the performance of syscalls with i64 arguments?

**Comment by lukewagner** [comment]
+1 for "temporarily disallow until JS has real int64s`".  ISTR this being discussed somewhere else with the same conclusion but I can't find it now.

For `i32` (and `i64`, when it is eventually supported), In the JS-calling-wasm direction, I think we should coerce with the JS spec `ToInt32` (I don't think the signedness matters since wasm puts signedness on the ops, not the types).

**Comment by lukewagner** [comment]
I guess it depends on whether we consider syscalls part of any ABI.  With an OS, that is necessarily the case.  With wasm, the syscall is into JS so every toolchain/library can define its own.  With the WebIDL binding this would come up but I suspect use of int64 in WebIDL is also blocked on int64 in JS :)

**Comment by kg** [comment]
Pseudo-hypothetical example of how we actually can't just punt on this, we need to think about it:

```time_t``` is 64 bits, unless we want to bake the year 2038 problem into wasm. Real applications will, at some point, need to know what time it is. That means the syscall they perform to get the current time needs to be able to pass 64 bits across the wall, somehow. Likewise, any operation that takes a time will need to be able to pass 64 bits across the FFI.

Saying ```the syscall is into JS``` also ignores the reality that some of this code will not be running in a JS VM, even though most of it probably will be. Some of the syscalls will be implemented directly by the JS runtime even if you're in a browser, in which case the i64 constraint isn't useful.

I'm not suggesting that we bake the individual syscalls into the ABI - the issue is that there are enough syscalls that will use i64s down the road that we need to at least figure out what the solution is now, and make sure it's not something we will deeply regret later.

One option that routes around this would be for our current ABI to be 'i64s can't move as arguments or live in locals, only in the heap'. Then it's just 8 bytes, and you pass the address of the bytes in the heap. I can imagine lots of tricky problems with that, though...

**Comment by lukewagner** [comment]
`time_t` is a good example, but my point is that `time_t`-taking *syscall*s don't necessarily have to be part of any stable ABI.  Now a separate matter is the representation of `time_t` within wasm (if you dynamically link two wasm modules), but that can just be `i64`.

> Saying the syscall is into JS also ignores the reality that some of this code will not be running in a
> JS VM

I had assumed, but I see now noone has explicitly stated that, by "temporarily disallow", we were talking about host-specific restriction and only for imports/exports to/from JS, not in the wasm spec itself.

**Comment by kripken** [comment]
(Side note on `time_t/2038` - a libc port can use a double to communicate with JS, which has 53 bits of integer precision, enough for the year 142,606,336 ;) )

**Comment by jfbastien** [comment]
The main concern I'd have is if the platform has warts from day 1 which we can't get rid of. It sounds like time_t can be fixed without much issues: as @kripken says older builds which use `double` will "never" fail, and once we have `i64` we can do it The Right Way.

Are there other cases where we're not so fortunate?

**Comment by kg** [comment]
Well, the problem is not that we don't have a stopgap - ```double``` is fine - but if it's a stopgap, we need some way to transition to The Right Way in the future and it's not immediately clear to me how that would work unless we spec it.

Likewise, "```time_t```-taking syscalls don't necessarily have to be part of any stable ABI" is true but I don't think it holds unless we explicitly make it so. If by the time we ship the MVP we haven't specified a way to read the current timestamp, are we going to be happy with that?

The answer is probably just that we will standardize wherever possible (everywhere?) on designs that ensure we never have to use int64. doubles, storing the values on the heap, etc. That might work out totally fine for every case, but it still implies some mismatches with existing C APIs and syscalls on other platforms, which will pose hurdles for people doing ports and potentially introduce some performance disadvantages. I'm not worried about that, but we should consider it.

**Comment by lukewagner** [comment]
Definitely agreed on the goal to not bake in any warts and plan for the transition path from the MVP to the goal state.

> If by the time we ship the MVP we haven't specified a way to read the current timestamp

Specifying a way to read the current timestamp sounds outside the purview of the wasm spec and the C/C++ wasm ABI.  I think this is something we just need to be intentional about: whereas we *would* have the goal of being able to link dylibs produced by two different toolchains, I think we *wouldn't* have the goal of being able to use the supporting JS glue-code file of 1 toolchain with that of another: in the goal state, there is no JS glue-code file necessary, so it seems like we definitely want to view this as an impl detail.

**Comment by jcbeyler** [comment]
I am not in favor of removing i64 from call_imports. I know I'm a minority here but I am looking at WebAssembly used outside of the web world and outside of being used in Javascript but more as a portable language. 

I understand we might say that that is a post-MVP question but would rather not already have a language without i64 for imports :)

**Comment by lukewagner** [comment]
@jcbeyler Perhaps you missed the clarification in my above comment that what I think we're all discussing here is only disallowing i64 when imported/exported to/from JS (so this would be a web host environment restriction) and only as a temporary measure until JS has a proper way to represent int64.  Does that address your concerns?

**Comment by jcbeyler** [comment]
@lukewagner Yes it does (sorry for the delay I was out for a bit, but back now). In that respect, then I have no comments or problems with this :)

**Comment by flagxor** [comment]
So I believe the intention was that i64 be allowed in imports + exports, but fail if called from JS. This allows hooking up cross module calls with i64 args.
I'll look into clarifying this in the docs.

**Comment by MikeHolman** [comment]
This is now clarified in JS.md. Closing as fixed.
