### ISSUE TITLE
Alignment hints: boolean or integer?

### ISSUE THREAD

**Issue by MikeHolman** [WebAssembly/design#534]
Currently we specify that each memory access provides a power of 2 immediate for alignment, but it seems like this is optimizing for a very rare case. The vast majority of memory accesses will be naturally aligned. For those few which are unaligned, do we really need such specificity, and is the information usually available to the compiler?

For example, VC has an `__unaligned` modifier which will generate byte accesses, so I don't even know how a programmer would cause code to be generated with `(i32.load 2 ...)`. Is there some other scenario we have in mind where byte accesses are insufficient?

Also, there is inconsistency between spec, design, and binary format. AstSemantics.md implies alignment is specified for every access. The spec repo specifies alignment as an optional parameter, and the binary format has alignment as a boolean value (either natural alignment or unaligned).

I'm currently in favor of just having aligned vs. unaligned like binary format does, but curious what the motivation was for specifying exact alignment. In any case we should align the semantics across our repos.

**Comment by JSStats** [comment]
This looks like a dup of https://github.com/WebAssembly/spec/issues/217 which has some discussion.

**Comment by MikeHolman** [comment]
Thanks, you're right. I thought I saw some discussion around this but didn't find anything when searching design repo. Will close this and bring up my issues over there.

**Comment by jfbastien** [comment]
I don't think these are the same: I just want a maximum number in https://github.com/WebAssembly/spec/issues/217: not *all* powers of 2 make sense.

To answer your original question:
* In LLVM we have alignment information of this kind. The compiler works hard to infer alignment. You can also get unaligned values through packed structs. Non-C++ languages can also do fancy things.
* Having precise alignment (instead of just a boolean) allows a backend which knows misaligned data is slow or traps to break up the access. If you don't know it's 2-byte aligned then you'll break it up into byte accesses, instead of 2-byte accesses. That's quite a bit more work (need to merge the result too). There's there an advantage when you want to split accesses which the code says are likely unaligned: less code.

AstSemantics may be unclear: it says alignment is specified everywhere but our expectation was as you point out: the default was natural because that's the prevalent case. Spec or text being different simply reflects the default (no need to express it if it's implied).

The binary format being different sounds like a bug. @titzer ?

**Comment by lukewagner** [comment]
FWIW, the spec has alignment [optional](https://github.com/WebAssembly/spec/blob/master/ml-proto/spec/ast.ml#L36) where `None` is assumed to imply natural alignment (it's not semantically visible, so that part is not in the spec).

An important question is how this gets encoded in the binary format.  `load`/`store` are some of the most common ops, so ideally in the 99.9% case of natural alignment we should not be wasting a byte per load/store on a (variable-length integer) aligment immediate.  The same goes for the common case of `offset=0`.  The simplest option is to say "we'll just have a separate opcode for these special cases" but, with the [opcode table](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#backwards-compatibility), that means we'll need to introduce a new class of psuedo-operator-name strings which can be placed in the opcode table.  That's why I like the more general option of allowing any opcode table entry to fix a subset of immediates (so `align` and `offset` in this case).  This generalization means that if some C++ program needs (for compat reasons) *every* load/store to have `align=1` or if `offset=4` is super-common in module, these can also be given single-byte encodings.

**Comment by lukewagner** [comment]
Filed #235 to make alignment a simple `int` which makes the above explanation an epsilon simpler.

**Comment by MikeHolman** [comment]
Making alignment an int sounds reasonable.
