### ISSUE TITLE
Provisions for source mapping

### ISSUE THREAD

**Issue by stuartpb** [WebAssembly/design#602]
Is there any work in place standardizing a way to link a source map with a compiled WebAssembly binary?

I know I'm not alone in the fear that transmitting fully-compiled code will push the web toward becoming an even more obfuscated and opaque ecosystem than it already is. Knowing that there's a standard provision for attaching accompanying source code accessibly from day one would significantly alleviate that.

**Comment by mbebenita** [comment]
There is a discussion on this topic here - https://github.com/WebAssembly/spec/issues/258

**Comment by JSStats** [comment]
@stuartpb I share your concern.

1. Source code: keep in mind that although the binary is not very accessible it is still 'source code'.

2. A wasm deployment binary is not 'fully-compiled code' because there is no hardware that can currently execute the wasm deployment code and it is not designed to be executed without processing - not even a compliant interpreter could execute the function body code without at least firstly verifying it.

3. Perhaps the case that concerns you is the source-to-source compilation case, and you are concerned that the deployment source code it not in the preferred format of the developers? No matter what deployment language is chosen this case seems to still exist, and developers can still strip and otherwise 'obfuscate' their preferred source code. However I agree that it would be good to support developers who wished to cooperatively deploy accessible source code.

4. It is possible now to bundle source code in a preferred format along with the deployed wasm code, in an 'unknown' section, thanks to recent changes to the spec and implementations (at least v8, and many thanks to people who worked on this). This could be the actual text, or a link to it. I expect source maps will be officially supported for this use case. But there is no guarantee that the attached source code, or linked code, actually source-to-source compiles to the wasm executable code, and it is not possible to compel developers to include it. I doubt there will ever be a validation process, such as linked source-to-source compiler versions that would be used to validate the wasm executable code plus preferred source code before execution.

5. A different path is being explored by the [Web Low Level Language](http://WebLL.org/) project, which interprets the wasm deployed executable code as a more accessible source code, and then augments the code with meta information such as comments or choices between presentation patterns etc, so that the deployment code is the source code and no 'validation' step between a preferred source and the executable code is necessary. This might at least make the wasm deployed code more accessible, and I hope it might set an example that other people could follow for a range of familiar preferred languages.

6. In some ways wasm is in a better place than minified JS because wasm does not include formatting so can be presented in a far more readable format at the discretion of the user! If the community can help ensure that there are good quality views from the start and that they are integrated in web browsers then it may help protect these rights of web users by making it clear to developers deploying wasm that this is the context in which they are deploying their code.

**Comment by jfbastien** [comment]
I think this question is addressed [in the FAQ](https://github.com/WebAssembly/design/blob/master/FAQ.md#will-webassembly-support-view-source-on-the-web) and mentioned [under tooling](https://github.com/WebAssembly/design/blob/master/Tooling.md).

Closing for now, feel free to reopen if that's not the case.
