### ISSUE TITLE
Squash commits

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#645]
After chatting with @kripken and @dschuff I enabled the option to [only allow squash commits](https://github.com/blog/2141-squash-your-commits) on our currently active repos. It'll make it simpler to merge PRs with multiple patches into a single commit.

Leaving this issue open for any discussion! Or rather, use github's emotion buttons to like, dislike, party, or horse this issue.

/cc @titzer @binji @sunfishcode @rossberg-chromium 

🐎

**Comment by dschuff** [comment]
I heartily enhorse this event or product.

**Comment by rossberg-chromium** [comment]
Sounds like a good idea. But excuse a github layman: where do I find this alleged "Squash and Merge" button the link talks about? Does it only become available when you activate this option?

**Comment by dschuff** [comment]
You actually have to click the "Merge pull request" button first, and then the "confirm" button has a dropdown which gives you the option to squash or create a merge commit.

**Comment by rossberg-chromium** [comment]
Ah, okay. Thanks, will start using that!

**Comment by mbodart** [comment]
No issue with this, but just a question from another git layman, does this alleviate constraints on the complexity of the branch history?

I only ask because for an earlier change to spec, it was requested that I do a squashing rebase to simplify the pull.  In particular one of the changes in my branch was a conflict-resolved merge from master.  Will the squashing pull tolerate this automatically, or should such branches still be rebased?

**Comment by dschuff** [comment]
Squashing does simplify the history (and using github squashing is more convenient than doing it manually). If there are conflicts I think you still have to resolve them yourself (with command-line git, you can do this either via a merge or a rebase).

**Comment by jfbastien** [comment]
OK this all sounds good! closing and horsing! 🐎
