### ISSUE TITLE
Will-Never-Use Opcode?

### ISSUE THREAD

**Issue by BSalita** [WebAssembly/design#687]
Does WebAssembly have an opcode number that is guaranteed to never be used? This would be valuable to compiler writers who want to experiment with new opcodes and features. The experimental compiler would be paired with a corresponding interpreter.

The opcode could be followed by a length that tells the interpreter where to restart interpretation.

**Comment by distransient** [comment]
There is discussion to make `0x00` "Unreachable" here: #683 & #684 (it's currently `0x0a`)

[Right now](https://github.com/WebAssembly/design/blob/db2bb0bb8ddb3e69dad0fe9938ea7b376108e624/BinaryEncoding.md) there are no opcodes that are guaranteed to not be assigned an operation in the future.

**Comment by sunfishcode** [comment]
A significant idea that's being discussed in a variety of places is that of an *opcode table*, which would be a table in a wasm module that declares a mapping from numbers to strings, with the strings holding opcode names, and then the binary code would refer to these operators by number.

The opcode table would be more flexible than a single fixed reserved opcode range, because adding new opcodes would just be a matter of making up new names for them and adding them to the table in a wasm module that wants to use them. In particular, two people working independently on unrelated features would be likely to pick different names for their opcodes, so their extensions would be more likely to be compatible with each other than if they both used opcodes from the same fixed reserved range.

**Comment by flagxor** [comment]
Implementors have discussed this and decided not to explicitly reserve an opcode for this purpose for the MVP timeframe.
