### ISSUE TITLE
Can we eliminate initializer expressions?

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#751]
It seems to me that the motivation for initializer expressions is to relocate multiple data segments in a "library" module relative to a single base address.

Not only is it a little messy to define some subset of the operations that can be part of an initializer expression, it also means that any linker needs to be able to interpret those initializer expressions to decipher where the module expects the data segment to be placed relative to the base address.

IMO it would be simpler to drop initializer expressions and just say that each data (or element) segment needs its own independently relocatable base address.

**Comment by lukewagner** [comment]
> say that each data (or element) segment needs its own independently relocatable base address.

What precisely does that mean?  We have global immutable imports as the way to describe load-time values, but if we simply *require* every elem segment base to be a global immutable import, then that's kindof annoying for statically-linked modules that have no need.  So that suggests *some* form of choice between a fixed literal and imported value and that's basically all an initializer expression is today.

FWIW, in SM we actually treat initializer expressions as just the binary encoding of a trivial [tagged union](http://hg.mozilla.org/mozilla-central/file/6b65dd49d4f0/js/src/asmjs/WasmTypes.h#l448) and don't do any sort of general expression evaluation at instantiation time.

I understand the fear that initializer expressions would grow unweildy, and maybe I can imagine we'd find use cases for adding `i32.add`, but I can't imagine it growing much more complicated than that.  I don't think anyone wants to write a special instantiation-time interpreter.

**Comment by AndrewScheidecker** [comment]
> What precisely does that mean? We have global immutable imports as the way to describe load-time values, but if we simply require every elem segment base to be a global immutable import, then that's kindof annoying for statically-linked modules that have no need. So that suggests some form of choice between a fixed literal and imported value and that's basically all an initializer expression is today.

Yes, it could just be a choice between a fixed literal and an import. That's semantically the same as the initializer expressions, but I think that's much simpler than to couple it to the operator encoding: especially if you wanted to support offsets relative to an import, which is either just another possible tag, or a stack machine.

Another way to do it would be to create an immutable global for every segment's base address. A separate, optional section would bind those globals to literal offsets. If it's not present, then their bindings upon instantiation are up to the host environment. In the JavaScript API, you could add an additional parameter for the `WebAssembly.Instance` constructor that maps data/element segment indices to offsets. The presence of that section would clearly distinguish between relocatable and non-relocatable modules, and it wouldn't require ABIs to include some standard for how to name relocation imports.

**Comment by lukewagner** [comment]
I don't really see the benefit to that approach nor any concrete cost to the current one, especially if we started to include things like linear arithmetic.

**Comment by AndrewScheidecker** [comment]
My argument has two parts:
* I don't think it's worthwhile to allow modules to constrain segments to be allocated at a fixed offsets relative to a single relocation.
* If doing so is necessary, encoding import+const using a stack machine has a lot of different ways to express the same thing, and requires interpretation in the host as well as the linker. Adding another option to a tagged union would be simpler.

**Comment by lukewagner** [comment]
IIUC, point 1 is saying that you don't think any addition of functionality will be necessary past what is currently accepted by initializer expressions.  Given that, than what we have now is no more than an encoding of a tagged union ([see the code](http://hg.mozilla.org/mozilla-central/file/e78975b53563/js/src/asmjs/WasmCompile.cpp#l1006)) that avoids inventing new magic constants.  If, in the future, we wanted to 'break away' from expression encoding, we'd have that ability.

**Comment by pizlonator** [comment]
It's too late for this.
