### ISSUE TITLE
Support for EM_ASM_ in LLVM backend

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/design#769]
Currently the variadic forms of the EM_ASM macro (EM_ASM_, EM_ASM_INT,  don't play nicely with the llvm wasm backend.
The way it currently works with asm2wasm is:
1. the macro gets converted to calls to emscripten_asm_const_int, which is a variadic function
2. fastcomp's JSBackend transforms this to a call to emscripten_asm_const_[signature]
3. emscripten's glue code creates a function and adds it as a table entry in ASM_CONSTS, and generates a function _emscripten_asm_const_[signature] which dispatches to it from asm.js code
4. asm2wasm converts the normal _emscripten_asm_const_[signature] call into a wasm call_import instruction

The way it currently doesn't work with the wasm backend is:
1. the macro gets converted to emscripten_asm_const_int
2. llvm's WebAssemblyBackend transforms the call in the way it handles any other varargs call, pushing all the arguments on a stack in linear memory and passing a pointer to the args as a single argument for the function to later unpack
3. s2wasm tries to then convert the call to emscripten_asm_const_int in the .s file into emscripten_asm_const_[signature], but by this point the only signature it can find is ii (index of generated js function, pointer to vararg stack), so it always generates emscripten_asm_const_iii
   emscripten's glue code creates a 2-argument function in ASM_CONSTS and the function _emscripten_asm_const_iii
4. When the (call_import _emscripten_asm_const_iii ...) instruction is executed, either the expected signature doesn't match, or the arguments aren't in the form that the generated _emscripten_asm_const_iii function was expecting
   The issue comes about because the wasm backend isn't aware of emscripten's glue code, and so doesn't have any special handling for emscripten_asm_const_int that would let it emit metadata to preserve the original signature for a later compilation step.

I talked with @dschuff about possible solutions, and we came up with a few ideas that have interesting tradeoffs.

1: Move the transform from binaryen into wasm backend.
Pros:
- No changes to existing user code
- Small change to current toolchain

Cons:
- Couples wasm backend with emscripten glue code

2: Have wasm not support EM_ASM*
Users can still call in to JS [by externing their JS functions](https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native).
Pros:
- Cleaner separation of concerns, for implementers and users
- Don't need to implement EM_ASM-like functionality in other languages that compile to wasm
- No changes needed in toolchain (except deletion of current emscripten_asm_const handling in s2wasm)

Cons:
- Makes any existing code that uses this more of a chore to port to wasm.
- More work for developers to define this type of functionality.

3: Have non-vararg support for a small number of EM_ASM arguments
Predefine _const_ii, _const_iii, expose to users as something like EM_ASM_II. Emscripten glue should be able to match call sites directly instead of needing to go through metadata.
Pros:
- Don't need any compiler-level changes
- Most changes to user code will be small
- Keeps an EM_ASM-like feature as a simple way to interop with JS, in simple cases

Cons:
- Need to maintain both EM_ASM and FFI
- No single answer to the question "how should I call JS from C?"

Thoughts? Any context around EM_ASM that I'm missing? Is there prior work around calling into JS code from C code, that includes passing C arguments, that I missed?

**Comment by kripken** [comment]
cc @sunfishcode 

This is actually a good example of the type of information I was talking about in the meeting earlier! The problem here is that the compiler lowers the varargs call into lower operations in an irreversible way and without metadata to describe it, i.e., information was lost. You can imagine that this could hurt in LTO: if we have a varargs call to a function, and no other callers at LTO time, we could un-variadicify it in theory, **if** variadic calls were in a form we could still see and understand. But as things stand we can't. It's the same problem as described as in this issue.

Which suggests other options here,

4a) wasm backend emits variadic calls in a not-fully-lowered form, and s2wasm does the final lowering (and can then do the EM_ASM special handling while doing so, much like asm2wasm).

4b) wasm backend still does the lowering, but emits metadata for each variadic call that contains its signature. That is enough to create code on the receiver end, `emscripten_asm_const`, that supports the wasm backend's varargs format (we just tell it that metadata, then it knows how many args and which types).

**Comment by kripken** [comment]
There is also

5) Find another way to implement the EM_ASM macro at the C preprocessor level.

**Comment by sunfishcode** [comment]
@kripken The problem here is that information is lost before being translated to LLVM IR. Adding another LTO layer below LLVM IR isn't what fixes that.

@jgravelle-google Other prior art includes WebIDL and such, which are also doable, but that's a significantly heavier-weight approach.

Here's another idea, which may be a hybrid of 3 and 5:

```
#define EM_ASM_0(str) \
  (asm volatile("emscripten_basil(str)"))

#define EM_ASM_1(str, a0) \
  (asm volatile("emscripten_basil(str, %0)" :: \
     "X"((a0))))

...

#define EM_ASM_5(str, a0, a1, a2, a3, a4) \
  (asm volatile("emscripten_basil(str, %0, %1, %2, %3, %4)" :: \
     "X"((a0)), "X"((a1)), "X"((a2)), "X"((a3)), "X"((a4))))
```

Compile with `-S -no-integrated-as`, and then s2wasm can pick out the emscripten_basil "calls" in the output. We'll need a little bit of code to implement the 'X' constraint in the wasm backend, but it's doable. Return values are also possible to add, using output constraints. Thoughts?

**Comment by kripken** [comment]
@sunfishcode: yes, you can lose the information before translating to LLVM IR, or you can lose it after in codegen; regardless of where you lost it, if you instead preserved it - as e.g. the asm.js backend does - then you are capable of doing more thins on the code later. (I'm not saying this is an amazing thing to LTO, just that it's an example of LTO-relevant of information that wasm files lack.)

**Comment by kripken** [comment]
Regarding `EM_ASM_0` etc., that's like 2 (not having `EM_ASM` support), it means existing code won't just work. That would hamper adoption of the wasm backend and be a less-good upgrade story than we have been telling people we would have.

**Comment by sunfishcode** [comment]
How about something like this?
```
extern int em_asm_placeholder;

#define EM_ASM_HELPER(a0, a1, a2, a3, a4, ...) \
        asm volatile("emscripten_basil(%0, %1, %2, %3, %4)" :: \
                     "X"((a0)), \
                     "X"((a1)), \
                     "X"((a2)), \
                     "X"((a3)), \
                     "X"((a4)))

#define EM_ASM(...) EM_ASM_HELPER(__VA_ARGS__, \
        &em_asm_placeholder, \
        &em_asm_placeholder, \
        &em_asm_placeholder, \
        &em_asm_placeholder, \
        &em_asm_placeholder)

void foo(char *p, float f, int x) {
   EM_ASM(x, f, p);
}
```
s2wasm would then be made to recognize &em_asm_placeholder and strip those arguments. This technique has a static limit on the number of arguments passed, but we could make the number sufficiently high. I think this gets us pretty close. Anyone else have any preprocessor tricks they can add to make this even better?

**Comment by kripken** [comment]
Neat hack, and I think we could warn at s2wasm time if the limit is exceeded so it seems safe? (What is "[basil](https://en.wikipedia.org/wiki/Basil)" though?)

**Comment by binji** [comment]
You can use the preprocessor trick here to count macro args: https://groups.google.com/forum/#!topic/comp.std.c/d-6Mj5Lko_s

This is referenced by the a stackoverflow post here, to do something similar to above: http://stackoverflow.com/a/1872506

I used this trick in sexpr-wasm, actually: https://github.com/WebAssembly/sexpr-wasm-prototype/blob/master/src/wasm-emscripten-helpers.c#L43

**Comment by sunfishcode** [comment]
@kripken "basil" in this context is apparently a more obscure reference than I thought. It's meant to be something to mark a place for a tool to look, but obviously we could name it something else. And yeah, s2wasm could detect and warn when the number of supported arguments is exceeded. 

@binji Interesting; I wonder if one could do something like `PP_CONCAT(EM_ASM_, PP_NARG(__VA_ARGS__))` in order to create `EM_ASM_0`/`EM_ASM_1`/etc., along with the code [here](https://github.com/WebAssembly/design/issues/769#issuecomment-240585072)

**Comment by jgravelle-google** [comment]
Closing as implemented in https://github.com/WebAssembly/binaryen/pull/910
