### ISSUE TITLE
Short-circuiting conditionals (&&, ||)

### ISSUE THREAD

**Issue by kg** [WebAssembly/design#78]
In a discussion about control flow it came up that asm.js currently doesn't support && or ||. The resulting control flow trees are pretty complicated sometimes. I think we should make sure short-circuiting boolean logic is expressible in webasm so that the resulting AST is denser and shallower. Thoughts?

EDITED: clarity

**Comment by titzer** [comment]
Consensus is that we have statements = expressions, so building short-circuiting conditionals can be done pretty easilly.

**Comment by kripken** [comment]
Where is the discussion leading to statements = expressions? I must have missed it.

**Comment by lukewagner** [comment]
Even without stmts=exprs, AstSemantics.md currently has a ternary.  asm.js does not have short-circuiting because ternary was sufficient.

**Comment by kripken** [comment]
More generally, we have an open issue on statements =?= expressions, #223, which does not have any conclusion, nor any activity for almost 4 months. That's why I'm surprised to hear @titzer say "Consensus is that we have statements = expressions".

(No concerns from me on closing this particular issue about && and ||.)
