### ISSUE TITLE
Merge the module-scope index spaces

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/design#783]
There are a lot of different module-scoped index spaces right now:
- The **global index space** includes imported and internal global variables. It's used by global-kind exports, `get_global`, and `set_global`.
- The **function index space** includes internal functions. It's used by function-kind exports, table segments, and `call`.
- The **import index space** includes imported globals, memories, tables, and functions. It's used by `call_import`.
- The **linear memory index space** includes imported and internal linear memories. It's used by memory-kind exports.
- The **table index space** includes imported and internal tables. It's used by table-kind exports.

I think it would better to merge these index-spaces into a single **object index-space** containing objects of all kinds: all imports, all internal memories, all internal tables, all internal globals, and all internal functions:
- `call_import` would be removed, and `call` would use this index space.
- `get_global` and `set_global` would use this index space.
- Any future operations that can access non-default linear memories and tables would use this index space.
- Exports would just be a name and an index in this space.

This would make validating global variable types in particular a lot easier: since the current **global index-space** includes an implicit subset of the imports, you need to explicitly construct the global index-space on load to map a global index to a value type.

Any place that uses this index space would have to validate that the right kind of object is being referenced, but for all the index-spaces being replaced, these checks could occur entirely while loading the module.

There may also be some edge cases that were previously impossible that we want to disallow: e.g. tables with imported functions, or exporting imported objects. However, I think overall this would be a worthwhile simplification.

**Comment by lukewagner** [comment]
(Sorry for missing commenting on this earlier.)  I think it's useful to have separate index spaces for each kind of object since, at least in SM, these index spaces end up directly indexing into internal arrays and so I think, at least in my experience, it would be more complexity to try to smoosh everything together into one index space; we'd probably end up building some big internal array mapping back into the separate index spaces.

There's also a practical size win to keeping each separate index space smaller since this keeps immediates smaller.  A notable example is when we have multiple tables/memories and want to index into these tiny index spaces from the flags immediate of load/store/call_indirect.

Lastly, there's a vague concern that a single index space is more fragile since, when adding some new kind of object, you have to be careful you're not perturbing the meaning of the index space of existing modules (backcompat).

So overall, I'd really like to keep the index spaces the same.

**Comment by titzer** [comment]
I agree with what Luke said above. Separate index spaces means that we
don't have a giant array of all the things and need a way to unify (and
distinguish) all the things in the implementation (other than icky void*).

**Comment by pizlonator** [comment]
It's too late for this.
