### ISSUE TITLE
Reexporting JS imports has potentially surprising semantics

### ISSUE THREAD

**Issue by rossberg-chromium** [WebAssembly/design#798]
The first step of processing exports in JS.md says:

> - If index refers to an imported type definition, then simply re-export the imported JS value.

Is that really what we want? Globals and functions are converted/wrapped upon import, this requires to undo that, and store references to the original values.

It has some weird consequences, too:

- When importing-exporting-reimporting a global, the second module will repeat the conversion, and if the original value is a general object, may get a completely different result.
- When importing-exporting-reimporting a JS function, the second module may import it with a signature that is completely different from the original type under which it was exported.
- When exporting a JS function, the JS side may invoke it and see it returning values that are not Wasm values. That is weird, because it got it from a Wasm module after all.

An alternative semantics would be that reexporting a JS value produces the converted/wrapped item, which would presumably be less surprising and maybe simpler to implement, too. WDYT?

**Comment by lukewagner** [comment]
I definitely agree that that seems like the natural thing for immutable globals.  I didn't realize this pre-/post-coercion nuance so that's actually what we've implemented for immutable global reexports.

Given that, I see the symmetry for functions.  So thinking through some of the details:
* There would be some new "`ToWebAssemblyFunction(f, sig)`" conversion that wraps a JS function `f` with a wasm `sig` and returns a new JS function object identity that we'd accumulate in some vector of coerced-imports that can be re-exported.
* The wrapped function object returned by `ToWebAssemblyFunction` would be the same kind of exported-wasm-function as all other wasm exports.
* `ToWebAssemblyFunction(f, sig)` on an exported-wasm-function `f` either returns `f` or throws if `f`'s signature doesn't match `sig`
* Because of the above, you'd never double-wrap a JS function: once it's been wrapped, it is now an exported wasm function and gets signature-checked on future import.
* That also means that, while I can't assign a JS function to a Table element directly via `set`, I *could* get it wrapped and then assign it: either by import+`elem` or import+reexport+`Table.set`.  I really like this b/c it removes an otherwise potentially-frustrating limitation on import+`elem` usage without allowing full-on untyped JS functions in tables (which I'd like to avoid).
* If a single imported JS function was reexported twice, you'd get the same identity (because there is one `ToWebAssemblyFunction` coercion on import).
Does that match your thinking?

Initially I had some vague impression that this change would break JS devs' expectations around function identity (by comparison to ES6 module re-exports).  If wasm one day gets an `any` type, then we'd have the same "reexport the exact imported value" behavior as ES6, but that's not what we have here, so the coercion semantics makes sense.  So I'm in favor; good find!

**Comment by rossberg-chromium** [comment]
Yes, this sounds like what I had in mind (and matches ml-proto's host function behaviour, I think). Thanks for breaking down the details! Getting rid of the table exception is nice added value and removes an annoying failure mode.

So, I'll happily to LGTM a respective PR to the design repo. :)

**Comment by lukewagner** [comment]
Great, I'll write up a PR as soon as I have a chance.

**Comment by rossberg-chromium** [comment]
Fixed by #816 and #817.
