### ISSUE TITLE
WebAssembly.Table: Consider using less generic name

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#835]
In https://github.com/WebAssembly/design/blob/master/JS.md#constructor-properties-of-the-webassembly-object, the term "Table" is vague (very generic term; we also have "br_table" which is a different table). Being vague, it does not help the developer easily understand what benefit they get from this API.

Proposal: IndirectFunctionTable

**Comment by flagxor** [comment]
Yeah, Table is pretty ambiguous, even in context.

**Comment by lukewagner** [comment]
Even though tables can only contain `anyfunc` in the MVP, the reason there is an `element` argument to the constructor is that the plan is to allow more element types in the future.  Paired with GC types as well as `set_elem`/`get_elem`/`grow_table` operators, this would allow tables to serve as the basis for a rooting API (mapping integers to GC references).  So indeed, they are intended to be used far more generally than for just indirect functions.

**Comment by binji** [comment]
My understanding is that this is supposed to be a table of arbitrary structured data, not just for functions (that's why it has an `elem_type`).

**Comment by binji** [comment]
Oops, just beat me! :)

**Comment by mtrofin** [comment]
I see. A few more questions then:

When we add support for other types than functions, is the plan to add all that support in one go, which means afterwards, any upcoming `elem_type` will be implicitly supported, or will it be more liklely per `elem_type`, because each `elem_type` requires special handling by runtime or JIT? If the latter, are even all `elem_type` equal candidates?

What is the envisaged use of the API - add/remove mainly? Is there any reason developers may want to re-read what's there?

Thanks!

**Comment by lukewagner** [comment]
Just speculating here, but my expectation is that, at least in the shorter-term we'd add types to the set of allowed element types on a case-by-case basis, for the reason that you mentioned.  As t→∞, I can imagine, for regularity, the desire to support all types, but spending effort on supporting, e.g., `i32` et al seems like a waste for now.

For the envisaged API use: once we allow direct table access from wasm code (instead of only via JS API `Table.prototype.`{`get`,`set`,`grow`,`length`} as it currently stands), a primary use case would be C++/GC/DOM interop either using tables as stacks (pushed/popped by a standard C++ RAII-style rooting API) or heaps (with non-LIFO pinning/unpinning).  In either case, C++ would pass around an integer index into the table and use `get_elem`/`set_elem` to get the opaque reference value at use sites (analogous to function pointers and `call_indirect`).

**Comment by mtrofin** [comment]
Thanks.

Since specific `elem_type` require work to support, and, as you pointed out, some types have a weak rationale for even being supported, how about having a table per supported type? This way, the developer has a clear signal of what is and isn't supported.

**Comment by lukewagner** [comment]
Well, some types (function signatures, GC struct/array types)&mdash;actually most every type other than `anyfunc` and perhaps later `anyobject`&mdash;are going to be compound and thus there will be an infinite number, so I think you really want the Table&lt;X&gt; approach instead of the XTable approach of typed arrays.

**Comment by mtrofin** [comment]
Sorry, I meant "type" as in developer-facing concern, not as `elem_type`:

IndirectFunctionTable
ObjectTable (or GCHandleTable, whatever the name may end up being)

**Comment by rossberg-chromium** [comment]
@mtrofin, I don't understand what the benefit of such "Hungarian" naming would be. It would be a very inflexible scheme. It is not unlikely that we gonna have a hierarchy of types, some of which may be rather heterogeneous even from the JS perspective.

**Comment by lukewagner** [comment]
Just as a concrete example, I'm imagining the wasm-GC JS API ends up merging with and co-opting preceding [Typed Objects](https://github.com/nikomatsakis/typed-objects-explainer) proposals, so that you have:
```js
var Rect = new StructType({x:int32, y:int32, w:int32, h:int32});
var tbl = new WebAssembly.Table({initial:10, element:Rect});
tbl.set(0, new Rect({x:1, y:2, w:3, h:4}));
```

**Comment by mtrofin** [comment]
I see - the example helps understand the pushback to per-user visible type naming. 

Separately, I'm not sure what the motivation is for this level of generality, but that's for a different issue. I'll close this current issue (the naming).

**Comment by flagxor** [comment]
I can foresee making the tables more general could be the right way to go. That is of course intertwined with us also doing multiple tables (which we've also now assumed in various places). I'm not completely convinced that reusing the tables for that purpose is where we want to go, but that's why baby steps with MVP.
