### ISSUE TITLE
Support int8 and int16?

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#85]
Should Web Assembly explicitly support int8 and int16?

We've discussed this:
* In issue #82 w.r.t. load/store and implicit truncation / extension.
* In issue #81 because having int64 makes int8/int16 look more regular / less out of place.

A few thoughts:
* I think supporting these types makes it easier to have a dumb and fast compiler.
* It is more instructions to know about in the assembler, but less work to figure out patterns in the instruction selector.
* It adds complexity to a register allocator if we try to treat types differently.
* Opens the door for more advanced optimizations (value / bit tracking, or even vectorization).

We can also add these types to a later version of Web Assembly if just int32 / int64 prove insufficient.

**Comment by sunfishcode** [comment]
Exotic types like i3 and i1337 have uses for high-to-mid-level optimization (e.g. LLVM's optimizer), because they preserve a little more value range information. However, they must be lowered for codegen (e.g. WebAssembly) on any common hardware.

Types like i8 and i16 are less exotic, however many platforms don't have i8 or i16 arithmetic at all, and even on x86 which does have them, i16 arithmetic tends to be slow anyway, and i8 arithmetic is only occasionally faster than i32 arithmetic. But even then, C's promotion rules mean that all arithmetic is done at "int" width or wider by default, so codegen only ever sees i8 arithmetic when the optimizer has proven it safe to form. And in those cases, lowering i8 values to i32 usually leaves behind enough hints that a reasonably clever code generator can see that only 8 bits are needed and optimize to 8-bit arithmetic anyway.

I think the main arguments for WebAssembly to have i8 and i16 would be that we wouldn't need sign/zero-extending loads and truncating stores, and there'd be a little closer symmetry between SIMD types and scalar types (since SIMD will have 8-bit and 16-bit integer element types). However, since these types aren't actually that useful in scalar, it seems like a greater simplification to just omit them.

**Comment by sunfishcode** [comment]
Closing, based on the rationale in the previous comment. If anyone wants to revisit this, we can reopen or open a new issue.
