### ISSUE TITLE
Make sections ids always non-zero

### ISSUE THREAD

**Issue by mbebenita** [WebAssembly/design#860]
Concatenated `.wasm` files would be trivial to parse if section codes are required to never be `0`.  Currently, if the magic number (`0x6d736100`) appears at the end of another `.wasm` file, it can be interpreted as a user-defined section whose payload_len is `0x61` . While it's not that hard to check for the magic number when parsing sections, it would be nice to remove this source of ambiguity.

**Comment by jfbastien** [comment]
Hmm, this is clever... Are you suggesting that we rejigger things so that concatenating .wasm files "just works"?

**Comment by lukewagner** [comment]
Another solution might be a section-count in the module preamble.  I could imagine this being useful for other purposes as well...

**Comment by jfbastien** [comment]
A while ago for PNaCl, @flagxor had wanted to embed data in a `.pexe`. We ended up not doing this, and for wasm you'd use custom sections to do this, so I think if we do something here we want to control what the valid "extra stuff at the end" can be.

Just random data shouldn't be allowed because you should have used a custom section instead.

Concatenation seems like the only "valid" thing.

**Comment by mbebenita** [comment]
> Another solution might be a section-count in the module preamble.

This would make it more difficult to append sections to a `.wasm` file, as you'd also have update the section count field. If it's `varuint32` field then we'd also have to possibly shift everything down if the number of sections become too large. What other purposes did you have in mind?

**Comment by mbebenita** [comment]
> Are you suggesting that we rejigger things so that concatenating .wasm files "just works"?

Yes. Currently you can append new sections easily, this would make appending new `.wasm` files just as easy.

**Comment by rossberg-chromium** [comment]
I don't understand the use case. Why would I ever want to concatenate Wasm modules? There are very few, rather useless cases where that would not result in (invalid) duplicate sections. And why would it be too hard to strip the 8 byte header before concatenating in those cases?

**Comment by mbebenita** [comment]
> Why would I ever want to concatenate Wasm modules?

This makes working with multiple `.wasm` modules in the shell more convenient. CLI tools can be written to read and write any number of modules from `stdin` and `stdout`.

> And why would it be too hard to strip the 8 byte header before concatenating in those cases?

Certainly not at easy as `cat a.wasm b.wasm > c.wasm`

**Comment by binji** [comment]
This seems like a bad idea to me. What precedent is there for having a file format that can be easily concatenated in this way? Are you suggesting that all wasm binary file readers now have to be aware that there may be multiple modules in one file? What does a wasm execution engine do if it sees a file that has multiple modules? Agree w/ @rossberg-chromium, I don't see why this is useful.

**Comment by mbebenita** [comment]
> What precedent is there for having a file format that can be easily concatenated in this way?

Javascript Files

> Are you suggesting that all wasm binary file readers now have to be aware that there may be multiple modules in one file?

Only command line tools, I'm not suggesting that browsers should support this.

**Comment by wllang** [comment]
Seems a good idea to make the magic number follow the section format too, so have an assigned section code and a section size. This means it must start with a 'known' section code, so not zero, and be follow by the length `0x02`. Lets say that the section codes are bumped up so the magic number has section code `0x01` then the new magic number might be `0x76870201`.

**Comment by jfbastien** [comment]
We want the first byte to stay `0` so that it's not a valid JavaScript value so if you use a JS API with a wasm object it can just "do the right thing".

**Comment by wllang** [comment]
Guess this means bumping the 'unknown' section code then. E.g. use `0x01` for these. Btw calling these 'unknown' seems odd, could the term be changed to 'named section'?

Then the magic number could be e.g. `0x76870200`.

**Comment by binji** [comment]
Fair point about JavaScript. I meant binary file formats, but wasn't clear. In any case, it sounds like they would be serving completely different purposes; concatenating JavaScript is like a bizarre form of linking and is likely to be valid, but concatenating WebAssembly modules will almost never be valid.

I guess my thought is, if you really want to bundle multiple files together, why not be explicit about it and use a file format that reflects that like tar or ar?

**Comment by jfbastien** [comment]
I get why you have `0x0200`, but why `0x7687`? I think `0x4157` is better :)

**Comment by lukewagner** [comment]
@binji Agreed, I'm not really convinced this is a problem we need to be attempting to solve in wasm.

**Comment by wllang** [comment]
Being able to just concatenate them together is much simpler. Why not at least design the binary format to make it possible to do so, even if they need to be unpacked before passing to a wasm consumer, and it only requires a small trivial change.

**Comment by rossberg-chromium** [comment]
Agreed with @binji. If we wanted some kind of container format then we should design/use one, but that would be another layer and require different API to process.

@mbebenita, concatenation of JS scripts always was a hack that barely worked, and the ES6 module system does not support it either, which was a conscious decision.

**Comment by wllang** [comment]
The problem to be solved is making it trivial and robust to parse concatenated wasm binary files, for a valid reason known to the developer doing so and a reason that I for one think has merit. The solution is a trivial change of the magic number, and a renumbering of the section codes.

This is not a request for a container format, or to have consumers support concatenated wasm binary files, so arguments that 'concatenating WebAssembly modules will almost never be valid' is not useful because the user who does so has a valid reason.

The argument that 'if you really want to bundle multiple files together, why not be explicit about it and use a file format that reflects that like tar or ar' is also not useful because the user concatenating them has chosen this trivial file format.

Perhaps people need to look at the use case being requested to be addressed and take note of the trivial design change required - the requested change seems like a well spotted positive contribution to me.

**Comment by rossberg-chromium** [comment]
@wllang, no engine will be able to consume concatenated binaries with multiple modules, whether the magic header is ambiguous or not. Unless we make quite a few more changes to the semantics of binaries and the respective APIs -- essentially turning them into a container format. If OTOH clients just want to bundle for their own merit then it would in fact be easier for them to send along the trivial meta information to split the file again instead of decoding it to find the boundaries.

**Comment by wllang** [comment]
@rossberg-chromium As noted this issue is not about engines being 'able to consume concatenated binaries with multiple modules', so it's not useful to keep raising that point. The point is that it is *also* trivial to concatenate the wasm binary modules together which is the requested use case and the merits of this use case are a matter for the developer to judge, and I for one see this as one trivial option. Weighing this against the trivial design changes required, changes that do not prejudice other container formats, and it seems a positive change to me.

**Comment by qwertie** [comment]
I'd say if the extent of the change is to change the magic number then the question switches from "why bother?" to "why not?"

> I get why you have 0x0200, but why 0x7687? I think 0x4157 is better :)

A long time ago I proposed basing the Wasm container format on some existing standard (e.g. protocol buffers). Since that idea was rejected, I'm going to suggest a new idea: let's imagine the Wasm container format itself as a brand new template for simple binary formats. All we have to do is change the initial 8 bytes as follows in MVP:

00 06 04 77 61 73 6D 01

This combines the magic number and an (8-bit) version number into a single unit that can also be viewed as a valid section named "wasm"; thus the Wasm format can be viewed as an instance of a more general "list of sections" or "LOS" format. The LOS format, which (unlike a wasm-enabled web browser) supports concatenation of files, might be a useful starting point for other binary formats in the WebAssembly ecosystem that may be developed in the future. We could define the "magic number" of all LOS files as the three bytes 00 06 04.

**Comment by wllang** [comment]
@qwertie Great point, the version number needs to be in this header section too.

btw the `0x7687` example was in jest as i would have preferred this project be named as a Web Low level langage rather than a Web-Assembly code.

I also wish wasm had used a meta format like protocol buffers so that tools could work with it without having to know all the section formats and opcodes, but what would the encoding size cost have been.

**Comment by titzer** [comment]
Let's not bite off more than we can chew here. I think the main constraints
are:

- module should begin with an illegal JS character
- module should be self-contained list of sections

I don't really see the use case here, but wouldn't it imply and extra
constraint:

- module header is a valid section

Or is there something I am missing?

**Comment by wllang** [comment]
@titzer Yes, I think that is all that is being requested, to make the module header a valid section. For example, allocate section id zero for the module header and bump up the other sections ids and make say id 1 the unknown section id (or some other ordering people can agree on). A reduced two character string needs to be chosen, say "WA", or something else people can agree on. The 32 bit version code is included in this module header section. The module section header then becomes:

```
00 06 57 41 0d 00 00 00
```

**Comment by jfbastien** [comment]
This idea hasn't gone anywhere. Can we close?

**Comment by wllang** [comment]
@jfbastien Not 'gone anywhere' does not mean that it should not be applied. There are some views that the use case is not relevant, that no one should want to concatenate binaries or should add some other container if they do, but the technical fact remains that simply concatenating them is one trivial container, so why not make the trivial change to support it. It is frustrating that such issues have gone nowhere, but closing issues here might not be a constructive path forward for the group.

Could I put it to those who object to this change: could you live with it, and how does it prejudice your uses or wasm? I think that is what people should be asking themselves to unblock some of these issue and speed progress. If there are real technical objections beyond personal preferences then please raise them.

**Comment by wllang** [comment]
@jfbastien If you are going through these and see that they clearly block the MVP, such as the incompatible encoding change in this issue, could you please consider tagging them as such. If you do not want to conflate what technical blocks the MVP with what has been agree on then perhaps create a separate tag e.g. 'would block the MVP'.

**Comment by jfbastien** [comment]
@wllang I do not plan to organize these issues. Happy if someone else does.

**Comment by wllang** [comment]
@jfbastien Well do you expect 'someone else' from the small subgroup controlling the positions of Chair and with authority over this repo to even organize these issue? If not then can the group have back control of the Chairs and this repo?

**Comment by jfbastien** [comment]
Too late to change, closing.
