### ISSUE TITLE
Export JSFunctions should have string names

### ISSUE THREAD

**Issue by titzer** [WebAssembly/design#883]
I just noticed that in JS.md, we specify that the exported Function exotic objects, we specify the name of a function to be the index as a number. That seems to be at odds with ECMAScript, which seems to require that all function names be either a string or a symbol.

Should we change JS.md to specific the function index is stored as a string?

**Comment by rossberg-chromium** [comment]
In particular, the [SetFunctionName](https://tc39.github.io/ecma262/#sec-setfunctionname) meta function explicitly makes this assumption. A ToString conversion seems in order.

**Comment by lukewagner** [comment]
Yeah, I don't know what I was thinking when I wrote that because we assign a string too.

Actually, looking at the code, we don't assign the stringified index, we write the same function name we use in callstacks which will use the name provided by the names section.  I guess that's a bad idea, since it means stripping the names section could break code (which is technically true b/c `Error.stack`, but more in the fuzzy space).

**Comment by titzer** [comment]
We were doing something slightly different: using the name of the first export of that function. I think Stringified function index makes the most sense here.

**Comment by lukewagner** [comment]
Oh, that's a neat idea, and stable under name-stripping.  Technically there is the corner case of exported functions derived from `Table.get(i)` which have no exported name; which perhaps is what brought up this question in the first place.

I guess a question is whether `.name` is principally used programmatically or just for debugging/logging.  If the latter, we could do something friendlier string like `wasm function with index ${i} (and name ${s})` (where the parenthetical was optional).  But if the former, just stringified index will probably be best.

**Comment by rossberg-chromium** [comment]
Some implementations include the name when invoking toString on the function, though nothing around that is properly standardised, and it's already violated by some other cases. There are some concrete TC39 proposals on the way that do that, too, though IIRC.

**Comment by lukewagner** [comment]
Oh hah.  Just because of how the usual hooks work out, we currently print out `"function wasm-function[0]() {\n    [native code]\n}"` where `0` is the function index.

So noone's printing the binary->text in `toSource` here, are they?  Because that would require saving (at least parts of) the bytecode even when the `Module` is dead and also put the binary->text algo on the normal security surface.

So if we're not printing wasm text format in `toString`, then it doesn't have to conform to any language and it's just an aesthetic choice so something like `wasm function with index ${i} (and name ${s})` could make sense, keeping `.name` to the minimal `ToString(index)`.  How does that sound?

**Comment by lukewagner** [comment]
Or even `wasm function with index ${i} offset ${o} (and name ${n})` and then, if this same string is included into whatever overall `Error.stack` string format the engine already has, this could subsume #814.
