### ISSUE TITLE
Identity of re-exported imports

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/design#920]
There may be other places where identity isn't well defined, @saambarati and I have a few other issues on this.

As @lukewagner says here: https://github.com/WebAssembly/design/pull/911#issuecomment-267727506

For the current spec text, the question is whether this assert holds:
```
var js = () => {};
var m = new Module(wasmTextToBinary`(module
    (import $a "" "a")
    (export "a" $a)
    (import $b "" "b")
    (export "b" $b))
`));
var i = new Instance(m, {'':{a: js, b: js}});
assert(i.exports.a !== i.exports.b);
```
In SM the assert passes, because we're basically saying that each (instance, function-index) pair is given a unique exported-wasm-function-object, regardless of whether the function-index is an import. I find this easy to reason about and it also simplifies the implementation a good deal by allowing imported/internal functions to be treated much more uniformly.

I think the current spec text says the assert() should fail, though, because the associated closures would be equal (because the underlying JS object identities would be equal). To implement the spec, you'd need to maintain a separate hash-set of imported JS objects and query this set separately. Then, taking this PR into account, you'd have to eagerly walk an imported Table to put any wrapped-JS-functions into the hash-set. For example, this assert passes in SM (and I bet V8) but I think fails according to this PR:
```
var js = () => {};
var m1 = new Module(wasmTextToBinary(`(module
    (import $i "" "")
    (table (export "tbl") anyfunc (elem $i)))
`));
var i1 = new Instance(m1, {'':{'':js}});
var m2 = new Module(wasmTextToBinary(`(module
    (import $fun "" "fun")
    (export "fun" $fun)
    (import "" "tbl" (table 1 anyfunc)))
`));
var i2 = new Instance(m2, {'':{fun:js, tbl:i1.exports.tbl}})
assert(i2.exports.fun !== i1.exports.tbl.get(0));
```
I think the fix for both issues is to give all closures an (instance, func-index), on which equality is defined (and HostFuncs just have additional fields).

**Comment by rossberg-chromium** [comment]
Actually, upon rereading JS.md, I think Luke was misreading the current text. In particular, Step 4.iii.1, which applies to all imports that are not already Export Exotic function Objects, says:

> Let closure be a new host function of the given signature which calls v by coercing WebAssembly arguments to JavaScript arguments via ToJSValue and returns the result, if any, by coercing via ToWebAssemblyValue.

That is, for every JS import a _new_ host function value will be created unconditionally. And as pointed out in the note about equality of closure values, this shall be interpreted as being different from any other such value. Nowhere does it even compare underlying JS functions.

So AFAICS, the spec already says what Luke asks for.

**Comment by lukewagner** [comment]
Happy to see we're agree on the intended meaning here.  So I was interpreting "host function" to mean "JS function", but it seems like there is some sort of intermediate *thing* here with an identity that is neither a JS object nor a wasm function.  In particular, the hyperlink from "host function" to the [`HostFunc`](https://github.com/WebAssembly/spec/blob/master/interpreter/spec/instance.ml#L9), which is just a value constructor, makes this all a bit fuzzy.

Could the resolution to this issue be to keep the meaning the same but to clarify wording using (instance, func-index) pairs?  I find it pretty intuitive to say that each (instance, func-index) has a unique JS exported-function-object.  It also maps pretty clearly to what I think is the obvious [implementation](https://hg.mozilla.org/mozilla-central/file/5745bab28ff5/js/src/wasm/WasmJS.cpp#l1031) we'd all want to use to avoid eagerly creating all possible exported-function-objects (viz., for tables): an `Instance` object contains a mapping from func-index to exported-function-object that is lazily populated only for functions needed for the export object or `Table.get` calls.

**Comment by jfbastien** [comment]
To make sure I understand waht @lukewagner is saying: you have a unique JS object for each Instance's export, right? That sounds fine.

**Comment by lukewagner** [comment]
@jfbastien Correct, where "Instance's export" includes all functions in `elem` sections and thus accessible via Exported Function Objects `Table.get`.

**Comment by rossberg-chromium** [comment]
@lukewagner, hm, (instance, index) pairs will probably be even more confusing. They are not unique, since there may generally be several possible such pairs identifying a single Wasm function import. You would need to distinguish between imports that are real JS functions (get a new index) and imports that are Exotic Wasm functions (identified by their original index).

I think the only clean way to specify this is to properly model the generativity of creating wrappers. That's what the current text tried in the shortest possible way, but I agree that it should be more explicit.

**Comment by lukewagner** [comment]
This is probably something I'd have to write up to demonstrate what I mean; but there wouldn't be an ambiguity because b/c by construction you'd never end up asking for the exotic wasm function of a (instance, index) in the case where this pair referred to an imported exotic wasm function.  But yes, anything to clarify would be useful.

**Comment by rossberg-chromium** [comment]
This should be fixed by #987.

**Comment by littledan** [comment]
With the new WebAssembly spec, the definition of equality changes a little bit. Rather than closures, there's funcaddrs in the store. The current draft spec text I wrote here checks for something with the same funcaddr when looking through funcs to find something to reuse the object of, and creates a new ExportedFunction if not. For JS functions that are used from the outside, a new host function address is allocated each time that function is imported; but then, if it's somehow re-exported multiple times (I guess this would require new capabilities for WebAssembly), the caching would work too. The logic of iterating through the table, as introduced in #987, is preserved.

Any thoughts on whether this seems sufficient? I'm not sure if any additional clarifying notes are needed, and where they should go exactly. The spec is already explicit about comparing by \[\[FunctionAddress]] and it describes where those addresses come from, but it might be hard to understand just by reading it.

**Comment by rossberg** [comment]
Will have a look. FWIW, reexporting multiple times from the same module is possible today.
