### ISSUE TITLE
when is WebAssembly coming?

### ISSUE THREAD

**Issue by llfylwg** [WebAssembly/design#934]

**Comment by jfbastien** [comment]
There is a [published roadmap](http://webassembly.org/roadmap/).

**Comment by wllang** [comment]
@llfylwg Please note that as a member of this CG I do not agree with this roadmap for a number of reasons including that there are significant technical design matters to resolve and that it includes a transition to a W3C working group for which only paying customers of the W3C have any control and not us members of the CG. @jfbastien does not claim to be a Chair, and only our elected Chairs can publish documents for our group, yet he seems to claim authority over this repo to close issues, and I ask the only Chair I suspect was elected @lukewagner to please remove the authorization that @jfbastien has over this repo or please move our work to a new repo that the CG controls and ask @jfbastien to stop using our trademark or rename our CG. I am sorry the current state of this group is not pretty, and the only pretty outcome is to finish the design and get a great design out the door, and I am work on just one small part of this design in some spare cycles and might have some tentative results in a few months, so my guess is that even with a quick change in the tone of this group and new found cooperation that six months is the very earliest, and I expect rolling previews with less and less breaking changes over the year. Then again some people might try to a publish a spec, it might need to be disputed for good technical reasons, their standing to publish might need to be challenged, some people might break off to a W3C working group, we can only try to get a good design out and to try and do so in a business like manner.

**Comment by jfbastien** [comment]
Were the roadmap to change, [this URL](http://webassembly.org/roadmap/) would still be the right place to refer to.

Were one interested in changing the roadmap, then the [website repo](https://github.com/WebAssembly/website/) would be the right place to do so, specifically its [roadmap.md](https://github.com/WebAssembly/website/blob/master/roadmap.md).

Chairpersonhood has nothing to do with this. Specifically, answering valid questions can be done by anyone. If the question wasn't answered then the author is free to re-open the question (as with any github repo), as are they to ask further clarifications.

Please do contact the chairs or the W3C ombuds if you have questions or concerns about how the CG conducts itself.

**Comment by titzer** [comment]
Speaking as a Chair and as a tech lead on the Google side, the roadmap linked to by @jfbastien is accurate and is what we have agreed to.

**Comment by wllang** [comment]
@titzer As a member of this CG I was not given an opportunity to vote for you as a Chair, and I note your failure to explain your standing to claim a position of Chair and you have repeated your claim to be a Chair. It would have been a simple matter for yourself or any of the Chairs to respond clarifying the standing of the Chairs, so given the failure of the claimed Chairs on this matter I hold the current positions of the Chairs as untenable and ask you to please accept the handing back of your Chairs to the group by the end of the week to save the CG having to take action on this matter.

I call fresh elections of the CG Chairs and put forward the time frame of having these elections on the week ending the 10 Feb 2017 which gives people four weeks to consider stepping forward.

**Comment by lukewagner** [comment]
@wllang The Chairs of the WebAssembly CG are not elected according to a formal process because the WebAssembly CG has not yet adopted an *operational agreement*, as defined in the "Community Group Operational Agreements" section of the [Community Group and Business Process](https://www.w3.org/community/about/agreements/).  As defined by the CG process, when an operational agreement is adopted, it is chosen by the chair(s) and announced publicly.  This discussion illustrates that maybe we've waited too long to do so and should consider it in the near future.

Since the beginning, though, a primary and public goal of the CG has been to build and maintain consensus between the major browser engines since this has historically been such a critical, blocking and challenging feat to achieve.  While we also desire consensus within the entire CG, it's unrealistic to assume unanimity given the wide variety of backgrounds, perspectives, constraints, etc.  I do understand that it's frustrating when the consensus does not match one's preference on technical issues, though.

**Comment by wllang** [comment]
@lukewagner The 'Call for Participation in WebAssembly Community Group' notes that 'The group must now choose a chair', it does not mention appointment of Chairs via any other process and if no other process has been adopted then there still seems to be a significant lack of standing of many of the Chairs to be listed and claim to be Chairs, and this happened under your Chair. This is no small matter as the Chairs can publish a specification for the group - if these were just honorary positions then it would not matter. I repeat my request for the claBrham Giri Abhijith Chatra, Ben Titzer, and Filip Jerzy Pizlo to please accept returning their Chair by the end of the week and for you to also accept returning your Chair. I do not believe that wasm is ready for MVP, so disagree with the roadmap, and I will attempt to explain this to the CG members and seek their authority, if there is no interest or agreement then I'll give up and resign but I will have made by case in good faith trying to get a good outcome for the web community.

**Comment by thomvn** [comment]
The proposers of any CG may select the initial chairs in a manner of their choosing. The four chairs as listed for this CG conform to this initial process.  

Veronica Thom
Administrator for W3C CGs

**Comment by wllang** [comment]
@thomvn Thank you for the clarification, but unfortunately you comments leave a lot unanswered and unfortunately you do not appear to have the facts because Ben Titzer does not appear to have been an 'initial chair', and I question if anyone but Luke Wagner was an 'initial Chair'.

Irrespective of who is claiming to be a chair and their standing I allege that this group is not running well and that the design work has not been completed. We have chairs indicating an intention to publish and they appear to have the authority to do so, so this is an important matter. Also the Chairs have indicated an intention to transition to a W3C working group after which the members of the CG will clearly have not authority.

I allege that the initial members, specifically some groups representing some web browser vendors, have held a vice like grip over the authority of the CG and their tone has created a toxic working environment leading to the failure to explore the design space and thus their decision to publish is high questionable. I was working on this project before the creation of the CG and would have been an initial member if included but was not contacted. This is about getting a good design completed and out and I can not see this happening with the current working conditions and the current Chairs.

Unfortunately it seems I will have to take this case to the members to seek their authority, so if you are speaking for the W3C and/or for your customers holding the authority of this CG and if you are communicating that the W3C has the ultimate authority to dictate the Chairs of this CG and that you support the status quo then please let me know so that I can avoid taking the case to the members and so that I can resign so as not to be misrepresented as having been part of the decision making processes resulting in the output of this CG?

I have in the past demonstrated the performance of alternative designs and put forward many design ideas to explore and engaged in the technical discussions, so I hope the members accept that I have some genuine concerns about the technical design and that it is quite likely that I could demonstrate design alternatives that better meet the design principles of this project given some time. Let's not let the output of this process be one that history reflects on as being a failure of a toxic working environment to explore the design space. It had always appealed to me that in part this project could somewhat free the web community from endless disagreements and blocked paths by striping the web language to the core and allowing groups to explore their own paths by being able to efficiently target a web language.

**Comment by wllang** [comment]
@thomvn I can not substantiate your claims that "The proposers of any CG may select the initial chairs in a manner of their choosing." I refer to the W3C comments on choosing a chair at https://www.w3.org/community/about/tool/#choose-chair "Groups nominate their own Chairs and choose their own process for doing so."

Significantly I find no separate distinction for "proposers" and thus conclude that the four organizations and/or chairs did not have the authority to hold these positions at their choosing and that they have no more or less authority than other members of the CG, rather it appears to have always been a matter for the Group to decide. I note that the "Group" still has no explanation on how the chairs were chosen, so it seems fair to conclude that the Group did not "choose their own process for doing so" and thus the W3C processes were not followed. The matter will go to the Group members.

**Comment by jfbastien** [comment]
@wllang the reply you received from @thomvn was late Friday, and it is now early Sunday. I assume you'll get a reply on Monday, and suggest you not jump to conclusions based on lack of a reply over the weekend. It seems unlikely that the W3C's own CG administrator made unsubstantiated claims w.r.t. W3C CGs.

**Comment by wllang** [comment]
@jfbastien Happy to give the chairs and their organisations another week to accept that the battle is over and to return their chairs to the group, and I look forward to the group moving forward much more positively in 2017.

I have some items to float such as a competition with a number of rounds. This could offer recognition for the winners and perhaps we can even obtain some token funds for prizes, and I believe it could offer an objective and positive environment to get the best outcome for the web. With a number of rounds contestants could integrate the best for the next round, to get a well optimized design and sharing of ideas. It could be open to all members and even staff of organisations participating might benefit from recognition for good entries, so there need be not distinction between organisations and individual members contributing. We already have somewhat of a framework for people to work with, some tools and some implementations, but I wonder if we could get an end-to-end test for the competition so that the performance from decoding to execution would be assessed. The competition could have a time-line so that the project has a firm completion data at which the winning design is chosen so we get something out by the end of 2017 and address this issue.

**Comment by qwertie** [comment]
I would like say that I'd also like to get more involved; my lack of knowledge of how to build and use Wasm tools has been holding me back, but I'll make some time soon to figure it out. For example, I'd still like to push for inclusion of an [LESv3 subset](http://loyc.net/2017/lesv3-update.html) if I am granted an opportunity.

**Comment by wllang** [comment]
@qwertie I suggest looking ahead to an SSA encoding of wasm as it introduces some different common patterns and there is no need for the 'stacky' syntax rather it works well naming SSA definitions and referencing them by name. Perhaps in a few weeks I can get something presentable out, but perhaps take a look at this interesting project for another take on an SSA syntax that is not stacky https://github.com/stoklund/cretonne/blob/master/docs/langref.rst and names the SSA definitions, and wasm in SSA form has some resemblance to this with named SSA definitions and a functional presentation style, and the body of wasm blocks is similar to the cretonne `ebb` but wasm has structured blocks so it's syntax also is somewhat different.

**Comment by qwertie** [comment]
@wllang I will be neutral on whether SSA or the stack machine is better, as JITs are not my area of expertise. IMO, LES is well-suited to the current stack machine.

**Comment by thomvn** [comment]
@wllang 
* By default, it is left to CGs to determine how they choose their Chairs [1]:
   "The participants of the Group choose their Chair(s).”
* The people who launch a CG are allowed to name themselves Chairs.
* Some groups did not find that sufficient, so we started work on a more detailed (but not too onerous)
   chair selection algorithm [2]. That algorithm is not a requirement and is not formally a part of CGs.
* However, some CGs have adopted charters that include that algorithm. And our CG charter template
   includes the algorithm [3].
 * The WebAssembly CG does NOT have a charter, and so how they choose their
   Chairs is up to them (as a group). The Director and staff do not play a role in Chair selection for
   CGs. Chair changes after launch are also allowed and so the current four Chairs are indeed allowed to be the current Chairs of the CG
 * it may be possible to convince existing CG chairs to nominate others. But when it’s
   not, CGs are designed so that people can start their own easily.

[1]https://www.w3.org/community/about/agreements/
[2]https://www.w3.org/community/council/wiki/Chair_selection
[3]http://w3c.github.io/cg-charter/CGCharter.html

**Comment by wllang** [comment]
@thomvn Thank you for explaining this. I will defer taking the matter to the Group for now, but I would ask current Chairs to please take note the finding and to please ensure that future communication in relation to their standing reflects that their claim to the position of Chair is at the choice of the Group and ask them not to take significant actions such as closing the Group or publishing a specification without that being a choice of the group as a whole.
