### ISSUE TITLE
Interplay between memory section and memory import

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#942]
Scoped just for MVP, where there is at most one entry in the memory section and at most one memory import, we have the following 4 combinations. For some, I wasn't able to find specified behavior. What should it be? I took a shot below at summarizing what I think we spec-ed so far, plus some questions I think are open. 

mem section | module import | expectation
------------------|---------------------|-----------------
absent | absent | module is invalid if loads/stores are present; Question: memory provided as import at instantiation is ignored?
absent | present | module validates. Memory must be provided as import. Loads/stores may fail at runtime if oob
present | absent | module validates. At instantiation, runtime allocates memory with size equal to what the memory section's "min size" specifies. If, at instantiation, a memory import is provided, it is ignored (or?)
present | present | module validates (Question: what about the limits, may the import part omit them? Must be within what the mem section specifies?). If no memory import is provided, runtime allocates as per mem section spec. If memory import is provided, it will be used instead.

**Comment by lukewagner** [comment]
Just like the function index space is a concatenation of function-imports followed by function-definitions, so does the [memory index space](https://github.com/WebAssembly/design/blob/master/Modules.md#linear-memory-index-space) and [table index space](https://github.com/WebAssembly/design/blob/master/Modules.md#table-index-space).  The MVP limitation is that the memory and table index spaces must be size 0 or 1.  Thus, (present, present) is a validation error.

If you provide a memory/table as a property of the import object when the module has no declared memory/table import, resp., it is silently ignored; not having anything to do with memories/tables, but just because you can pass any number of superfluous properties on your import object.  (Maybe instead you are asking about the old, now-non-standard V8 API extension that let you pass a memory/arraybuffer directly as a second argument to instantiation?)

I *think* that covers the questions in your table; make sense?

**Comment by mtrofin** [comment]
Thanks, so what we have for MVP then is this - correct?

mem section | module import | expectation
------------------|---------------------|-----------------
absent | absent | module is invalid if loads/stores are present; memory provided as import at instantiation is silently ignored.
absent | present | module validates. Memory must be provided as import. Loads/stores may fail at runtime if oob
present | absent | module validates. At instantiation, runtime allocates memory with size equal to what the memory section's "min size" specifies. If, at instantiation, a memory import is provided, it is silently ignored
present | present | module fails validation

**Comment by lukewagner** [comment]
Yes.  (Technically, "Loads/stores may fail at runtime if oob" is also true for (present, absent).  And also all the statements apply *mutatis mutandis* to tables; in particular `call_indirect` fails to validate if you have no table import or definition.)

**Comment by rossberg-chromium** [comment]
Closing. Modules.md states that "there may be at most one linear memory import or linear memory definition". Moreover, all cases are covered by both the spec interpreter and the test suite.
