### ISSUE TITLE
Imported memory validation step

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/design#943]
According to https://github.com/WebAssembly/design/blob/master/Modules.md#imports, there needs to be a validation for an imported memory.
We should also add this to [JS.md](https://github.com/WebAssembly/design/blob/master/JS.md#webassemblyinstance-constructor) in the steps when importing a memory or at least make a reference to the validation.

**Comment by lukewagner** [comment]
Technically this validation is done within `Eval.init` (in [`add_import`](https://github.com/WebAssembly/spec/blob/master/interpreter/spec/eval.ml#L390) which calls [`check_limits`](https://github.com/WebAssembly/spec/blob/master/interpreter/spec/eval.ml#L380) for memory and table imports) since this is part of core wasm semantics, not the JS binding, but you're probably right that it'd be more clear to make a mention in JS.md with link to Modules.md in the associated memory/table import cases.

**Comment by lukewagner** [comment]
Should be resolved by #945.
