### ISSUE TITLE
relation between return values from Module.imports/exports

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#946]
in the following snippet:

var m1 = Module.imports(myModule);
var m2 = Module.imports(myModule);

what is the relation between m1 and m2?

same for exports

**Comment by mtrofin** [comment]
To be more specific, which is true:

m1 === m2
m1 == m2
...?

**Comment by jfbastien** [comment]
I think identity is ill-defined in many places, this one included. See #920. We should go through and define everywhere.

**Comment by mtrofin** [comment]
Yes, but define it to what?

**Comment by jfbastien** [comment]
Whatever makes more sense, ideally consistent with other JS things. Identity of the JS API values is something I'd like to see resolved before MVP, how it's resolved doesn't really matter to me as long as it's sane.

**Comment by mtrofin** [comment]
Order of elements in the array, and the way that relates to the order of elements in the binary, is another thing. I suppose we can spec the order as preserving the one in the binary.

Other concerns: are the "m"s mutable? what about their content?

**Comment by jfbastien** [comment]
The rule is usually: if it's mutable then each array is a new copy, so they have separate identity. IIRC we did that elsewhere.

Elsewhere as well, we did in-binary order.

So what you propose seem like good clarifications.

**Comment by mtrofin** [comment]
#948 is related

**Comment by lukewagner** [comment]
Yes, the current wording does say we're returning an `Array` object each time (otherwise we'd have to have wording about caching/reusing it), but specifying a *new* `Array` would help.  And agreed that the intention of the current phrasing of mapping imports/exports to array elements does mean preserving order and that could be clarified as well.

So then to the original question: neither `==` or `===` hold.

@jfbastien Although I think you were thinking of *exported wasm functions*, which is a separate issue from what @mtrofin is asking about here, I think we do now actually have a well-defined identity; it's just not super-clearly stated.

**Comment by mtrofin** [comment]
Opened #957 for the APIs discussed here. Will close this issue once we feel we covered all the APIs (I haven't myself just yet).
