### ISSUE TITLE
WebAssembly.imports/exports: why Array and not Iterable?

### ISSUE THREAD

**Issue by mtrofin** [WebAssembly/design#948]
The size of imports/exports may be large. Instead of pre-allocating an Array, why not return an object conforming to the Iterable protocol, thus avoiding memory pressure?

**Comment by Kardax** [comment]
Arrays have many useful features and characteristics, and would represent a very small portion of the memory used by any non-trivial WASM file.  I don't see any issue with this aspect of the design.

**Comment by jfbastien** [comment]
@Kardax right, but if you want an array then you can use spread syntax with something using the iteration protocol. You can't do the reverse.

Which one is more desirable is based on what's more idiomatic "modern" JS. If we change here we should also change other APIs, such as `Module.customSections`.

**Comment by rossberg-chromium** [comment]
The size of imports/exports may be large but it is clearly dominated by the size of the binary, so shouldn't matter in practice.

It is normal in JS to use an array for this kind of thing, see e.g.  the analogue `Object.keys` and friends.

**Comment by mtrofin** [comment]
It matters when you are memory constrained. By returning an array, we increase memory pressure.

**Comment by jfbastien** [comment]
@rossberg-chromium normal in ye-olden JS. Is it normal in "modern" JS? If so I think we should follow "modern".

Agreed import/export aren't big, but `customSections` could be.

**Comment by lukewagner** [comment]
While I expect the payload of some custom sections to be big, I expect the number of custom sections (esp., with a particular name) to be pretty small.

My impression is that, even for huge modules, we're talking 100s of imports/exports, and then only for huge modules where the bytecode is 1000x bigger than the aggregate size of the returned arrays.  So I think an Iterable would be overkill.  Also, these functions are really just a convenience to allow clients to avoid manually decoding the binary, but manually decoding is actually pretty easy (that's what @yurydelendik and @kripken did in their respective module loaders before we added these functions) so that's always a workaround for users in pathological situations (who might want to avoid the GC allocation of an iterable altogether).

**Comment by mtrofin** [comment]
@lukewagner What about customSections, as @jfbastien mentioned?

If these APIs are just convenience, why even include them - did we have a strong ask/scenario for them? We can always add later (apologies if this was discussed elsewhere - if so, pointer, pls)

**Comment by jfbastien** [comment]
It was added because it's very simple, and otherwise tools such as emscripten's generated code end up decoding the sections themselves in the browser, which is kinda silly. Adding it later basically means we're stuck with silly code forever.

**Comment by mtrofin** [comment]
So Emscripten offers the main usecase for all 3 APIs, or just for Imports & Exports? When using Imports & Exports, does it end up visiting all imports/exports? What about customSections - is Emscripten code the user, or would that be rather exposed to developers, and how do we envision the usage pattern look like?

**Comment by rossberg-chromium** [comment]
@jfbastien, yes, even ES2015 methods like `Object.getOwnPropertySymbols` or ES2017 methods like `Object.entries` and `Object.values` return arrays.

I assume `customSections` arrays will be even smaller in practice (typically size 1), because they only collect all sections of _one_ particular name.

**Comment by jfbastien** [comment]
@rossberg-chromium thanks! I think it's better to follow what "modern" JS APIs do, so Array seems like the right thing.

**Comment by mtrofin** [comment]
I suppose we can close this - the group's position is to leave the APIs as Arrays.
