### ISSUE TITLE
Remove the explict `end` to function bodies in the binary

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/design#994]
There doesn't seem to be a rational for the explicit end after the function bodies in the binary

**Comment by rossberg-chromium** [comment]
The rationale is twofold:

1. Regularity: all instruction sequences end in `end` (or another terminator like `else`), i.e., blocks, expressions (e.g. for global initializers or segment offsets), functions.

2. Layering: section sizes only need to be checked in the end, they don't otherwise affect decoding. A binary can be parsed as a (quasi) context-free grammar. That separates decoding from navigation concerns.

**Comment by wanderer** [comment]
> Regularity: all instruction sequences end in end (or another terminator like else), i.e., blocks, expressions (e.g. for global initializers or segment offsets), functions.

this doesn't quite make sense to me, since there is no explicit function start or block. point 2 make sense!

**Comment by rossberg-chromium** [comment]
[oops wrong button]
@wanderer, initializer expressions don't have that either.

**Comment by wanderer** [comment]
right, and the init_expr don't have a size associated with them so there is no way around having the delimiter and it makes sense to keep the all expression encoding uniform

**Comment by jfbastien** [comment]
Note that length field for `init_expr` was discussed in #857.
