### ISSUE TITLE
Add rationale for polymorphic typechecking to Rationale.md

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/design#998]
I have a few questions about the following paragraph in Validation section of [Semantics.md](https://github.com/WebAssembly/design/blob/master/Semantics.md).

> A special case is unconditional control transfers (br, br_table, return, unreachable) because execution never proceeds after them. The stack after such an instruction is unconstrained and thus said to be polymorphic. The following instructions still must type-check, but conceptually, values of any type can be popped off a polymorphic stack for the sake of checking consecutive instructions. A polymorphic stack also matches any possible signature at the end of a block or function. After the end of a block, the stack is determined by the block signature and the stack before the block.

1. Can somebody clarify what means "values of any type can be popped off a polymorphic stack", but "the following instructions still must type-check"? Sounds some like contradictory to me.

2. "A polymorphic stack also matches any possible signature at the end of a block or function."
So in code below (emscripten generated $stackAlloc)
```
func i32
  block i32
    ...
    get_local 0x1
    return
  end
end
```
`return` pops last value from the stack, so when we hitting `end` of `block i32` there are no more operands on the stack. But because the stack is polymorphic we accept that, pop control stack, and we should push i32. Then we are hitting `end` of `func i32`, and we are poping that i32 and return it (because of implicit `end` of `func` behavior). 
Am I get it right?

3. Why is this polymorphic stack thing even needed in a first place? Why just not throw validation error on an unreachable code?

**Comment by rossberg-chromium** [comment]
On 27 February 2017 at 09:40, Sergey Pepyakin <notifications@github.com>
wrote:

> I have a few questions about the following paragraph in Validation section
> of Semantics.md
> <https://github.com/WebAssembly/design/blob/master/Semantics.md>.
>
> A special case is unconditional control transfers (br, br_table, return,
> unreachable) because execution never proceeds after them. The stack after
> such an instruction is unconstrained and thus said to be polymorphic. The
> following instructions still must type-check, but conceptually, values of
> any type can be popped off a polymorphic stack for the sake of checking
> consecutive instructions. A polymorphic stack also matches any possible
> signature at the end of a block or function. After the end of a block, the
> stack is determined by the block signature and the stack before the block.
>
>
>    1.
>
>    Can somebody clarify what means "values of any type can be popped off
>    a polymorphic stack", but "the following instructions still must
>    type-check"?
>
>
Other values may be pushed onto a polymorphic stack and must still be
consumed correctly. E.g.

    unreachable (i64.const 0) i32.add

is malformed.


>    1.
>    2.
>
>    "A polymorphic stack also matches any possible signature at the end of
>    a block or function."
>    So in code below (emscripten generated $stackAlloc)
>
> func i32
>   block i32
>     ...
>     get_local 0x1
>     return
>   end
> end
>
> return pops last value from the stack, so when we hitting end of block i32
> and there are no more operands on the stack. But because the stack is
> polymorphic we accept that, pop control stack, and we should push i32. Then
> we are hitting end of func i32, and we are poping that i32 and return it
> (because of implicit end of func behavior).
> Am I get it right?
>

Yes, that's right.


>
>    1. Why is this polymorphic stack thing even needed in a first place?
>    Why just not throw validation error on an unreachable code?
>
>
Long history to that, but in a nutshell, disallowing unreachable code would
be painfful for (some) producers, there is no precedent for it in other
code formats, and implementing polymorphic checking turns out to be only
marginally more complicated. (For a recent summary see
https://docs.google.com/presentation/d/11lO0bJ0G4fMRoeSFyhky1WeJk2YBvfNblt3CGtiiSE4/
and for a pseudo code checking algorithm see
https://docs.google.com/document/d/1E9zNSnATBeETbIAcrwblDrEKKaR5enjNNk4PhlN0a4c/
)

**Comment by pepyakin** [comment]
@rossberg-chromium thank you for your explanaition!

> Other values may be pushed onto a polymorphic stack and must still be
> consumed correctly. E.g.
> 
>     unreachable (i64.const 0) i32.add
> 
> is malformed.

Can you explain, why this is malformed? Because i32.add have only one operand, because this one operand have i64 type, or because i32.add lefts one unconsumed operand on the stack, or because all of this or something else?

**Comment by binji** [comment]
I'm not sure this is the correct way to explain it, but here's how I think of it:

An `unreachable` (or `br`, `return`, etc.) make the stack polymorphic. This means we don't know what the stack contains anymore -- it could be anything. But as we continue to iterate through operators, we can determine what the stack _must have been_, for everything to be valid. If there is a contradiction, that means that the instruction sequence is malformed.

So, for example: `unreachable i32.add`: the `unreachable` makes the stack polymorphic. Then the `i32.add` requires two i32 values. Since the stack is polymorphic, we can make it whatever we want. In this case, the stack must have contained `i32 i32` for everything to be valid. So this example is valid.

Another example: `unreachable drop`: in this case, `drop` is type-parametric, so it can consume any concrete type. So the stack could have been `i32` or `i64` or `f32` or `f64`. But it could not have been empty (or had two values, etc.) So this example is also valid.

Now, `unreachable (i64.const 0) i32.add`: unreachable makes the stack polymorphic, then an i64 value is pushed on. At this point we try to perform `i32.add`, but there's no concrete stack where this would be valid. The polymorphic stack part can be replaced by any concrete stack of any size, but there's still that pesky i64 on top. So this example is invalid.

Finally, a way to make the last example valid: `unreachable (i64.const 0) i64.add`. Now we have a polymorphic stack, and we push on an i64. `i64.add` requires the stack to have `i64 i64`, so we pop the first i64, then we pop from the polymorphic stack. Since we can make the polymorphic stack whatever we want, we choose `i64`, since that's required to make it valid. So this example is valid.

I'm probably screwing up terminology here, but I think this is mostly correct. :-)

**Comment by jfbastien** [comment]
It would be great to add this information to Rationale.md.

**Comment by rossberg-chromium** [comment]
What @binji said. @jfbastien, good idea.

**Comment by pepyakin** [comment]
@binji thanks for your thorough explanation!

**Comment by jfbastien** [comment]
Can someone file a PR for this?

**Comment by pepyakin** [comment]
Awesome! I think this can be closed now
